### ISSUE TITLE
Checkout with paypal takes ~10s on production ...

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#101]
... and there is no indicator right now that something's going on, so the user will surely think it ain't working and drop it, just to be billed anyways. demo: https://read2me.online/ (you have to be logged in)

**Comment by crookedneighbor** [comment]
Thanks for reporting this.

When we switch to use the [`paypal-checkout` component](http://braintree.github.io/braintree-web/current/PayPalCheckout.html) with [checkout.js](https://github.com/paypal/paypal-checkout) this should be solved, as checkout.js will provide UI to indicate that the transaction is still in progress.

**Comment by NinoSkopac** [comment]
Awesome. Any ETA on that? Will it break BC?

**Comment by crookedneighbor** [comment]
I'm working on the PR right now. We're waiting for a change on the Braintree gateway before we can merge it in. The one required change for you will be that you will need to create and link a PayPal sandbox account in your Braintree GW.

I do not have an ETA yet.

**Comment by crookedneighbor** [comment]
You may want to consider passing `intent: 'sale'` in your PayPal config. That should speed up the process a bit as it does an auth and capture in one step instead of doing that work on the server after the fact.

http://braintree.github.io/braintree-web/current/PayPal.html#tokenize
