### ISSUE TITLE
There are inconsistencies between translations of string 'payingWith'

### ISSUE THREAD

**Issue by juongithub** [braintree/braintree-web-drop-in#104]
### Issue description

The string _payingWith_ is translated differently in various languages. For example, in _en.js_, it is simply "Paying with" whereas in _it_IT.js_ is "Pagamento con {{paymentSource}}," but _paymentSource_  is left unchanged.

Actually, the problem is in the translation itself, or in the fact that the string _paymentSource_ is not replaced with a correct value.

**Comment by crookedneighbor** [comment]
Thanks for spotting this. I'll look into it today.
