### ISSUE TITLE
Issue in main.scss

### ISSUE THREAD

**Issue by juongithub** [braintree/braintree-web-drop-in#107]
Please note that at line 517 of main.scss:

`transition: font-weight 300;`

there is an error.

**Comment by crookedneighbor** [comment]
Thanks for catching this.

@lilaconlee any idea what this was _supposed_ to be? I think we can safely just remove the line.

**Comment by crookedneighbor** [comment]
The commit for reference: https://github.com/braintree/braintree-web-drop-in/commit/900fdce8b20251471644e0974eca89441cc1b0fa#diff-0f7bc6b0448cbca0959b2e11d9ee62f6R495
