### ISSUE TITLE
PayPal Vault Callback?

### ISSUE THREAD

**Issue by bkonia** [braintree/braintree-web-drop-in#110]
When adding a credit card, we bind the Submit button to requestPaymentMethod, which provides a callback to execute additional actions, after the credit card has been added.

When adding a PayPal account using the Vault workflow, it opens a popup window, which allows the user to login to his PayPal account and authorize it, after which, it closes the popup window and returns the user to the main window. I need to execute additional actions after this process completes, but I can't find any event or callback to hook into, that would execute when the PayPal authorization is complete. Am I missing something? If no such callback exists, would you consider adding one?

**Comment by crookedneighbor** [comment]
We haven't finished this work yet, but if you look at the [beta notes in the README](https://github.com/braintree/braintree-web-drop-in#beta-notes), you'll see that a full event API is forthcoming. This will let you know when a payment method is able to be requested as soon as it is available.

**Comment by intelliot** [comment]
@bkonia To help us understand this use case better, what's an example of an additional action that you need to execute when the PayPal authorization is complete?

**Comment by bkonia** [comment]
I'm using Drop In form solely for vaulting payment information, not for processing payments. I have another form on the same page where the user can submit a payment using one of his vaulted payment methods. With credit cards, after the user adds a card, I use the callback to make an AJAX request to a script that returns the current list of payment methods. I then update the "Payment Method" select box on my payment form. This allows me to update the select box immediately, without having to reload the entire page. I'd like to do the same thing with PayPal. After a user adds his PayPal account, I want to update the select box so it shows his PayPal account as an available payment method.

**Comment by crookedneighbor** [comment]
We've just released version 7 of the beta which includes events for when paypal is request-able. See https://github.com/braintree/braintree-web-drop-in#events for details

New beta build is: 

```
<script src="https://js.braintreegateway.com/web/dropin/1.0.0-beta.7/js/dropin.min.js"></script>
```
