### ISSUE TITLE
Web Drop-in Translations Requests

### ISSUE THREAD

**Issue by intelliot** [braintree/braintree-web-drop-in#116]
Use this issue to track requests for language translations.

- Latvian (requested by @Cracken6 [here](https://github.com/braintree/braintree-web-drop-in/issues/83#issuecomment-290547151))

**Comment by lilaconlee** [comment]
Closing this issue now that you can supply your own translations when [creating Drop-in](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create).
