### ISSUE TITLE
Minified Dropin Breaks

### ISSUE THREAD

**Issue by trigun0x2** [braintree/braintree-web-drop-in#145]
## General information

SDK/Library version: DropIn UI 1.0.0-beta.5 with SDK v3
Environment: Sandbox/Prod
Browser and OS: Chrome (multiple version) on MacOS 10.12.4

## Issue description

Everything works fine when gulp does not minify our compiled JS. But once minified, it no longer attaches to the div and gives no errors in console.

**Comment by crookedneighbor** [comment]
Can you try with beta.7? If the issue persists, can you provide the gulpfile you're using so we can more easily replicate it?

**Comment by trigun0x2** [comment]
Sorry I just updated to beta.7. I'm not sure what I can show you from the gulp file since it's our production file.

**Comment by crookedneighbor** [comment]
Well, there are numerous ways to minify with gulp. Even just providing your minification task would be enough to give us something to reproduce.

**Comment by crookedneighbor** [comment]
I've put together a demo with various ways to include drop-in on your page (including directly from the cdn, browserified from npm, and concatting and minifying files with gulp): https://crookedneighbor.github.io/braintree-web-minification-demo/

This is what I have for my Gulpfile and it works. https://github.com/crookedneighbor/braintree-web-minification-demo/blob/master/gulpfile.js

Happy to help you troubleshoot what's going wrong with your minification, but I'll need to be able to reproduce it first.

**Comment by trigun0x2** [comment]
Let me chat with my team, but for now I've included the dropin.js in the header of the page.

**Comment by crookedneighbor** [comment]
I'm going to close this, but feel free to comment here when you're ready to dig into it and I'll re-open the issue.
