### ISSUE TITLE
beta-6 to beta-7 migration

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#146]
Hey, is there anything I should know when it comes to latest beta migration? I checkout your releases, but there are no release notes.

What's changed? Any BC breaks?

I'm using this in production.

Thank you

**Comment by crookedneighbor** [comment]
Release notes are in the CHANGELOG.md https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#100-beta7

The only thing that you may need to update is that using PayPal in sandbox now requires a [linked sandbox account](https://developers.braintreepayments.com/guides/paypal/testing-go-live/php#linked-paypal-testing). Should need no changes for production use.

**Comment by NinoSkopac** [comment]
Thanks.
