### ISSUE TITLE
Web Drop-In Is Almost Suitable As Credit Card Management Page

### ISSUE THREAD

**Issue by danielrobbins** [braintree/braintree-web-drop-in#153]
The Web drop-in UI is so very close to being useable as a credit card management page. What I mean is that it is very useful even if you are not planning to capture the nonce and send it to the server.

The one functionality I am missing is having the option of adding a button underneath the payment method entry area that says "Add This Payment Method" (matching the "Choose Another Way to Pay" button) which only appears when adding a new payment method and causes the entered CC information to be validated, and if valid, saved. "Choose another way to pay" and this "Add this payment method" button would never be displayed at the same time.

For my app, the customer must set up a credit card prior to requesting services (in this particular case, we are driving people home who have been drinking and it's ideal to get CC info entered when sober.)

**Comment by crookedneighbor** [comment]
This should already be doable by leveraging the [events api](https://github.com/braintree/braintree-web-drop-in#events). Here's a repo that does it: https://github.com/crookedneighbor/braintree-web-drop-in-payment-method-manager

And a live github pages to illustrate it: https://crookedneighbor.github.io/braintree-web-drop-in-payment-method-manager/

If this does not solve your problem, feel free to comment here and I'll re-open the issue.

**Comment by pootzko** [comment]
Just to save someone else a bit of time, here is a fixed link to the events API:
https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on
