### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by buu700** [braintree/braintree-web-drop-in#158]
Is reference documentation for this module planned? The readme helps, but without some basic information about the `braintree.dropin` interface at https://braintree.github.io/braintree-web/current porting my existing Braintree v2 dropin code will be an unnecessary hassle.

**Comment by lilaconlee** [comment]
Thanks for the feedback! We've got some additional Drop-in documentation in our [developer docs](https://developers.braintreepayments.com/guides/drop-in/javascript/v3), but nothing quite like the client reference. 

We'll definitely keep this in mind as we keep making improvements!

**Comment by crookedneighbor** [comment]
We now have reference documentation up. https://braintree.github.io/braintree-web-drop-in/docs
