### ISSUE TITLE
JS Exception on IE9: SCRIPT438: Object doesn't support property or method 'setRequestHeader'

### ISSUE THREAD

**Issue by dpolivy** [braintree/braintree-web-drop-in#169]
### General information

* SDK/Library version: 1.0.2
* Environment: Production
* Browser and OS: IE9 on Windows 7

### Issue description

IE9 is throwing a script error when loading the drop-in.

`SCRIPT438: Object doesn't support property or method 'setRequestHeader'`

It may be harmless (drop-in still seems to work) but it would be better to gracefully handle this case instead of throwing an unhandled exception.

### Repro

Open IE9 on Windows 7 (using browserstack.com or similar).
Navigate to: https://developers.braintreepayments.com/guides/drop-in/javascript/v3
Open the F12 developer tools and view the console.

**Comment by crookedneighbor** [comment]
Thanks for the report. This is coming from PayPal's [checkout.js library](https://github.com/paypal/paypal-checkout/blob/de6d31b5b1bc678f8623647cc76410e50cf5ef3a/src/lib/http.js#L98). We're checking in with the team that manages it.

**Comment by crookedneighbor** [comment]
Closed via https://github.com/braintree/braintree-web-drop-in/pull/236

Will be out in the next release.
