### ISSUE TITLE
Default Card Option not available

### ISSUE THREAD

**Issue by HaoGeng** [braintree/braintree-web-drop-in#171]
### General information

* SDK/Library version: 1.0.2
* Environment: Sandbox
* Browser and OS : Chrome and expo ios simulator

### Issue description

using 
braintree.dropin.create({
      authorization: 'token',
      selector: '#dropin-container',
      paypal: {
            flow: 'vault'
        },
    },function (createErr, instance) {

but only paypal shows up without the default card option. if I take paypal out, there will be no option displayed

I want both paypal and card options
<script src="https://js.braintreegateway.com/web/dropin/1.0.2/js/dropin.min.js"></script>

**Comment by crookedneighbor** [comment]
Do you have any processor connections for cards set up in your Braintree Gateway? If you give us your merchant id, we can look that up for you if you are unsure how to check.

**Comment by crookedneighbor** [comment]
@HaoGeng We haven't heard back from you about this, so I'm going to close the issue. If you still need assistance, feel free to comment here.
