### ISSUE TITLE
Form-fill with LastPass results in incomplete CC#

### ISSUE THREAD

**Issue by dpolivy** [braintree/braintree-web-drop-in#198]
### General information

* SDK/Library version: 1.0.2
* Environment: Production
* Browser and OS: Chrome 58 on Windows 10

### Issue description

A user has reported this issue, which I have been able to verify.

1. Setup the LastPass browser plugin.
2. Add a Form Fill profile with a credit card. Ensure the credit card number does not have spaces in it when entered into LastPass, e.g. `4111111111111111`.
3. Navigate to a page with the drop-in UI.
4. Initiate the form fill with LastPass using the previously added card profile.

*actual*
The filled in credit card number is missing the last 3 digits:

![image](https://cloud.githubusercontent.com/assets/3200655/26802772/a2bb6306-49f6-11e7-80ea-d7bffcf0cf98.png)

*expected*
The filled in credit card will contain the complete credit card number.

Note: this only seems to repro with LastPass, and not if you paste in a credit card number manually. There must be some issue with the form validation and how LastPass enters the info.

**Comment by lilaconlee** [comment]
To collect credit card information, Drop-in uses Hosted Fields from braintree-web where we have known issues with [credit card autofill](https://github.com/braintree/braintree-web/issues/239). We've got some fixes in the works that should be out soon, so we'll update this issue when they're available as part of Drop-in.

**Comment by dpolivy** [comment]
Thanks @lilaconlee! Looking forward to trying these fixes.

**Comment by lilaconlee** [comment]
Autofill fixes from braintree-web [3.18.0](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#3180) are released in braintree-web-drop-in [1.3.0](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#130). Let us know here if you run into any issues!

**Comment by dpolivy** [comment]
@lilaconlee LastPass on iOS 11 seems to be having issues auto-filling with drop-in v1.8.0 (as in, it doesn't work). Need me to file a new issue, or can you take a look?

**Comment by crookedneighbor** [comment]
@dpolivy I assume lastpass is just using the iOS clipboard under the hood, so [your issue here](https://github.com/braintree/braintree-web-drop-in/issues/299) will be what we use to track it. Thanks!

**Comment by dpolivy** [comment]
@crookedneighbor I'm not so sure about that, I think it might inject JavaScript into the page. Also, the behavior is different in that it isn't a formatting issue, but rather, it just doesn't insert anything anymore.

**Comment by crookedneighbor** [comment]
Thanks for the info. I assume though that whatever change was made in iOS 11 to change this behavior is related. We'll look into both.

**Comment by dpolivy** [comment]
@crookedneighbor 1.9.0 does not fix the LastPass issue - I am unable to fill the card form on iOS. Should I open a separate issue for this?

**Comment by crookedneighbor** [comment]
@dpolivy Sure, but do so on https://github.com/braintree/braintree-web, since that's actually where this is happening.

**Comment by crookedneighbor** [comment]
Thinking about this more, I think the problem _may_ be that the Lastpass extension on iOS can't see the Hosted Fields iframes as valid inputs for inserting credit cards. I'm guessing it's using JavaScript under the hood, and it can't access the inputs.

The reason the desktop version works, is because it's inserting the JavaScript it needs to run directly into the iframes. My assumption is that iOS has some restriction around that.

Will investigate, but that's my hunch.

**Comment by crookedneighbor** [comment]
Yep, that's exactly it. If you connect your iOS device to a mac and open the Safari dev tools, you'll see a message like this:

> Blocked a frame with origin "https://your-domain.com" from accessing a frame with origin "https://assets.braintreegateway.com". Protocols, domains, and ports must match.

I don't think there's anything we can do about that. The way Lastpass's system, it _cannot_ run the JavaScript in the iFrames.

**Comment by dpolivy** [comment]
@crookedneighbor Thanks for investigating. Can you file an issue with LastPass to see if they can do anything about (since you own the form)?

**Comment by crookedneighbor** [comment]
I've sent an email. I expect that their implementation is limited to what Apple allows them to do, but if I hear back otherwise, I'll update this issue.
