### ISSUE TITLE
Hitting Enter/Return Key while focus is on Credit Card CVV/Expiration Date/ZIP fields clears existing input and makes them uneditable

### ISSUE THREAD

**Issue by h4r5h4** [braintree/braintree-web-drop-in#205]
### General information

* SDK/Library version: 1.3.0
* Environment: Sanbox & Production
* Browser and OS : Chrome58.0.3029.110 (64-bit) on MacOS 10.12.4

### Issue description

You can test this out by generating a Credit Card Form and hitting Return key when one of these fields are focused. (Expiration Code/CVV/Postal Code).

I did not get to check what's causing the issue, but can confirm this is not happening on older versions.

Linking a fiddle if anyone wants to try it out quick.
https://jsfiddle.net/ww7c27xv/show/

Focus your pointer on Expiration Date, Hit Return Key and try to enter anything in the same field.

**Comment by lilaconlee** [comment]
This is an issue with Hosted Fields in [braintree-web](https://github.com/braintree/braintree-web) 3.18.0 which we use to collect card information in 1.3.0. We'll make a fix in braintree-web and let you know when we've updated the version here. Thanks for reporting the issue!

**Comment by lilaconlee** [comment]
This issue is fixed as part of [1.3.1](https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#131).

**Comment by h4r5h4** [comment]
Thanks for the quick fix 👍
