### ISSUE TITLE
Paypal checkout question

### ISSUE THREAD

**Issue by victor-von** [braintree/braintree-web-drop-in#207]
### General information

* SDK/Library version: 3
* Environment: Sandbox
* Browser and OS: Chrome 58.0.3029.110 (64-bit) on MacOS 10.12.5

### Issue description

I am in the process of integrating drop-in to my web page following your drop-in example as guideline with two payment types: credit card and paypal checkout. Credit card works great but I am having issue with Paypal checkout.

The problem with Paypal checkout is that when I hit Paypal checkout button it basically redirect me to Paypal checkout web page which just went through the whole payment process while my original form is still waiting the 'submit' button to be hit to move on to next step (calling requestPaymentMethod on drop-in instance, like what your example does). 

I think there should be a way for my form to be notified when 
1. Payment method has been changed, and
2. When Paypal checkout window is closed, either with sucess or with error.

Thanks.

**Comment by victor-von** [comment]
My bad, a similar issue was asked and solved. I think I know how to solve this.

**Comment by crookedneighbor** [comment]
Glad you figured it out. I assume you leveraged the events API?

**Comment by victorvon** [comment]
Yes, exactly.

**Comment by pootzko** [comment]
Just to save someone else a bit of time, here is the link to the events API:
https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on
