### ISSUE TITLE
"Choose another way to pay" unclickable after payment

### ISSUE THREAD

**Issue by Beastw00d** [braintree/braintree-web-drop-in#210]
### General information

* 1.3.1
* Sandbox
* Chrome 57.0.2987.98 (64-bit)  and Firefox 53.0.2 (64-bit)

### Issue description

As a user with already one saved credit card I want the page to reload after a payment goes through the server, regardless of success or failure, and to be able to make another payment using the drop-in UI. I want to be able to choose from the saved credit or  'choose another way to pay'.

After a payment goes through on the server the page refreshes. The user has a list of items that he can click pay on which will pop open a modal with the drop-in UI, and the majority of the time the "Choose another way to pay" link/button will not be clickable. I am assuming there is some sort of caching on braintree's side because the few times it works it is because the whole drop-in component reloads.

**Comment by Beastw00d** [comment]
![braintree2](https://user-images.githubusercontent.com/8293827/27364255-6d8171c2-5607-11e7-8ec2-a7f384381040.gif)

This is what I mean by unclickable.

**Comment by crookedneighbor** [comment]
Do you have a staging site we can examine? Or a sample site on Github that reproduces the behavior?

**Comment by Beastw00d** [comment]
I don't not. Ill try wire one up today.

**Comment by Beastw00d** [comment]
@crookedneighbor I've made a sample of what we are trying to achieve. 

1. Code: https://github.com/Beastw00d/beastw00d.github.io/blob/master/index.html
2. Page: https://beastw00d.github.io/

Unfortunately this doesn't recreate the issue because it only happens when there is at least one saved credit card and I would have to set up a server to do that. I've started to think it is happening because the modal is hidden away (loaded in DOM) and the drop-in UI is created on that hidden modal right on the page load. I've been able to fix it in the real code by wiring up the create on the modal opening. The only problem with this is it makes the modal jump in size because will take half a second start loading so if this is the solution I have to go with then I'll probably have to mess with the sizing. 

`
$('#braintree.modal').on('shown.bs.modal',
        function() {
            var button = document.querySelector('#submit-button');
            braintree.dropin.create({..});
       });
`

**Comment by crookedneighbor** [comment]
Thanks for creating the page. I used Chrome dev tools to insert a client token with saved payment methods to test it.

Okay, so I think the problem is in the transition helper library: https://github.com/braintree/braintree-web-drop-in/blob/7b96efab4d64e8257d504f11b7195e2a540f14e4/src/lib/transition-helper.js

I think that since you have the modal hidden, the loading div never gets properly cleaned up. We'll look into fixing this. Thanks for reporting it!
