### ISSUE TITLE
Selected method changed event? paymentMethodRequestable inconsistency

### ISSUE THREAD

**Issue by pootzko** [braintree/braintree-web-drop-in#211]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.3.1/js/dropin.min.js
* Environment: Sandbox, AngularJS
* Browser and Chrome 59 (64-bit) on Win10

### Issue description

Hi all,

I feel that having `paymentMethodRequestable` and `noPaymentMethodRequestable` is not really enough to get a flawless workflow with the drop-in. Let's take these few images as an example of what I'm thinking of:

Step 1.
 - user enters the details of a card he wants to use
 - `paymentMethodRequestable` fired, it's now safe for the user to click the "Select payment method" button so we unhide it
 - the user clicks the button button which calls `dropInInstance.requestPaymentMethod()`
 - we obtain the nonce, hide the "Select payment method" button, the drop-in changes to "Paying with card" view and we display the "Pay" button - Step 2.
 - if the user clicks the "Pay" button, we make a request to the back-end which then creates a transaction
 - all fine so far

![payment - quickdbd - google chrome](https://user-images.githubusercontent.com/535842/27401796-6c3ba0de-56bc-11e7-81a8-39c3e9b79663.jpg)

Step 2.
 - the user changes his mind, and clicks the "Choose another way to pay" button
 - at this point `noPaymentMethodRequestable` event has fired 
 - we hide both the "Select payment" and "Pay" button because it makes sense to do so
 - the user is taken to Step 3.

![payment - quickdbd - google chrome_2](https://user-images.githubusercontent.com/535842/27401805-705bd8d2-56bc-11e7-9cfa-f43488412489.jpg)

Step 3.
 - this is where the inconsistency lies and where I feel the problem is

Step 3.1.
 - if we click on the top button (original card details ending with 11), `paymentMethodRequestable` is fired but the drop-in also automatically takes you back to the Step 2., only this time with the wrong button being displayed ("Select payment method")
 - this time we don't have to click that button because the drop-in is already aware of the current nonce, our app has it cached in current controller instance and making an additional request in unnecessary
 - having to click this button one more time is redundant and brings a bit of confusion to the UX
 - instead, we want to display the "Pay" button

Step 3.2.
 - if we enter new card details the `paymentMethodRequestable` fires after the last detail is entered
 - now we can display the "Select payment method" button which in this case is correct
 - we click the button, it calls the `dropInInstance.requestPaymentMethod()`, gets the new nonce and the user gets taken to Step 2.
 - this time the correct button is displayed ("Pay")

![payment - quickdbd - google chrome_3](https://user-images.githubusercontent.com/535842/27401811-734ffabe-56bc-11e7-9a2c-2b9e7d6d099b.jpg)

To me it seems that with the current combinations of events which the drop-in lib provides, it's impossible to get the workflow to avoid that redundant "Select payment method" click. Am I right or is there perhaps a way to do it and I'm totally clueless? Is there a way to know whether the `paymentMethodRequestable` came from clicking on an existing payment method or from filling the form with the last bit of information?

I believe the needed information (origin of event) could be put inside the `even` param of the `paymentMethodRequestable` event callback. That would make these two events distinguishable and it would help a lot.

Thanks!

**Comment by crookedneighbor** [comment]
To confirm, what you're asking for is that when `paymentMethodRequestable` fires, you want the event to include some indication about whether or not the payment method is cached in Drop-in or not, right?

Something like:

```js
dropinInstance.on('paymentMethodRequestable', function (event) {
  if (event.stored) {
    // change button to "Pay"
  } else {
    // change button to "Select Payment Method"
  }
});
```

**Comment by pootzko** [comment]
That would sort of be the end result, yes. It would be very helpful to have some piece of information on `paymentMethodRequestable` event that would indicate whether the `requestPaymentMethod()` has to be called again or not. 

What I personally think would be best is in case when the payment method is cached - pass that payment method object as an `event` property. Perhaps as `event.selectedPaymentMethod`. This would provide plenty of information and it would make the whole thing very flexible. If the clicked method has not been cached (someone clicks on a "pay with card" form), set `event.selectedPaymentMethod` as undefined. That sort of thing, I'm just throwing ideas around of what I believe would be most useful. For added clarity and explicitness perhaps also set `event.cached` or `event.stored` to true or false.

**Comment by pootzko** [comment]
Hi,

just a slight nudge. :) do you think you might be able to add this in the relative future (a month or two) or should I not count on it?

Thanks.

**Comment by quinnjn** [comment]
@pootzko we opened a PR (#223) that implements your suggestion. Take a look if you're able!
