### ISSUE TITLE
Braintree option changed event

### ISSUE THREAD

**Issue by pootzko** [braintree/braintree-web-drop-in#212]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.3.1/js/dropin.min.js
* Environment: Sandbox
* Browser and Chrome 59 (64-bit) on Win10

### Issue description

Hi,

I feel selecting a braintree option should also emit an event. I'm talking about these:
![image](https://user-images.githubusercontent.com/535842/27426884-f9e45fca-5734-11e7-91c7-a1a8804ce2df.png)

The only correct way to tie the drop-in into for example an AngularJS app is via events. Everything else means simply hacking your way around the limitations. And in my opinion the payment process shouldn't be a half-baked hacked up solution. It's great that the drop-in lib exists, but many apps nowadays are SPA's and these kind of events would be of great help.

Thanks!

**Comment by crookedneighbor** [comment]
That request seems reasonable. I've opened up a PR to add it: https://github.com/braintree/braintree-web-drop-in/pull/213
