### ISSUE TITLE
Error paypal dropin

### ISSUE THREAD

**Issue by BorisBresciani** [braintree/braintree-web-drop-in#216]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.3.1/js/dropin.min.js
* Environment: 'Sandbox'
 Browser and OS: Firefox 47.0

### Issue description

Screen: [http://i.imgur.com/ef244va.png](http://i.imgur.com/ef244va.png)

When I click on 'Pay' on the 'Paypal' button I have a popup that opens and then closes directly with the errors displayed on the screenshot.

Code:
`braintree.dropin.create({
 authorization: 'token'
       selector: '#dropin-container',
 paypal: {
    amount: 10.00,
    currency: 'EUR'
  }
     }, function (err, dropinInstance) {
       if (err) {
         // Handle any errors that might've occurred when creating Drop-in
         console.error(err);
         return;
       }
       submitButton.addEventListener('click', function () {
         dropinInstance.requestPaymentMethod(function (err, payload) {
           if (err) {
             // Handle errors in requesting payment method
           }
console.log(payload);
         });
       });
     });`

Thanks you !

**Comment by crookedneighbor** [comment]
For anyone looking at this in the future, the problem was that now `flow` property was included in the PayPal configuration.

**Comment by ciokan** [comment]
Where is that documented?

**Comment by crookedneighbor** [comment]
@ciokan If you're having issues, please open a ticket with our support team.  It's unlikely that it's an issue with the SDK itself.

https://developers.braintreepayments.com/forms/contact

**Comment by ciokan** [comment]
It was due to wrong Paypal sandbox account linked in braintree.

**Comment by ilnli** [comment]
> It was due to wrong Paypal sandbox account linked in braintree.

I'm hitting the same issue, although I have a Paypal sandbox account linked to the Braintree account, but it keeps giving me "No value passed to payment", could you please tell me what's different in your correct Paypal sandbox that's making it accept the payments now but wasn't before with the wrong account?
