### ISSUE TITLE
Error attempting to add PayPal payment to vault.

### ISSUE THREAD

**Issue by chris-die** [braintree/braintree-web-drop-in#217]
### General information

* 1.3.1
* Environment: Sandbox
* Chrome 59.0.3071.109 on Mac OS 10.10.5

### Issue description

I'm attempting to add PayPal payment methods to the Braintree vault via the Drop-In UI.

I've followed the steps to link my Braintree sandbox to my PayPal sandbox as outlined [here](https://developers.braintreepayments.com/guides/paypal/testing-go-live/php#linked-paypal-testing).

Included in the options I have for the Drop-In [`create`](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create) method is:

```
paypal: { flow: 'vault' }
```

The drop-in UI is rendering OK in my browser.

But when I click the `PayPal Checkout` button the PayPal pop-up window appears momentarily then closes itself. I then I have a error in my browser console that says `Error: Error: No value passed to payment`, and the drop-in UI displays a message around the `PayPal Checkout` button saying `Something went wrong on our end`.

If I change the the `create` options to use the `checkout` flow the PayPal pop-up window opens OK and I don't get the error. ie:

```
paypal: {
  flow: 'vault',
  amount: '10.00',
  currency: 'USD'
}
```
But (obviously) this is not what I want because I want to vault the PayPal payment method.

Using the Drop-In UI to add credit card payment methods to the vault works OK.

Could this be an issue with the linked Braintree and PayPal sandboxes?

The Braintree web console gives no indication that the details I've entered are actually correct (I think they are, but if I add total nonsense I receive no error back from the web console).

**Comment by luq10** [comment]
I have the same problem

**Comment by crookedneighbor** [comment]
Can you provide the client token you are using?

I've set the [demo app to use a client token encoded with a customer id and set the PayPal config to `{flow: 'vault'}`](https://braintree.github.io/braintree-web-drop-in/?paypalCredit=null&paypal={%22flow%22:%22vault%22}&authorization=eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiIyZmVlNTkyZjRlZTNjMmNmMDMxNjRlMDUwOTNmYThiNWVjZjM5NThiNTI4ZDhjYTgyOGMxMjkwMmM1MzQwMjNjfGNyZWF0ZWRfYXQ9MjAxNy0wNi0yNlQxMzo1MDo1NS42MTgwMDA5NzMrMDAwMCZjdXN0b21lcl9pZD02MDk0NzQ1NjQmbWVyY2hhbnRfaWQ9aGg0Y3BjMzl6cTRyZ2pjZyZwdWJsaWNfa2V5PXEzanRzcTNkM3Aycmg1dnQiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvaGg0Y3BjMzl6cTRyZ2pjZy9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbImN2diJdLCJlbnZpcm9ubWVudCI6InNhbmRib3giLCJjbGllbnRBcGlVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvaGg0Y3BjMzl6cTRyZ2pjZy9jbGllbnRfYXBpIiwiYXNzZXRzVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhdXRoVXJsIjoiaHR0cHM6Ly9hdXRoLnZlbm1vLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhbmFseXRpY3MiOnsidXJsIjoiaHR0cHM6Ly9jbGllbnQtYW5hbHl0aWNzLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb20vaGg0Y3BjMzl6cTRyZ2pjZyJ9LCJ0aHJlZURTZWN1cmVFbmFibGVkIjp0cnVlLCJwYXlwYWxFbmFibGVkIjp0cnVlLCJwYXlwYWwiOnsiZGlzcGxheU5hbWUiOiJidCIsImNsaWVudElkIjoiQVZRSmY5YS1iNmptWUZnaW9OcEkyaTU3cnNRa0hqUlpadjRkOURaTFRVMG5CU3Vma2h3QUNBWnhqMGxkdTg1amFzTTAyakZSUEthVElOQ04iLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjpmYWxzZSwiZW52aXJvbm1lbnQiOiJvZmZsaW5lIiwidW52ZXR0ZWRNZXJjaGFudCI6ZmFsc2UsImJyYWludHJlZUNsaWVudElkIjoibWFzdGVyY2xpZW50MyIsImJpbGxpbmdBZ3JlZW1lbnRzRW5hYmxlZCI6dHJ1ZSwibWVyY2hhbnRBY2NvdW50SWQiOiJjNXljdzJzdnlrbnp3anR6IiwiY3VycmVuY3lJc29Db2RlIjoiVVNEIn0sImNvaW5iYXNlRW5hYmxlZCI6ZmFsc2UsImJyYWludHJlZV9hcGkiOnsiYWNjZXNzX3Rva2VuIjoic2FuZGJveF82ZGR0bXdfcHpiNndwX3dkd2hjeV85aGc2bmJfY3k2IiwidXJsIjoiaHR0cHM6Ly9wYXltZW50cy5zYW5kYm94LmJyYWludHJlZS1hcGkuY29tIn0sIm1lcmNoYW50SWQiOiJoaDRjcGMzOXpxNHJnamNnIiwidmVubW8iOiJvZmYifQ==) and I have no issues vaulting a Sandbox PayPal account. Do you get the same error, or does the demo app work for you?

**Comment by chris-die** [comment]
Hi @crookedneighbor. Thanks for looking into this for me.

The demo app works OK for me.

Here's the client token I'm using:

`eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiI5ZTYwYTJmZjZmODVkMWIzNDVlOWMxYTA5N2RmNzZkNTE4YzJiNGFjNTIwYzQ2OTY5ZjBkZjY1Nzg4MzcwYzdkfGNyZWF0ZWRfYXQ9MjAxNy0wNi0yN1QyMTo1NjowNy4yNTk4OTYxMzErMDAwMFx1MDAyNmN1c3RvbWVyX2lkPTQ0MTA3XHUwMDI2bWVyY2hhbnRfYWNjb3VudF9pZD1zZXJhdG8tdXNcdTAwMjZtZXJjaGFudF9pZD1jbjdrZ2dxanFkcHhnNGhtXHUwMDI2cHVibGljX2tleT00aGNnMjk3eXdmcGdrbWhtIiwiY29uZmlnVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL2NuN2tnZ3FqcWRweGc0aG0vY2xpZW50X2FwaS92MS9jb25maWd1cmF0aW9uIiwiY2hhbGxlbmdlcyI6WyJjdnYiXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL2NuN2tnZ3FqcWRweGc0aG0vY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tL2NuN2tnZ3FqcWRweGc0aG0ifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6ZmFsc2UsInBheXBhbEVuYWJsZWQiOnRydWUsInBheXBhbCI6eyJkaXNwbGF5TmFtZSI6IlNlcmF0byIsImNsaWVudElkIjoiQWYyaXFUNGlKTlN3bGhEczhKNVFYWVdLNXdGai1fT2FiZEJrMHdCU0FWOHB4R2FtSE03VjZiaGNYbHVkNXZrWVFtWkF1VW5vRTlwUWhPZl8iLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjpmYWxzZSwiZW52aXJvbm1lbnQiOiJvZmZsaW5lIiwidW52ZXR0ZWRNZXJjaGFudCI6ZmFsc2UsImJyYWludHJlZUNsaWVudElkIjoibWFzdGVyY2xpZW50MyIsImJpbGxpbmdBZ3JlZW1lbnRzRW5hYmxlZCI6dHJ1ZSwibWVyY2hhbnRBY2NvdW50SWQiOiJzZXJhdG8tdXMiLCJjdXJyZW5jeUlzb0NvZGUiOiJVU0QifSwiY29pbmJhc2VFbmFibGVkIjpmYWxzZSwibWVyY2hhbnRJZCI6ImNuN2tnZ3FqcWRweGc0aG0iLCJ2ZW5tbyI6Im9mZiIsIm1lcmNoYW50QWNjb3VudElkIjoic2VyYXRvLXVzIn0=`

**Comment by chris-die** [comment]
Also:

I tried the Tokenization Key from the demo app in my own app and it worked OK.

I then tried generating my own [Tokenization Key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3) from the Braintree sandbox and using this is place of the [Client Token](https://developers.braintreepayments.com/guides/authorization/client-token). But the error returned.

So this suggests to me some kind of misconfiguration with my Braintree and/or PayPal sandbox.

**Comment by crookedneighbor** [comment]
@chris-die Looks like Reference Transactions weren't set up on your Sandbox PayPal account, so when opening the vault flow, setting up the Billing Agreement failed. It has now been enabled so it should work for you.

@luq10 I'll need your merchant ID (or client token) to diagnose your issue. Please [contact Braintree support](https://developers.braintreepayments.com/forms/contact) for assistance and reference this Github Issue.

**Comment by chris-die** [comment]
@crookedneighbor Bingo. That was indeed the issue. Thanks for your help.

**Comment by kaloraat** [comment]
@crookedneighbor 
Can you please share the source code/repo link of this demo app?

![Screen Shot 2019-03-31 at 10 31 41 AM](https://user-images.githubusercontent.com/15702617/55282813-3aed1700-53a0-11e9-9069-940c104a7317.png)

**Comment by crookedneighbor** [comment]
@kaloraat https://github.com/braintree/braintree-web-drop-in/blob/master/test/app/index.html
