### ISSUE TITLE
Broken icons in Firefox with Angular routing

### ISSUE THREAD

**Issue by thmsltmnn** [braintree/braintree-web-drop-in#224]
### General information

* SDK/Library version: 1.3.1
* Environment: Sandbox and Production
* Browser and OS: Firefox 54.0.1 (64-Bit) on Windows 10

### Issue description

Firefox has a problem displaying SVGs with `<use>` tags when there is a `<base href="/">` element present. This base tag is required in Angular applications for routing to work properly.

The easiest way to reproduce this issue is to use Firefox to open https://braintree.github.io/braintree-web-drop-in/ and use the dev tools to add `<base href="/">` to the HTML head. Using the teardown and create buttons, the issue can be observed because the icons are broken.

**Comment by crookedneighbor** [comment]
Looks like this is a bug in Firefox that will be [resolved officially in October](https://ricaud.me/blog/post/2017/04/On-the-utility-of-filing-bugs). We'll need to see if we can include a workaround until then.

**Comment by thmsltmnn** [comment]
Thank you for the proposed workaround.

Firefox Beta already fixes the mentioned issue, and should be released 2017-08-08 (see https://wiki.mozilla.org/RapidRelease/Calendar).

**Comment by crookedneighbor** [comment]
Since we're less than a month out for a fix from Firefox, we're going to refrain from including a fix within the SDK, but you can put this snippet in the callback of your `dropin.create` call and it should fix the issue for you:

```js
dropin.create({
  authorization: 'your-client-token-or-tokenization-key',
  container: '#your-container-id'
}, function (err, instance) {
  var pageUrl = window.location.href.replace(window.location.hash, ''); // page url without the hash
  var svgs = document.querySelectorAll('#your-container-id svg use');

  [].slice.call(svgs).forEach(function (svg) {
    svg.setAttribute('xlink:href', pageUrl + svg.getAttribute('xlink:href'));
  });

  // finish your setup
});
```

**Comment by thmsltmnn** [comment]
Thank you for the workaround. I will close the issue now, as it will resolve itself with Firefox 55.
