### ISSUE TITLE
"PayPal pending payments are not supported" error

### ISSUE THREAD

**Issue by msmol1** [braintree/braintree-web-drop-in#227]
### General information

* SDK/Library version: 
* Environment: Sandbox,MeteorJS
* Browser and OS : Chrome 59.0.3071.115 (64-bit) on Windows 8.1

Issue description

Hi, I am having problems with PayPal payment.
I am getting an error "PayPal pending payments are not supported".
My accounts seetings:
Braintree sandbox account: PL,
PayPal sandbox acocunt receiver: account: PL, main currency: €. 
PayPal sandbox account sender: account: DE, main currency: €
Money is send in €.

I though there might be some problems with allow/deny conditions in settings, but haven't found anything. 

Does anyone know whre can be the problem?

**Comment by crookedneighbor** [comment]
It's likely a misconfiguration with your PayPal account. Please [contact our support team](https://developers.braintreepayments.com/forms/contact) with your public merchant ID and the email of your business PayPal sandbox account.

You can include a link to this Github issue in your support request. 

I'm going to close this now, but if it ends up being a problem with the SDK after all, we can re-open it.
