### ISSUE TITLE
Placeholder text on Dropin form appears encoded incorrectly 

### ISSUE THREAD

**Issue by higgins777** [braintree/braintree-web-drop-in#228]
### General information

* SDK/Library version: 1.4.0
* Environment: Sandbox
* Browser and OS Tested across all standard up to date browsers in Windows 7 and Ubuntu 14.04

### Issue description

Greetings,

I am in the process of migrating from hosted fields to Dropin V3. The only issue I cannot seem to get resolved is the placeholder text appears to have an encoding issue. 

Note the placeholder below. It is a similar case on the CVV field.
```
<input type="tel" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" class="number" data-braintree-name="number" name="credit-card-number" id="credit-card-number" maxlength="22" placeholder="â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢ â€¢â€¢â€¢â€¢" aria-invalid="true">
```

Please let me know if I can provide any other app specific details that might be helpful.
Coffeescript:
```
  braintree.dropin.create {
    authorization: gon.client_token
    container: '#dropin-container'
    locale: 'en_US'
  }, (createErr, instance) ->
    form.addEventListener 'submit', (event) ->
      event.preventDefault()
      instance.requestPaymentMethod (err, payload) ->
        if err
          console.log 'Error', err
          return
        # Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce
        form.submit()
        return
      return
    return
```

**Comment by lilaconlee** [comment]
This can be fixed by including the `<meta charset="UTF-8">` tag in your `<head>`. If you rather use your own placeholder that doesn't require utf-8, you can use the `card` overrides in your create options which is shown in an example [in our reference documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create).

**Comment by higgins777** [comment]
My head tag already includes that (cleaned up a bit to only show meta tags)

```
<head>
    <meta charset='UTF-8' content='width=device-width, initial-scale=1.0' name='viewport'>
    <meta name="csrf-param" content="authenticity_token" />
    <meta name="csrf-token" content="?" />
</head>
```

Per your suggestion I'll mess around there a bit more and try the card overrides. 

Thanks!

**Comment by higgins777** [comment]
Trying to mess with size/syntax of my head didn't resolve the issue. The card overrides did the job though.

Thank you for the fast response and help.

**Comment by crookedneighbor** [comment]
We added some code to detect the encoding on the site and fallback to a `*` if utf-8 is not supported. This was released in v1.10.0

**Comment by maticb** [comment]
I also have UTF-8 set as charset in head, but getting the same error:
https://i.gyazo.com/d1d82dc2957104f3fbbecfecbb019d60.png

**Comment by crookedneighbor** [comment]
@maticb What version of the sdk are you using?

**Comment by maticb** [comment]
The one from the documentation links:  https://js.braintreegateway.com/web/dropin/1.11.0/js/dropin.min.js

Although I copied it and saved it locally on my server. But it does the same if I use the web link (thought it could be the .js file being saved in a wrong encoding because I have it locally)

**Comment by crookedneighbor** [comment]
v1.11.0 should have a workaround to detect the improper encoding and substitute `*` for it. Can you share a site that exhibits the behavior so I can troubleshoot it?

**Comment by maticb** [comment]
Sadly, the payment method isn't live yet. I can give you the site link though: 
https://jessyss.com/

**Comment by crookedneighbor** [comment]
I injected the script and added it to your site using Chrome dev tools.

![screen shot 2018-07-23 at 11 00 23 am](https://user-images.githubusercontent.com/2916945/43088421-b56b0216-8e67-11e8-9583-b6ea14791956.png)

Can you give more information about how to reproduce it?

**Comment by maticb** [comment]
I'm not sure, I did the same (inject on live site): https://i.gyazo.com/332b1162926558b5f9286b7f1ba13520.png

Tested on firefox too (locally, where I have the payment method implemented).

I will have to do more research and get back to you. Could it be something with the settings on my sandbox account?

**Comment by maticb** [comment]
This is what I see in the code, in the dropin.js on the same link I gave above:

https://i.gyazo.com/96b71f040239352dfdeb65362c12524d.png

If I download the file locally, and replace the string by copy&paste from here: https://www.compart.com/en/unicode/U+2022

Everything works fine. Will use this as a temporary workaround.

Also, is this normal, basically everything here is completely broken:
https://i.gyazo.com/e825fdb07eac9c65f51757946f575732.png

https://i.gyazo.com/a3f7da139854338c8f08a7ca09b30808.png

**Comment by crookedneighbor** [comment]
Looks to me like your system is changing the locally downloaded files and converting them to something that is not utf-8. 

If I copy and paste the icon in my downloaded version, git does not see a difference between the two.

You said the same thing is occurring when using the hosted version?

**Comment by maticb** [comment]
Yes, the screenshot is from the actual link (https://js.braintreegateway.com/web/dropin/1.11.0/js/dropin.js)

**Comment by krio** [comment]
I had the same problem when I manually copied the dropin.min.js file and pasted it locally. Calling straight from the cdn or downloading it and saving has fixed the issue originally described for me.

`<script src="https://js.braintreegateway.com/web/dropin/1.11.0/js/dropin.min.js"></script>`

**Comment by crookedneighbor** [comment]
Going to close this, because I think the problem seems to be from the source computer copying the encoding incorrectly. When used from the CDN with the correct character set encoding, it should not display incorrectly.
