### ISSUE TITLE
Number keypad on mobile does not hide on form submit

### ISSUE THREAD

**Issue by danieljodeci** [braintree/braintree-web-drop-in#229]
I am having an issue on mobile devices where the number keypad is not hiding after initiating the requestPaymentMethod request on the click event. I'm using the example for v3.

**Comment by crookedneighbor** [comment]
@danieljodeci Can you provide specific devices where this is occurring so we can reproduce the behavior?

**Comment by crookedneighbor** [comment]
Was able to reproduce this with an iOS device. Working on a fix. Thanks for the report!

**Comment by danieljodeci** [comment]
Hey! Sorry for the delay, but yes I was experiencing this issue on an iPhone 6. Thanks for the quick response!

**Comment by crookedneighbor** [comment]
This will be fixed in the next release.

**Comment by crookedneighbor** [comment]
This is now fixed in v1.5.0
