### ISSUE TITLE
Create a dist folder with dropin.js and dropin.min.js for Npm

### ISSUE THREAD

**Issue by judowalker** [braintree/braintree-web-drop-in#233]
Please create a dist folder with dropin.js and dropin.min.js.

**Comment by crookedneighbor** [comment]
We intentionally decided to not do this to keep the package size small on npm. Is there a reason you can't include browserify or another build tool and build it yourself as part of your build script?

**Comment by judowalker** [comment]
I simply don't use a build script.

**Comment by crookedneighbor** [comment]
Same answer here as https://github.com/braintree/braintree-web/issues/309

Here's a script for fetching the latest dropin built files.

```js
'use strict';

var exec = require('child_process').exec;
var fs = require('fs');
// put the path to your public assets here
var pathToPublicAssets = '/absolute/path/to/public/assets/';

// get latest version of braintree-web
exec('npm view braintree-web-drop-in version', function (err, version) {
  // remove new line character and white space so we have just the version number
  version = version.replace(/\s/g, '');

  // grab the latest version from the braintree cdn
  exec('curl https://js.braintreegateway.com/web/dropin/' + version + '/js/dropin.min.js', function (err, code) {

    // write the file to your public assets folder
    fs.writeFile(pathToPublicAssets + 'dropin.min.js', code, function () {
      console.log('Copied braintree-web-dropin version', version + '.');
    });
  });
});
```

**Comment by lightswitch05** [comment]
This would be very useful to other projects. At the cost of 186kb it would save significant time for setup and rebuilding. I'm not sure who would complain about 186kb, especially if they can speed up the build process which is ran much more often then a single download

**Comment by crookedneighbor** [comment]
This has been added as part of 1.12.0. The path to find it is on the browser tag in the package.json, `dist/browser/dropin.js`

**Comment by lightswitch05** [comment]
@crookedneighbor Thanks for this update. Unfortunately I'm not seeing it in the package. Here is a screenshot showing 1.12.0 package without a `dist` folder

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/598803/43935835-47cbabfc-9c45-11e8-99d1-7ec2c7afc099.png">

**Comment by crookedneighbor** [comment]
Hmmm... very strange. We'll look into this for the next release.

**Comment by crookedneighbor** [comment]
Figured it at. The .gitignore got added, which includes `dist`. This will be fixed in the next release.

**Comment by crookedneighbor** [comment]
Fixed in, https://github.com/braintree/braintree-web-drop-in/commit/5ff0583747e9946e5d8746c80c8682ef578b9d1c, will update here when it is released.

**Comment by jamesdixon** [comment]
@crookedneighbor any idea when this will be released?

**Comment by crookedneighbor** [comment]
Probably next week.

**Comment by crookedneighbor** [comment]
This is out in v1.13.0

**Comment by lightswitch05** [comment]
@crookedneighbor thank you again for providing this build, its going to be a great help to https://github.com/bitwarden/web

By any chance, especially since this is a build, could it be updated to be a min version?

**Comment by kspearrin** [comment]
A pre-minified version would definitely be helpful.

**Comment by crookedneighbor** [comment]
If you're grabbing the build from npm, shouldn't your own tool chain minify it along with the rest of your files? Not sure what the use case of providing a minified file would be when anyone using it should already be minifying it as part of their own JS build.

I've seen in the past where a minified file was minified a second time and it corrupted the file so it could not be used. So, I'm hesitant to have the built version be minified.

**Comment by kspearrin** [comment]
@crookedneighbor While our use case may not be the norm, we are just copying the dist folder during build time and then using the file directly in the page's html: `<script src="/scripts/dropin.js"></script>`. There isn't a step in the build for minifying.

**Comment by lightswitch05** [comment]
@crookedneighbor if you want to see how its being used, here is the pull request that started using the pre-built version instead of the js.braintreegateway.com version: https://github.com/bitwarden/web/pull/259

This is a password manager, and so not pulling in javascript from 3rd party hosts is the goal of the change. Also as added security, it doesn't load this javascript unless its needed, so having it being bundled in with the reset of `vendor.js` would also be undesirable

**Comment by crookedneighbor** [comment]
Thanks for the feedback. We don't have any plans to add minified file at this time, but we'll consider it for the future.

FYI, even though you'd vendor this particular script tag into your app, the SDK would still use the CDN to load css files, iframes for the credit card fields, as well as third party scripts (PayPal, Google Pay, etc), so it's not gonna be possible to fully eliminate calls to outside CDNs from your integration.
