### ISSUE TITLE
Brain tree

### ISSUE THREAD

**Issue by Button0501** [braintree/braintree-web-drop-in#246]
### General information

* SDK/Library version: 
* Environment: 
* Browser and OS

**Comment by crookedneighbor** [comment]
I assume this was an unintentional issue you opened. Closing.

**Comment by Button0501** [comment]
Open

**Comment by crookedneighbor** [comment]
There is no information here about what issue you are having with the SDK. Please comment with your issue and I will gladly re-open the issue.
