### ISSUE TITLE
Data collector Support

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#254]
Data collector will be supported ?

**Comment by crookedneighbor** [comment]
This will be supported in the next release. https://github.com/braintree/braintree-web-drop-in/pull/252

**Comment by MixMe** [comment]
When you plan to release an update ?

**Comment by crookedneighbor** [comment]
Should be some time this week. We'll close this issue when it is out.

**Comment by MixMe** [comment]
okey, thx ;)

**Comment by crookedneighbor** [comment]
Data collector was added in version 1.7.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#170
