### ISSUE TITLE
Apple Pay Support

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#256]
Apple Pay will be supported ?

**Comment by crookedneighbor** [comment]
It is on our roadmap to support Apple Pay, but we don't have a definite timeline for when it will be added.

**Comment by YamileAndrada** [comment]
Hi guys!
I had a problem which also happens in the demo https://braintree.github.io/braintree-web-drop-in/
1 - I choose pay with paypal
2- I sign in with may paypal sandbox account and I close the  paypal popup
3- I click on  chosee another way to pay
4-  I choose again pay with paypal
5-  click on pay and  it remembers my previous login, 
6- when I cllick on "Not you?" link 
Then an error is displayed
"Something went wrong on our end."
and I cant login with other paypal account

**Comment by crookedneighbor** [comment]
@YamileAndrada This is unrelated to this particular issue. I've opened a new issue here to track it: https://github.com/braintree/braintree-web-drop-in/issues/259

**Comment by dadrcheng** [comment]
I love the new dropin UI but it's lacking Apple Pay.  Any chance it might be released before holiday sales season?

**Comment by crookedneighbor** [comment]
@dadrcheng We're working on it this week. Hoping to get it out to y'all soon!

**Comment by crookedneighbor** [comment]
Support for Apple Pay added in 1.9.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#changelog

Documentation on the Braintree docs site is forthcoming.
