### ISSUE TITLE
Clicking "Not You?" in PayPal flow causes an error

### ISSUE THREAD

**Issue by crookedneighbor** [braintree/braintree-web-drop-in#259]
### General information

* SDK/Library version: 1.6.0
* Environment: Sandbox
* Browser and OS: Mac Chrome

### Issue description

Originally Reported here by @YamileAndrada: https://github.com/braintree/braintree-web-drop-in/issues/256#issuecomment-322189892

> Hi guys!
I had a problem which also happens in the demo https://braintree.github.io/braintree-web-drop-in/
1 - I choose pay with paypal
2- I sign in with may paypal sandbox account and I close the paypal popup
3- I click on chosee another way to pay
4- I choose again pay with paypal
5- click on pay and it remembers my previous login,
6- when I cllick on "Not you?" link
Then an error is displayed
"Something went wrong on our end."
and I cant login with other paypal account

Was able to reproduce. Probably just need to update the version of checkout.js we are using.

**Comment by crookedneighbor** [comment]
@YamileAndrada got a PR to fix it with https://github.com/braintree/braintree-web-drop-in/pull/260

**Comment by YamileAndrada** [comment]
Thanks ! :)

**Comment by crookedneighbor** [comment]
This will be out in the next release.

**Comment by YamileAndrada** [comment]
Great! 
Also I want to know in drop in ui if exists some way to avoid displays duplicated PayPal accounts (using vault flow), preferently by customer

**Comment by crookedneighbor** [comment]
Not on the client. 

You can prune the duplicates on the server side. The customer object has a property for [PayPal accounts](https://developers.braintreepayments.com/reference/response/paypal-account/php) associated with that customer. You can iterate through them and delete any that are duplicates.

**Comment by YamileAndrada** [comment]
Perfect regards!
