### ISSUE TITLE
ISO-8859-1 not working

### ISSUE THREAD

**Issue by loopion** [braintree/braintree-web-drop-in#263]
### General information

* SDK/Library version: Braintree Web Drop In 1.6.0
* Environment: Sandbox
* Browser and OS : Chrome 59 (64-bit) on Windows 7 -->

### Issue description

Tried to set ISO-8859-1 as charset and it doesn't look right.

![iso-8859-1_dropinui_error](https://user-images.githubusercontent.com/4337/29417537-c7c2a70c-8369-11e7-9c97-91ef1343a818.png)

**Comment by crookedneighbor** [comment]
The translations as is require UTF8 encoding. However, you can supply your own translations if your site must use IS-8859-1 encoding:

https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create

```
braintree.dropin.create({
  authorization: YOUR_AUTHORIZATION,
  locale: 'fr_FR',
  translations: {
    cardNumberLabel: 'Your custom card number label',
    endingIn: 'Your custom ending in translations {{lastTwoCardDigits}}',
    // any other translations to modify
  }
```

You can see the full list of translation strings here: https://github.com/braintree/braintree-web-drop-in/blob/e08a6f5c0e9ff1e9fbd3574a0a6fb263c8708cde/src/translations/fr_FR.js

Likely any with accent marks or other utf8 characters will need to be changed to use IS-8859-1 encoding on your site.

**Comment by crookedneighbor** [comment]
Just realized that the number placeholder is not part of the translations object, so you'll need to override the placeholder property in the create call:

```js
braintree.dropin.create({
  card: {
    overrides: {
      fields: {
        number: {
          placeholder: 'your placeholder'
        }
      }
    }
  },
  // other config properties
```
