### ISSUE TITLE
Changing the text color within the dropin-container

### ISSUE THREAD

**Issue by vijay559** [braintree/braintree-web-drop-in#278]
### General information
<img width="609" alt="screen shot 2017-09-08 at 5 49 54 pm" src="https://user-images.githubusercontent.com/7060822/30235534-2ec29632-94be-11e7-83ca-4e4edd8ed50a.png">

In the attached image, I am unable to change the color of the text from black to white(Paying with Card and Other ways to pay). After reading through the documentation, I didn't find any way to do this. Can you please suggest me how to do this. 

* SDK/Library version: Javascript V2
* Environment: Sandbox
* Browser and OS : Chrome.

### Issue description
Thanks to the dropin-Container, but I am very limited with the customization of text. Please see the attached screenshot.
<div id="dropin-container"></div>

**Comment by crookedneighbor** [comment]
You can target the `[data-braintree-id]` properties to adjust the CSS. Here's a codepen example: https://codepen.io/braintree/pen/c677ef8c03057533126111d6fac3ece4
