### ISSUE TITLE
No text shown on the PayPal button when using Firefox

### ISSUE THREAD

**Issue by ShaunDychko** [braintree/braintree-web-drop-in#279]
### General information

* SDK/Library version: 1.7.0
* Environment: Sandbox
* Browser and OS Firefox 55.0.3 (64-bit) on macOS Sierra 10.12.6 (16G29), as well as Firefox on Android mobile.

### Issue description

When selecting "PayPal" from the Drop-in UI, there is an empty yellow oval shown with no text. Screenshot is attached, along with a screenshot of the Firefox debug console error messages. This is specific to using Firefox. Chome works fine.

<img width="1511" alt="braintree-paypal-icon-console-debug" src="https://user-images.githubusercontent.com/235214/30243996-7964d7b6-956a-11e7-8be9-842f7c27eddc.png">
<img width="1048" alt="braintree-paypal-icon-error" src="https://user-images.githubusercontent.com/235214/30243997-796849fa-956a-11e7-98ef-d72f85a9083b.png">

**Comment by crookedneighbor** [comment]
This is a known issue with the version of checkout.js that is used by the current version of Drop-in. It will be fixed in the next release.

**Comment by crookedneighbor** [comment]
This was fixed on the checkout.js side and _should_ be fixed in v1.7.0 automatically. I checked with v55.0.3 of Firefox and confirmed that button renders normally now.

Let us know if that is not the case for you.

**Comment by ShaunDychko** [comment]
It looks great, thank you!
