### ISSUE TITLE
Which version of the client token is needed for the Drop-in UI?

### ISSUE THREAD

**Issue by ShaunDychko** [braintree/braintree-web-drop-in#280]
### General information

* SDK/Library version: Drop-in 1.7.0
* Environment: sandbox
* Browser and OS: Firefox

### Issue description

Could you please confirm which version should be used for generating a client token for use in the Drop-in UI? Is it version 3?

The [documentation for PHP](https://developers.braintreepayments.com/reference/request/client-token/generate/php#version) says, with regards to the version:

> Please check your client-side SDKs in use before changing this value.

The default version is 2, but the Drop-in UI seems to work with either 2 or 3. I'm assuming the Drop-in UI works best with version 3 only because it's documented [here](https://developers.braintreepayments.com/start/hello-client/javascript/v3) where it says "JS v3 SDK". However, the example code in [Braintree's PHP example](https://github.com/braintree/braintree_php_example/blob/master/public_html/index.php) shows
`var client_token = "<?php echo(Braintree\ClientToken::generate()); ?>";`, in which case the default version 2 client token is being given to the Drop-in UI. So, either

1. Version 2 and 3 work equally well and the difference doesn't matter
2. Version 3 is better, and the example at https://github.com/braintree/braintree_php_example/blob/master/public_html/index.php should be updated to read `var client_token = "<?php echo(Braintree\ClientToken::generate(['version' => 3])); ?>";`

**Comment by ShaunDychko** [comment]
A further question on this, it would seem that reading the "JS v3 SDK" does not necessarily imply the version to use for generating the client token since there exists an "iOS v4" client side SDK, but "4" is not an allowed value for the version. Where is the definitive place to find the version needed by the client side SDK?

**Comment by ShaunDychko** [comment]
Does the answer lie in the `braintree-web` major version in [package.json](https://github.com/braintree/braintree-web-drop-in/blob/master/package.json)? It would be "3"?

```
"dependencies": {
    "braintree-web": "3.22.2",
    "@braintree/browser-detection": "1.6.0",
    "promise-polyfill": "6.0.2",
    "@braintree/wrap-promise": "1.1.1"
  },
```

**Comment by kzurawel** [comment]
Drop-in 1.7.0 uses the JavaScript v3 SDK. JavaScript v3 can use either v2 or v3 client tokens. v3 client tokens are smaller than v2 client tokens, so we recommend setting your client token version to `3`, but either will work. 

We will update the docs to make this more clear. Thanks!
