### ISSUE TITLE
Payment via paypall reloads browser on Edge

### ISSUE THREAD

**Issue by slawus** [braintree/braintree-web-drop-in#281]
### General information

* SDK/Library version: Latest (1.7.0)
* Environment: Sandbox, didn't test on production
* Browser and OS Microsoft Edge 40.15063.0.0 on Windows 10 
### Issue description

Hi,

Me and my team discovered that there is a problem with UI on Edge, wchich occures only on some computers. After successfull sign on to paypal account, both main browser window and paypal 'popup' fully reloads, which break payment flow. On some computers tho, instead of reloading the popup is redirected to example.com domain.

Error exists both in our implementation, and example from braintree guide: https://developers.braintreepayments.com/guides/drop-in/overview/javascript/v3

We can't determine why it works on some computers, and breaks on other. The only thing that we figured out, is that the "browser reloading problem" occures, if user has already paid with credit card (so it appears on list of available cards when attempting to pay), a and then try to pay with 
his paypal account. Steps to reproduce this story:

1. Go to https://developers.braintreepayments.com/guides/drop-in/overview/javascript/v3
2. Go to demo
3. Click "Card" in "Choose a way to pay" step
4. Fill card number (use example one: 4111 1111 1111 1111), expiration date and CVV
5. Click purchase, card will become successfully validated.
6. [Popup] Click "Choose another way to pay" -> PayPal -> "PayPal Checkout" button
7. [Popup] Paypal popup window appears ->  fill data with your sandbox account -> click "Log in"
8. [Popup] After successful log in, accept method of payment.
9. Both main browsr window and popup should get redirected

**Comment by bluepnume** [comment]
See https://github.com/paypal/paypal-checkout/issues/384

Working theory is that this should be resolved when drop-in updates to use the latest checkout.js release.

@slawus if you wouldn't mind confirming this is true for you, could you please try the flow at https://developer.paypal.com/demo/checkout/ in Edge (which has the latest checkout.js), and let me know if you still see the issue? Thanks so much!

**Comment by slawus** [comment]
Thank you for quick response!

I've been trying to reproduce bug on https://developer.paypal.com/demo/checkout/ with no luck. However, I know that bug is very hard to reproduce, as it appears only on some PCs. Before we assume that latest version works, I believe it would me more convenient to first reproduce the error on previous version of checkout.js itself. Unfortunately, I can't find same "demo" for previous versions :/ 

@bluepnume Do you know the ETA for new version of the drop-in, with updated paypal library?

**Comment by crookedneighbor** [comment]
Hoping to get it today. Stay tuned!

**Comment by crookedneighbor** [comment]
v1.8.0 is out now. I'm going to close this because I'm fairly certain it should be fixed now, but feel free to comment here if you're still having issues.

**Comment by dpolivy** [comment]
@crookedneighbor We're using drop-in 1.10.1 and just had a user report this redirect issue while trying to make a payment via PayPal. Browser was Edge 16.

**Comment by crookedneighbor** [comment]
@dpolivy If you're having this issue, it's a checkout.js bug. Drop-in now pulls in the latest version of checkout.js when it loads, so please open a new issue on https://github.com/paypal/paypal-checkout or comment on https://github.com/paypal/paypal-checkout/issues/384 where it was reported initially.
