### ISSUE TITLE
missing validations on cardholderName

### ISSUE THREAD

**Issue by YamileAndrada** [braintree/braintree-web-drop-in#283]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.8.0/js/dropin.min.js
* Environment: Sandbox
* Browser: chrome, mozilla,etc

### Issue description
missing validations on  cardholder name field
- I entered cards with names of 100 characters, I think that maximum will be 32, I'm not sure
- also I was able to save cards with special characters like 
#"$#"$#&%"$54w6$%(#('574738907

**Comment by crookedneighbor** [comment]
The max character limit in the Braintree gateway is 255 characters for cardholder name. We should update the client side validations to account for that.

Characters such as `#"$#"$#&%"$54w6$%(#('574738907` are valid in the Braintree gateway. So they should be allowed via client side validation.

**Comment by YamileAndrada** [comment]
Great! thanks for the information. I'll keep an eye for the client update with the restriction
Regards.

**Comment by crookedneighbor** [comment]
Fixed in 1.9.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#changelog
