### ISSUE TITLE
Dropin UI stuck with perpetual spinner, initialization callback not called when iframe is within web component.

### ISSUE THREAD

**Issue by ernsheong** [braintree/braintree-web-drop-in#297]
### General information

* SDK/Library version: 1.8.0
* Environment: Sandbox
* Browser and OS: Chrome 61 on macOS

### Issue description

Iframe code:
```html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
</head>

<body>
  <div id="dropin-container"></div>
  <button id="submit-button">Purchase</button>

  <script src="https://js.braintreegateway.com/web/dropin/1.8.0/js/dropin.min.js"></script>
  <script>
    const button = document.querySelector("#submit-button");

    window.addEventListener("message", function(e) {
      if (e.origin !== window.origin) {
        console.warn("Message received from unexpected origin");
        return;
      }

      if (e.data) {
        if (e.data.name === "TOKEN") {
          const token = e.data.data;
          console.log("Received token", token);

          braintree.dropin.create({
            authorization: token,
            container: "#dropin-container",
          }, function(createErr, instance) {
            // NOT CALLED
            console.log("Init callback");
            if (createErr) {
              console.error(createErr);
              return;
            }

            console.log("Braintree init success.");
            button.addEventListener("click", function() {
              instance.requestPaymentMethod(function(requestPaymentMethodErr, payload) {
                // Submit payload.nonce to your server
              });
            });
          });
        }
      }
    });
  </script>
</body>

</html>

```

Result:

![image](https://user-images.githubusercontent.com/1343284/31598016-fffad818-b27d-11e7-88eb-1923881e1462.png)

The initialization callback is never called. There is no error in the console despite error handling code.

I am trying to workaround the issue caused by https://github.com/braintree/braintree-web-drop-in/issues/296, i.e. this iframe is being loaded from within a web component with shadow DOM encapsulation. But the DropIn code runs entirely within the iframe. What went wrong?

**Comment by ernsheong** [comment]
**Update**

I have tried to place the iframe within the root `document` instead of within the shadow DOM, and the code works as expected. Oddly, the iframe cannot work when loaded within a shadow DOM.

**Comment by ernsheong** [comment]
Looks like hosted field load timed out:

```js
{
   "analytics":[
      {
         "kind":"web.custom.hosted-fields.load.timed-out",
         "timestamp":1508136514
      }
   ],
   "braintreeLibraryVersion":"braintree/web/3.22.2",
   "_meta":{
      "merchantAppId":"...",
      "platform":"web",
      "sdkVersion":"3.22.2",
      "source":"client",
      "integration":"dropin2",
      "integrationType":"dropin2",
      "sessionId":"215651fd-5359-4aec-9bc7-364bfe4ed4cc",
      "dropinVersion":"1.8.0"
   },
   "authorizationFingerprint":"..."
}

```

**Comment by crookedneighbor** [comment]
This is going to be related to this issue: https://github.com/braintree/braintree-web/issues/226

**Comment by crookedneighbor** [comment]
This is likely going to be the same issue I elaborated on in https://github.com/braintree/braintree-web-drop-in/issues/296 where the Hosted Fields iframes cannot find their siblings. Since there's so much overlap between this issue and the original posted issue, I'm going to close this one.
