### ISSUE TITLE
Pasting CC# on iOS 11 doesn't work

### ISSUE THREAD

**Issue by dpolivy** [braintree/braintree-web-drop-in#299]
### General information

* SDK/Library version: 1.8.0
* Environment: Production
* Browser and OS: Safari 11 on iOS 11

### Issue description

1. Open a page with the drop-in UI, select Card as the payment type.
2. Copy the following number: 0123456789012345
3. Paste it into the credit card field.

*EXPECTED*
The full number should be pasted into the credit card field.

*ACTUAL*
The number pastes as:
`0123 5678 0123 5`

**Comment by crookedneighbor** [comment]
Thanks for the report. This is a bug in our restricted input library. I've opened a fix for it here: https://github.com/braintree/restricted-input/pull/46

Once it's merged in, we can update the library in braintree-web, and then when that version of braintree-web is released, we can update braintree-web in drop-in.

**Comment by shaunbaker04** [comment]
Can this braintree drop-in UI be used with PayPal for Marketplaces API's ? I don't know where else to ask? Thanks in advance.

**Comment by crookedneighbor** [comment]
@shaunbaker04 Please contact PayPal Marketplace support.

**Comment by crookedneighbor** [comment]
Fixed in 1.9.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#changelog
