### ISSUE TITLE
How do you test the drop in UI with Cucumber?

### ISSUE THREAD

**Issue by zedtux** [braintree/braintree-web-drop-in#301]
I'm using the [Braintree gem](https://github.com/braintree/braintree_ruby) with the drop in UI in my Rails project and I'm writting my Cucumber test but I'm not able to get the form and register my payment method.

I first try using [webmock](https://github.com/bblimke/webmock) + [vcr](https://github.com/vcr/vcr) but as it is a JavaScript library, and I'm using poltergeist to run the JavaScript code in my tests, I needed something else to record/replay requests to Braintreen.

I found [puffing-billy](https://github.com/oesmith/puffing-billy) which is doing the job for all the URLs so far, excepted for the URL:

```
https://client-analytics.sandbox.braintreegateway.com:443/xxxxxxxxxxxxxx?sharedCustomerIdentifierType=undefined&braintreeLibraryVersion=braintree%2Fweb%2F2.15.7&authorizationFingerprint=90845d21632c5072826562208550f6504a0ce8b114205d5e0250d5e7628a6e79%7Ccreated_at%3D2017-10-24T12%3A35%3A51.110601708%2B0000%26customer_id%3Dxxxxxxxxxxxx%26merchant_id%3xxxxxxxxxxxxxxxxxx%26public_key%3Dxxxxxxxxxxxxxxxxx&analytics%5B%5D%5Bkind%5D=dropin.web.initialized&_meta%5BmerchantAppId%5D=127.0.0.1%3A34467&_meta%5Bplatform%5D=web&_meta%5BplatformVersion%5D=Mozilla%2F5.0%20(Unknown%3B%20Linux%20x86_64)%20AppleWebKit%2F538.1%20(KHTML%2C%20like%20Gecko)%20PhantomJS%2F2.1.1%20Safari%2F538.1&_meta%5BintegrationType%5D=dropin&_meta%5BsdkVersion%5D=braintree%2Fweb%2F2.15.7&_method=POST&callback=callback_json7712bcc67f774cc6aa03bdb14632788d
```

This one is ending on `Errno::ETIMEDOUT`.

Then [capybara-screenshot](https://github.com/mattheworiordan/capybara-screenshot) is not creating any screenshot of my page with the warning:

```
WARN: Screenshot could not be saved. `page.current_path` is empty.
```
**Edit:** Regarding the screenshot thing, I found out that `page.current_url` returns `about:blank` ... This is strange.

So do you know how the drop in UI can be tested using Cucumber?

**Comment by crookedneighbor** [comment]
This question is better suited for our support team. Please [contact our support team](https://developers.braintreepayments.com/forms/contact) and reference this issue. 

It would be helpful for them if you could create a simple Github repo with rails, drop-in and cucumber set up that reproduces the issue you are seeing.

**Comment by zedtux** [comment]
Thank you @crookedneighbor for your comment.

> It would be helpful for them if you could create a simple Github repo with rails, drop-in and cucumber set up that reproduces the issue you are seeing.

I'm on it since 2 days. I think I'm close to the solution ...
