### ISSUE TITLE
Misleading UI

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#305]
When our customers introduce their Paypal accounts as a payment method - they see a green checkbox next to it and many of them think that the payment was already submitted. Can you remove this green checkbox or add a text that will explain the that this green checkbox means only that a 
![screen shot 2017-10-27 at 11](https://user-images.githubusercontent.com/3535911/32094169-86d2cb02-bb07-11e7-839a-2689be687756.png)
particular payment method was selected.

**Comment by lilaconlee** [comment]
Thanks for the feedback! We'll pass it on to our designers, but we're unlikely to change the design too significantly until we do another major version.

If you're interested in changing this design for yourself, you can include some CSS on your page like in [this codepen](https://codepen.io/lilaconlee/pen/OOLYGa). If you use custom CSS, we recommend you double check that everything still looks as you expect when you upgrade your version.

**Comment by crookedneighbor** [comment]
You can also utilize the events API to automatically request the payment method nonce when paypal authorization completes.

https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on

See the `Automatically submit nonce to server as soon as it becomes available` example in the above linke.
