### ISSUE TITLE
Unable to style space between containers (see image)

### ISSUE THREAD

**Issue by ernsheong** [braintree/braintree-web-drop-in#313]
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* Browser and OS: Chrome 62, macOS Sierra

### Issue description

Hi there, sorry it's me again :/ 👋 😔

I tried a lot of things, but I can't seem to style the background in between the red zones as in the picture (it remains stubbornly white): 
![image](https://user-images.githubusercontent.com/1343284/32336085-4ca44f42-c029-11e7-8701-b22e5f09120f.png)

I've tried most options:
![image](https://user-images.githubusercontent.com/1343284/32336134-6e7de7c2-c029-11e7-85ec-1e347c0b683e.png)

**Comment by ernsheong** [comment]
Ah I found it, have to style `.braintree-loaded .braintree-upper-container:before`. Sorry about that.

**Comment by crookedneighbor** [comment]
That's great. 

Just a reminder, if you are making changes to the CSS you should always verify that your changes are compatible with new versions of Drop-in before deploying it to your production site, just to make sure there aren't any unexpected visual changes.
