### ISSUE TITLE
Venmo Support

### ISSUE THREAD

**Issue by depombo** [braintree/braintree-web-drop-in#315]
Will Venmo be supported ?

**Comment by crookedneighbor** [comment]
It's not on the road map at this time.

We'll leave this open so other people can chime in if there is interest in including it.

**Comment by jpemberthy** [comment]
+1 interested on Venmo support 🚀

**Comment by gascanio2010** [comment]
I am interested on Venmo support as well!

**Comment by djjames** [comment]
I want itb

**Comment by danielcavero1** [comment]
+1

**Comment by depombo** [comment]
@crookedneighbor have you guys added it to the roadmap?

**Comment by KamilaD** [comment]
Hi @crookedneighbor, I would also be interested

**Comment by crookedneighbor** [comment]
This has been added to the roadmap. We'll comment here when it's ready.

**Comment by crookedneighbor** [comment]
Venmo support has been released with version 1.10.0

Client SDK Docs: https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~venmoCreateOptions

Docs on https://developers.braintreepayments.com should be up next week
