### ISSUE TITLE
CardholderName required: true

### ISSUE THREAD

**Issue by sidonaldson** [braintree/braintree-web-drop-in#318]
### General information

* SDK/Library version: 1.8.1
* Environment: Sandbox
* Browser and OS: Mac - Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Issue description

If I create a drop-in and turn on `cardholderName` and set it to `required` like so:
```
card: {
	cardholderName: {
		required: true
        }
}
```
The form field shows up correctly. Validation works if you tab into the field and tab away without typing. 
The issue is that if you submit the form immediately all the other fields fail validation and show the red warning, except the cardholder name. See image.

![image](https://user-images.githubusercontent.com/236669/32781040-6d2a40d0-c93b-11e7-8a6d-15b3446817c2.png)

If this is intentional please close, otherwise hope this helps. :)

**Comment by crookedneighbor** [comment]
Fixed in 1.9.0 https://github.com/braintree/braintree-web-drop-in/blob/master/CHANGELOG.md#changelog
