### ISSUE TITLE
WKwebview(iOS) Paypal error

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#319]
We get error: 
![screen shot 2017-11-14 at 3 47 18 pm](https://user-images.githubusercontent.com/3535911/32783283-dbdf2596-c953-11e7-856b-535102293a42.png)

**Comment by crookedneighbor** [comment]
I was able to use PayPal in a WK webview without any issue.

Do you get the same error on https://braintree.github.io/braintree-web-drop-in/ ?

Are there any messages in the console? (viewable on desktop Safari using the Develop menu)

**Comment by MixMe** [comment]
Using "React Native" WKWebView is not working :(
Using "Swift" WKWebView is working :)
very strange :)

**Comment by crookedneighbor** [comment]
Going to close this, as it's not an issue with the drop-in SDK. 

If you'd like to open an issue on https://github.com/paypal/paypal-checkout/issues, feel free. It's the library that manages the PayPal UI. I'm not certain that React Native is a supported platform, but feel free to reach out and ask.
