### ISSUE TITLE
Documentation for Apple Pay, 3DSecure

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#323]
How to implement ? :)
version 1.9.0

**Comment by crookedneighbor** [comment]
See https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create

Docs on https://developers.braintreepayments.com are coming soon and I'll post here when they are ready.

**Comment by crookedneighbor** [comment]
Apple Pay docs are now out: https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#apple-pay

3D Secure is still in progress

**Comment by crookedneighbor** [comment]
3D Secure docs are out now: https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#3d-secure
