### ISSUE TITLE
Apple Pay not working in 1.9.0

### ISSUE THREAD

**Issue by dpolivy** [braintree/braintree-web-drop-in#324]
### General information

* SDK/Library version: 1.9.0
* Environment: Sandbox
* Browser and OS: iOS 11

### Issue description

I've followed the instructions, and can't get Apple Pay working in the sandbox. Yes, I'm using a sandbox iCloud account, have a test credit card added, and `ApplePaySession.canMakePayments()` returns `true`.

From some debugging into the drop in, I'm seeing that my `gatewayConfiguration` is coming back with an `applePayWeb` field, but not `applePay` which is being looked for here:

https://github.com/braintree/braintree-web-drop-in/blob/2355dcbcdd733d5a8aa7a1420bc6160d56bddd27/src/dropin-model.js#L217

Is this a bug in the drop-in?

**Comment by crookedneighbor** [comment]
You're absolutely right.

The `applePay` setting refers to iOS. Our test merchant had both, and we missed this. I've opened a PR to fix it: https://github.com/braintree/braintree-web-drop-in/pull/325

**Comment by dpolivy** [comment]
Is there a hosted version of the dev changes I can test with?

**Comment by dpolivy** [comment]
@crookedneighbor With the fix applied locally, the Apple Pay option appears. However, when I tap the black Apple Pay button, I get a JS error:

````
TypeError: Type error

[native code]:9935:43	
dropin.js:9935:43_showPaymentSheet
````

**Comment by crookedneighbor** [comment]
This should be fixed in 1.9.1. Can you try with the hosted version?

**Comment by dpolivy** [comment]
@crookedneighbor Same with 1.9.1. It seems to be failing here:

https://github.com/braintree/braintree-web-drop-in/blob/2355dcbcdd733d5a8aa7a1420bc6160d56bddd27/src/views/payment-sheet-views/apple-pay-view.js#L56

I am passing this into the `braintree.dropin.create` call:

````
					applePay: {
						displayName: 'Test',
						paymentRequest: {
							label: 'Test',
							total: amount
						}
					}
````

Any ideas?

**Comment by dpolivy** [comment]
@crookedneighbor OK, I think I figured it out. This is the correct way to pass in the create options:

						paymentRequest: {
							total: {
								label: 'Test',
								amount: amount,
								type: 'final'
							}
						}

I can now get the Apple Pay UI to appear. Your support folks are giving out bad information here; they are the ones that provided the original code snippet that I was passing in. Might want to let them know that it's not correct.

**Comment by crookedneighbor** [comment]
Strange that they gave you an incorrect snippet. The docs look like this: https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#apple-pay

What's your ticket number so I can follow up with the support people?

**Comment by sidonaldson** [comment]
@crookedneighbor is it worth mentioning apple pay requires https?

**Comment by crookedneighbor** [comment]
Someone opened a PR about it: https://github.com/braintree/braintree-web-drop-in/pull/328

We'll update the docs to call that out as well.

**Comment by dpolivy** [comment]
@crookedneighbor Ticket # is 1746417 -- I let them know about the error, too.

**Comment by crookedneighbor** [comment]
Turns out, I gave them that snippet. My fault for not double checking it before I gave them the snippet.
