### ISSUE TITLE
Saved Apple Pay payment methods say 'undefined' in the small label area

### ISSUE THREAD

**Issue by julka** [braintree/braintree-web-drop-in#332]
### General information

* SDK/Library version: 1.9.0
* Environment: Sandbox and Production
* Browser and OS: Safari 10 & 11 on OS X and iOS 10 & 11

### Issue description

Customers with saved Apple Pay payment methods see `undefined` in the small label area for the payment method. In order to get this far in an Apple Pay saved payment method, you'll need to fix #330 (see PR #329) first. 

Here's a pull request with a fix: #331

**Comment by crookedneighbor** [comment]
Closed with https://github.com/braintree/braintree-web-drop-in/pull/331
