### ISSUE TITLE
[3DSecure] [Firefox] Modal doesn't close when there is an error

### ISSUE THREAD

**Issue by Minishlink** [braintree/braintree-web-drop-in#335]
### General information

* SDK/Library version: 1.9.1
* Environment: Sandbox
* Browser and OS: Firefox 57.0.1 (64 bits) on MacOS 10.13.1

### Issue description

Hello,

On Firefox, when there is a 3D Secure error, the modal doesn't close. This can be seen in this [codepen](https://codepen.io/braintree/pen/BZWdmy) with the card number `4000000000000051`.

**Comment by crookedneighbor** [comment]
Looks like it's not limited to Firefox. Reproduced the issue in Chrome.

Thanks for the report, we'll look into it.

**Comment by Minishlink** [comment]
Oh strange I wasn't seeing this on my Chrome. It looks like a race condition

**Comment by crookedneighbor** [comment]
The problem happens when no iframe is passed back (which means liability was not shifted). Opened a PR to fix that. https://github.com/braintree/braintree-web-drop-in/pull/338

**Comment by crookedneighbor** [comment]
The fix for this will go out in the next release.

**Comment by Minishlink** [comment]
Thanks @crookedneighbor!

**Comment by Minishlink** [comment]
@crookedneighbor Could you release a new version?

**Comment by crookedneighbor** [comment]
I'm shooting for a release at the end of this week, or the beginning of next week.

**Comment by crookedneighbor** [comment]
This has been released today as v1.9.3

**Comment by Minishlink** [comment]
Thanks @crookedneighbor!
