### ISSUE TITLE
Wrong Card Types Shown

### ISSUE THREAD

**Issue by edwinveldhuizen** [braintree/braintree-web-drop-in#337]
### General information

* SDK/Library version: v1.9.2

### Issue description

We have different set of supported card types per merchantAccounts/currencies, but in the drop-in it always shows all of them:
<img width="985" alt="screen shot 2017-12-13 at 15 20 22" src="https://user-images.githubusercontent.com/1787915/33943388-38aec1b0-e019-11e7-96d6-68d8226b33bb.png">

I wrote some own code to hide the ones that are not supported, but it would be best I could just include the merchantAccount on creation, so it hides the unsupported card types. Same goes for the ones in the vault, if those could be automatically hidden it would be great.

**Comment by crookedneighbor** [comment]
When generating your client token, are you passing in the merchant account id property? https://developers.braintreepayments.com/reference/request/client-token/generate/php#merchant_account_id

**Comment by edwinveldhuizen** [comment]
@crookedneighbor You're right, I should have dug a little deeper. Thanks!

**Comment by crookedneighbor** [comment]
:+1:
