### ISSUE TITLE
Deprecation warning when installing braintree-web-drop-in

### ISSUE THREAD

**Issue by fazpu** [braintree/braintree-web-drop-in#342]
### General information

* SDK/Library version: 1.9.2
* node version: 8.9.3

### Issue description

when installing the package via `yarn add braintree-web-drop-in`, the following is shown:

`(node:8060) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

Does it mean the library will be unusable in the upcoming node versions? Are there any plans to do something about it?

**Comment by crookedneighbor** [comment]
Can you be more specific about where you are seeing this error? Is it happening on the install step? I'm using the latest version of yarn and the version of node specified. I don't see the warning message.

```
 ᎒ yarn add braintree-web-drop-in
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
└─ braintree-web-drop-in@1.9.2
✨  Done in 0.41s.
```

**Comment by crookedneighbor** [comment]
I don't think there's anything actionable for us here, so I'm going to close the issue, but feel free to comment if you can provide us more information to investigate.
