### ISSUE TITLE
Callback after user returns from PayPal checkout

### ISSUE THREAD

**Issue by An1mo16** [braintree/braintree-web-drop-in#346]
### General information

* SDK/Library version: braintree-web-drop-in 1.9.2
* Environment: Sandbox
* Browser and OS: general

### Issue description

I have a question regarding callback after PayPal checkout is complete in "vault" flow. 
Is it possible to know by some value in the instance of dropin or callback that PayPal checkout was complete?

Because in my opinion, this flow is a little bit confusing for the user.  The user would complete checkout and expects that he already paid. But he needs to press "Submit payment" button again to actually execute the payment. I would like to at least change the text of the button or make it clearer for the user in UI that he needs to finish payment with help of mentioned callback or other way to know if the user got back from Paypal. Also, state of PayPal action would be helpful too.

Thank you very much.

**Comment by bluk** [comment]
You can [subscribe to events](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on) in Drop-in. In particular, [this example](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on-examples) may help with the `paymentMethodRequestable` event to know when the PayPal flow is completed.
