### ISSUE TITLE
3DSecure popup stuck at initializing UI

### ISSUE THREAD

**Issue by ernsheong** [braintree/braintree-web-drop-in#352]
### General information

* SDK/Library version: DropIn v1.9.3
* Environment: Sandbox
* Browser and OS: Chrome Version 63.0.3239 on Mac High Sierra

### Issue description

1. Using dummy Visa card (4111 1111 1111 1111)
1. Initiate purchase
1. 3DSecure popup appears

![image](https://user-images.githubusercontent.com/1343284/35665611-f4b9d33a-0761-11e8-92e1-0580595d7c20.png)

Expected: See some UI for 3DSecure verification
Actual: UI is stuck as seen in screenshot. There are no console errors. UI is there when inspected, but it remains invisible.

When I close the window, the transaction passes. Is this expected for Sandbox? It should work in Production?

I am using Web Components but I have already worked around this, and the popup is at the document top level.

**Comment by crookedneighbor** [comment]
Weird. I'm able to reproduce it. I'll look into fixing this.

**Comment by crookedneighbor** [comment]
This has been fixed in 1.9.4

**Comment by ernsheong** [comment]
Thank you, the verification UI is now displaying.
