### ISSUE TITLE
Canot red property 'render' of undefined.

### ISSUE THREAD

**Issue by RoberMac** [braintree/braintree-web-drop-in#354]
### General information

* SDK/Library version: 1.9.2
* Environment: Sandbox
* Browser and OS: Chrome 64.0.3282.140 (64-bit) on macOS 10.13.3

### Issue description

I got this error. Works fine at <= 1.7.0 but >= 1.8.0.

![image](https://user-images.githubusercontent.com/4065233/35736857-8664f802-0864-11e8-8508-7d601b91869b.png)

and the code:
```
$(function() {
  braintree.dropin.create({
    authorization: '{{ bt_client_token }}',
    container: '.c-payment-methods',
    locale: '{{ locale }}',
    paypal: {
      flow: 'vault'
    }
  }, function(createErr, dropinInstance) {
  ...
  });
})
```

**Comment by crookedneighbor** [comment]
Do you have a script on your page that is creating a `paypal` variable?

`render` is [called from the `paypal.Button` object provided by checkout.js](https://github.com/braintree/braintree-web-drop-in/blob/887db10f4d26e38d8d2c09c832ef2fcecdadce97/src/views/payment-sheet-views/base-paypal-view.js#L72). We only load the PayPal script if a `paypal` object does not already exist on the page: https://github.com/braintree/braintree-web-drop-in/blob/5d7032e25cd3ccd54a1563f66b854c059389559a/src/dropin.js#L320

**Comment by RoberMac** [comment]
thanks @crookedneighbor , fixed !
