### ISSUE TITLE
Labels do not focus fields

### ISSUE THREAD

**Issue by idontusenumbers** [braintree/braintree-web-drop-in#365]
### General information

* SDK/Library version: 1.9.4
* Environment: Sandbox
* Browser and OS Chrome on Mac 10.13.2

### Issue description
Clicking on the label "Card number" does not properly focus the card number field.

Seems the hosted field example on the braintree support site works properly.

For now I am using the following workaround which seems to work in at least Chrome:

	$('.braintree-form__label').on('click', function () {
		$(this).next('.braintree-form__field').find('label').trigger('click');
	})

This is tricky to work around because the element needing focus is inside the protected iframe.

**Comment by crookedneighbor** [comment]
You're right, this is a miss. We'll get this fixed up.

**Comment by crookedneighbor** [comment]
This is fixed in 1.10.0
