### ISSUE TITLE
Default styles of dropin are frustrating

### ISSUE THREAD

**Issue by idontusenumbers** [braintree/braintree-web-drop-in#366]
### General information

* SDK/Library version: 1.9.4
* Environment: Sandbox
* Browser and OS Chrome on macos 10.13.2

### Issue description

I'm using the dropin on my site. The default styles, of course, do not match my site. I am going through extreme lengths to get them to match.

I suspect it would be a better course to leave these forms minimally styled (read: not styled) in an attempt to clash less with surrounding designs and require fewer css overrides.

Also, as is, there are so many tiny little problems with the default styles that need to be fixed by consumers of the library:
* There are numerous hidden/empty elements which have state maintained fairly inconsistently. For example, the validation messages that start out empty but are later hidden.
* Content shifts a lot as the form is manipulated. This creates moving hit targets for the entire page below the form
* The font should DEFINITELY be inherited from the surrounding content instead of overridden
* Numerous measurements are specified in px instead of ems/rems
* Fields do not indicate focus when focused

**Comment by idontusenumbers** [comment]
From another github issue on this repo, here's a screenshot from a fairly-minimally modified design that looks pretty sloppy, mostly due to the the default styles. Look at the nested rounded rectangles, the awkward outlines, and the little artifacts between sections caused by the rounded rectangles. I too experienced all of these issues when I was 'resetting' the styles on the dropin.

https://user-images.githubusercontent.com/565038/29930601-115f43ba-8e6f-11e7-8894-28f86040ea39.png

**Comment by crookedneighbor** [comment]
Drop-in is intentionally opinionated. BUT, it is also open source and you can make changes as you see fit. I've opened a PR to add explicit instructions for doing customizations (both small and substantial) to the README: https://github.com/braintree/braintree-web-drop-in/pull/372/files

**Comment by idontusenumbers** [comment]
If one designer + developer at braintree fixes the dropin's design, then that saves hundreds or thousands of other designers + developers from doing the same. If the idea behind the dropin is that developers and designers will just leave it as-is, why not at least make it look good and behave well?
