### ISSUE TITLE
Fields do not properly validate when focused through label

### ISSUE THREAD

**Issue by idontusenumbers** [braintree/braintree-web-drop-in#367]
### General information

* SDK/Library version: 1.9.4
* Environment: Sandbox
* Browser and OS Chrome on mac 10.13.2

### Issue description

When focusing elements by clicking on a label, the validation does not trigger on blur which is inconsistent with when the fields are focused via keyboard (tab) or clicking directly on the field.

This is related to https://github.com/braintree/braintree-web-drop-in/issues/365

**Comment by crookedneighbor** [comment]
We've got a PR out for this and #365. Thanks for bringing this up! https://github.com/braintree/braintree-web-drop-in/pull/369

**Comment by crookedneighbor** [comment]
This is fixed in 1.10.0
