### ISSUE TITLE
2-letter culture code like 'en' make loading PayPal UI to fail

### ISSUE THREAD

**Issue by abereznyi** [braintree/braintree-web-drop-in#374]
### General information

* SDK/Library version: 1.9.3
* Environment: Sandbox
* Browser and OS:  Chrome or Firefox on Windows

### Issue description

2-letter culture code like 'en' in dropin.create() call makes PayPal UI to fail (dropinInstance._model.failedDependencies) with error:
"A linked sandbox account is required to use PayPal Checkout in sandbox".

With 5-letter culture code en_US it works fine. 

Also culture codes have underscores (_) instead of  normal dash in the ISO culture names (e.g. en-US is not understood as valid ISO culture).

**Comment by jackellenberger** [comment]
Hey, thanks for bringing this to our attention, @abereznyi! We'll take a look and respond to this issue once we have fix lined up.

**Comment by jackellenberger** [comment]
Hi @abereznyi, we've opened https://github.com/braintree/braintree-web-drop-in/pull/376 to hopefully make those locale errors easier to understand. Could you double check that you have a [linked paypal sandbox](https://developers.braintreepayments.com/guides/paypal/testing-go-live/ruby#linked-paypal-testing) account set up as well? That may be an issue separate from the locale code.

**Comment by abereznyi** [comment]
Yes, I have a linked paypal sandbox
<https://developers.braintreepayments.com/guides/paypal/testing-go-live/ruby#linked-paypal-testing>
 account set up.
It is working fine  when culture (locale) is set to 'en_US', but not with
culture set to 'en'.


Thanks, Alex
Tel. 724-484-3457

On Wed, Mar 14, 2018 at 10:52 AM, Jack Ellenberger <notifications@github.com

**Comment by crookedneighbor** [comment]
We recommend using the full 5 character string. See `locale` in https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create for the possible values.

**Comment by crookedneighbor** [comment]
This has been fixed with v1.11.0. Now 2 character locales will use the five character locale under the hood.
