### ISSUE TITLE
Show drop in on ReactJS

### ISSUE THREAD

**Issue by khuong291** [braintree/braintree-web-drop-in#378]
This code can not compiled.

`import DropIn from 'braintree-web-drop-in';`

```
<DropIn
  container="#dropin-container"
/>
```

**Comment by crookedneighbor** [comment]
I'm fairly certain you want

```
import * as DropIn from 'braintree-web-drop-in';
```

**Comment by crookedneighbor** [comment]
Going to close this now, because I'm fairly certain that is the issue. Comment here if you still cannot import it.
