### ISSUE TITLE
"Invalid calling object" at Edge and IE

### ISSUE THREAD

**Issue by onlyeric23** [braintree/braintree-web-drop-in#382]
### General information

* SDK/Library version: 1.10.0
* Environment: Both
* Browser and OS: Edge 41.16299.15.0, IE 11.192.16299.0

### Issue description

I find a issue when creating dropin at Edge and IE.
The issue is described very clearly in https://github.com/braintree/braintree-web/issues/219#issuecomment-291139849
It seems like braintree-web has the same problem before, and it is been fixed now.
However braintree-web-drop-in does not solve it, yet.

**Comment by crookedneighbor** [comment]
It's not going to be that error related to atob, because the only use of atob in the library is through the braintree-web dependency, and we're using a version after it was fixed there.

Do you experience the problem on the demo site? https://braintree.github.io/braintree-web-drop-in/

If not, can you provide a staging site or reproducible snippet?

**Comment by onlyeric23** [comment]
Hi @crookedneighbor, 
Thx for your reply. I do not experience the problem on the demo site.
You can browse our site [here](https://payoutstage.contribulet.com/orgs/e16a4313-62c1-4a4f-b7b0-a10d4a4d3901/donate_directly?authToken=33a0289c-7091-49bf-9591-5ba4f5354172#redirectedFromApp) with IE or Edge. You can see web-drop-in after chose an amount then clicked on "Continue" button.

I traced few lines of web-drop-in. I thought the issue is caused by https://github.com/braintree/braintree-web-drop-in/blob/413187286f718e56b3d21e8f73968380432b9c40/src/lib/polyfill.js.

After I manually force using polyfill's atob instead of global.atob in sendAnalyticsEvent or just use the workaround from https://github.com/braintree/braintree-web/issues/219#issuecomment-291139849, the issue does not appear anymore.
