### ISSUE TITLE
Possibility to delete a payment method

### ISSUE THREAD

**Issue by alexandrudanpop** [braintree/braintree-web-drop-in#391]
### General information
* SDK/Library version:  "braintree-web-drop-in": "^1.10.0"
* Environment: Sandbox
* Browser and OS: Chrome 66.0.3359.139 (Official Build) (64-bit), Windows 10

### Issue description
I've been searching the docs and the Web for a possibility to delete a payment method from the braintree web dropin but found none. 

This would require that when a delete button is clicked the paymentMethodToken for the selected payment method is returned in a callback function. Then this paymentMethodToken could be used to call the payment-method/delete API in the backend
https://developers.braintreepayments.com/reference/request/payment-method/delete/node 

Is this supported, or is there any plan to support this?

**Comment by Epreuve** [comment]
This is not a currently supported feature of the Drop-in, however we are looking at the possibility of adding it in a future version.  I'll leave this issue open so we can let you know if there are any updates on this.

**Comment by crookedneighbor** [comment]
It is currently being worked on. Hoping to get it out in the next couple of weeks.

**Comment by crookedneighbor** [comment]
PR for this feature: https://github.com/braintree/braintree-web-drop-in/pull/415

**Comment by patriciojofre** [comment]
I sent a question on #415 

👍

**Comment by crookedneighbor** [comment]
This is out in v 1.12.0
