### ISSUE TITLE
Basic dropin usage yield lots of warnings

### ISSUE THREAD

**Issue by rvion** [braintree/braintree-web-drop-in#392]
### General information

- Chrome Version 66.0.3359.139 (Official Build) (64-bit), OSX, 
- on Braintree __Sandbox__ environment 
- dropin included with a `<script src='https://js.braintreegateway.com/web/dropin/1.10.0/js/dropin.min.js'></script>` in document head

### Issue description

Basic dropin usage yield lots of warnings

notably: 
 - [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
 - [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
 - [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='cc-number', confirm at https://goo.gl/6KgkJg)  etc
 - The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. 

![image](https://user-images.githubusercontent.com/2150990/39566100-b3fcd388-4eba-11e8-8728-97846096ed76.png)

**Comment by crookedneighbor** [comment]
FYI, all but the SSL cert warnings are only emitting because you have verbose logging turned on. 

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
> [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.

We'll review our implementation for these.

> [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='cc-number', confirm at https://goo.gl/6KgkJg) etc

This has already been fixed, and the next version of Drop-in that's released will silence these warnings.

> The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70.

This is due to the SSL certs used by PayPal. They have a team working on rotating out these certs before M70 is released. 

Braintree will have a similar message in production. (see https://github.com/braintree/braintree-web/issues/343) and that will also be resolved before M70 is released. (Sandbox has already been taken care of)

**Comment by rvion** [comment]
>  all but the SSL cert warnings are only emitting because you have verbose logging turned on.

that's precisely why I have it on, to detect probable implementation problems :)

> We'll review our implementation for these.

thanks !

> This has already been fixed, and the next version of Drop-in that's released will silence these warnings.

Oh, sorry for that. I did a quick search prior to submitting, but [did not find anything](https://github.com/braintree/braintree-web-drop-in/search?utf8=%E2%9C%93&q=autocomplete&type=). Thanks !

**Comment by crookedneighbor** [comment]
You didn't find anything, because the problem exists upstream: https://github.com/braintree/braintree-web/issues/353

Drop-in just hasn't been deployed with the new version of braintree-web. Hoping to get it out next week.

**Comment by crookedneighbor** [comment]
> [DOM] Input elements should have autocomplete attributes (suggested: autocomplete='cc-number', confirm at https://goo.gl/6KgkJg) etc

This message should now be fixed. Still working on the other ones.

**Comment by crookedneighbor** [comment]
The warnings related to Drop-in should be fixed now. There are still some related to checkout.js, but we don't have any control over those.

You can report them here: https://github.com/paypal/paypal-checkout/issues

**Comment by crookedneighbor** [comment]
Fixed in v1.13.0 that is.
