### ISSUE TITLE
Postal Code 

### ISSUE THREAD

**Issue by vincemoley** [braintree/braintree-web-drop-in#397]
### General information

* SDK/Library version: 1.9.3
* Environment: Sandbox
* Browser and OS iPhone 11.3.1

### Issue description

Postal Code input uses query keyboard on focus, unlike card number, exp date & cvv inputs, which use number keyboard.

Let me know if you need any additional details

**Comment by crookedneighbor** [comment]
This is intentional because many non-US postal codes are alpha-numeric instead of being numeric. If you'd like to override this behavior, you can pass this:

```js
braintree.dropin.create({
  authorization: 'your-client-token-or-tokenization-key',
  card: {
    overrides: {
      fields: {
        postalCode: {
          type: 'tel'
        }
      }
    }
  }
}, function (err, instance) { /* callback */ })
```

And that will set the input type for the postal code input to `tel` like the number and cvv inputs.

**Comment by ultrono** [comment]
Ah ha! Overriding the field type solved it for myself. I initially assumed the fact I incorrectly had the locale set to `en_US` (and not `eb_GB`) caused the numeric field to trigger. Switching the locale to `en_GB` didn't change anything, which was surprising too.
