### ISSUE TITLE
clearSelectedPaymentMethod() does not clear nonce

### ISSUE THREAD

**Issue by plevetsky** [braintree/braintree-web-drop-in#408]
### General information

* SDK/Library version: 1.11.0
* Environment: Sandbox
* Browser and OS: All

### Issue description

Is it expected behaviour that `requestPaymentMethod()` does not return a new nonce after `clearSelectedPaymentMethod()` has been called?

I am using the Drop-in UI in conjunction with the 3DS lib and the behaviour above is causing me the following problem:

1. Customer selects a payment method and we call `requestPaymentMethod()` to get the nonce and then initiate the 3DS flow.
2. Customer cancels the 3DS flow and we call `clearSelectedPaymentMethod()`.
3. Customer chooses the same payment method again, but we get the same nonce back from `requestPaymentMethod()` and therefore cannot complete the 3DS flow because the nonce has already been consumed.

**Comment by davodesign84** [comment]
@plevetsky having the same issue here. I would expect the card not to be store if the 3DS is not passed.

**Comment by davodesign84** [comment]
@crookedneighbor amazing! Is there any way to track this issue?

**Comment by crookedneighbor** [comment]
Just follow this issue (as you are doing). We'll update here when it's fixed and deployed.

**Comment by andismith** [comment]
Is there any update - or ETA on a fix - on this please?

**Comment by crookedneighbor** [comment]
We had some pre-requisite work that needed to be done that was finished this morning. I've opened a PR to address this issue: https://github.com/braintree/braintree-web-drop-in/pull/417
