### ISSUE TITLE
I need onPaymentMethodReceived method

### ISSUE THREAD

**Issue by manishkumar1689** [braintree/braintree-web-drop-in#411]
### General information

* SDK/Library version: 
* Environment: 
* Browser and OS

**Comment by crookedneighbor** [comment]
You can utilize the events API for this. Specifically, [`paymentMethodRequestable`](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#event:paymentMethodRequestable).

This event will fire when the payment method is able to be requested. 

For vaulted payment methods and payment methods that require a separate auth (like PayPal), the event object that is emitted will include a `paymentMethodIsSelected` that is set to `true`. This indicates that the payment method has been selected by the customer and is ready to be requested and sent to the server.

For the card view, the event will fire when the fields are all valid, but we recommend letting the customer submit the card form in this case, so you can check the `paymentMethodIsSelected` property. It will be `false` in this case.

Example from [the client SDK documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/Dropin.html#on):

```js
var submitButton = document.querySelector('#submit-button');

braintree.dropin.create({
  authorization: 'CLIENT_AUTHORIZATION',
  container: '#dropin-container'
}, function (err, dropinInstance) {
  function sendNonceToServer() {
    dropinInstance.requestPaymentMethod(function (err, payload) {
      if (err) {
        // handle errors
      }

      // send payload.nonce to your server
    });
  }

  // allows us to still request the payment method manually, such as
  // when filling out a credit card form
  submitButton.addEventListener('click', sendNonceToServer);

  dropinInstance.on('paymentMethodRequestable', function (event) {
    // if the nonce is already available (via PayPal authentication
    // or by using a stored payment method), we can request the
    // nonce right away. Otherwise, we wait for the customer to
    // request the nonce by pressing the submit button once they
    // are finished entering their credit card details
    if (event.paymentMethodIsSelected) {
      sendNonceToServer();
    }
  });
});
```
