### ISSUE TITLE
How can I disable card option from dropin???

### ISSUE THREAD

**Issue by manishkumar1689** [braintree/braintree-web-drop-in#412]
### General information

* SDK/Library version: 
* Environment: 
* Browser and OS

**Comment by crookedneighbor** [comment]
You can utilize the `paymentOptionPriority` option in the create call. If you omit `'card'` from the options, Drop-in will not offer credit cards as an option to the user. For instance, to just use PayPal:

```js
braintree.dropin.create({
  authorization: 'your-tokenization-key-or-client-token',
  paypal: { /* your paypal config */ },
  paymentOptionPriority: ['paypal']
}, callback);
```
