### ISSUE TITLE
About the test environment

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#414]
How to set Drop in to test environment ?
https://developers.google.com/pay/api/web/guides/test-and-deploy/integration-checklist#about-the-test-environment

**Comment by crookedneighbor** [comment]
If you use a sandbox client token or tokenization key, it will automatically test Google Pay in test mode. See https://github.com/braintree/braintree-web/blob/f552b9a5eca14c0e9fdca93aa03110716b057fdd/src/lib/generate-google-pay-configuration.js#L10

**Comment by MixMe** [comment]
thx
