### ISSUE TITLE
iOS Keyboard reopens after loosing focus and closing keyboard

### ISSUE THREAD

**Issue by wenga86** [braintree/braintree-web-drop-in#419]
### General information

* SDK/Library version: 1.12.0
* Environment: All
* Browser and iOS: Safari, Chrome 68.0.3440.83 (64-bit) on iOS 11.4.1

### Steps to reproduce

1. Click in the credit card number input field
2. Fill in some numbers(Doesn't have to be valid or the complete number)
3. Click outside the input box (Somewhere on the page, even if there is no elements there)
4. Close keyboard with the Done or the X button
5. Click somewhere and the keyboard reopens

### Issue description
Keyboard continues to pop open when I click anywhere on the page, even after I call `teardown` on the drop UI. If I click on the field again and maintain focus on the element and click `Done` or  `X` the issue stops. Seems to be happening with all fields.

This issue seems to be nearly identical to one with [Strips](https://github.com/stripe/react-stripe-elements/issues/174)

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll look into this.

**Comment by yagrawl** [comment]
Hi @wenga86 We couldn't reproduce the issue on both iOS 11 and iOS 12 public beta. Did you try any workarounds from the issue you linked? Please reach out to support with code snippets if you continue to experience this issue.

**Comment by wenga86** [comment]
Hi @yagrawl I've created a [video demonstrating the issue](https://www.youtube.com/watch?v=euBXpwLa6LA). The demo is on a iPhone X, 11.4.1 Safari. I hope this helps clearify things. The demonstration uses the repos [demo page](https://braintree.github.io/braintree-web-drop-in/).

**Comment by jackellenberger** [comment]
@wenga86 Very interesting, thank you for the video. We'll see what there is to be done.

**Comment by crookedneighbor** [comment]
This is a pretty strange bug in Safari. Solution here: https://github.com/braintree/braintree-web-drop-in/pull/424

Hoping to do a release early next week.

**Comment by crookedneighbor** [comment]
This should be fixed in 1.13.0

**Comment by wenga86** [comment]
Awesome! Just spot checked it on my end and everything looks good. Thanks again.

**Comment by swapnilhpatil** [comment]
Hi @crookedneighbor ,
Hi 
We were facing issue for keyboard on IOS device, and it's been resolved after upgrading version of barintree-web-drop-in@1.13.0(latest).

Now we are facing another issue, when landed to payment screen and tried entering card details - specifically card number. Input box seems to be disbaled/not accepting the keyed numbers in card number input box. If I select or touch "Expire Date" input tab and then return to "Card number" input tab. That time, we don't have issue with capturing card number in input box.

**Comment by crookedneighbor** [comment]
@swapnilhpatil Does this occur the very first time you tap the card number field? Or does it occur after you've tapped it once, left and then come back?

If the latter, that's a known bug in iOS safari regarding keeping focus on the iframes. It doesn't bring up the keyboard because the iframe believes the focus never shifted away from it. Tapping it a second time will bring up the keyboard.

If it's occurring on the very first time you tap the card input, does the behavior occur in the demo: https://braintree.github.io/braintree-web-drop-in/

I can't reproduce the issue there on my iPhone, so could you provide more details about your device and iOS version?

**Comment by swapnilhpatil** [comment]
This issue is occurring each time when I landed to payment screen only for
card number input box.
Device configurations :
1.iPhone 6
IOS version 11.4.1

Thank you for considering my issue

Yours Sincerely,
Swapnil Patil

**Comment by crookedneighbor** [comment]
@swapnilhpatil Can you please open up a new issue on this repo?

**Comment by swapnilhpatil** [comment]
Hi @crookedneighbor,
I am attaching video file regarding the issue. Please check that video.

Yes, @crookedneighbor,
I am going to open a new issue in this repo.

Thanks for the frequent reply,

**Comment by crookedneighbor** [comment]
@swapnilhpatil Definitely open a new issue, since the behavior is separate from this one.
