### ISSUE TITLE
Payment methods are not vaulted on first session after creating a customer

### ISSUE THREAD

**Issue by yeldarby** [braintree/braintree-web-drop-in#420]
### General information

* SDK/Library version: _1.12.0_
* Environment: _Sandbox_
* Browser and OS: _Version 68.0.3440.106 (Official Build) (64-bit) on macOS High Sierra 10.13.5_

### Issue description

I'm using dropin to let the user store payment methods for later. I've set it up by passing a clientToken associated with that user's ID generated on the server.

I'm then creating a dropin and passing that authorization token.

On the first pageload, when a user enters their card or links their Paypal account, nothing gets stored in their vault. If I reload the page and do the same thing it works.

I'm trying to figure out whether this is an issue with generating my token or with dropin vaulting the info.

The basic logic on the server side is to use `gateway.customer.find` to search for the user, if found generate a token. If not found create the user first and then generate the token.

```javascript
var getBraintreeInfoFor = function(MY_USER_ID, cb) {
	var getTokenForCustomer = function(customer) {
		gateway.clientToken.generate({
			customerId: customer.id
		}, function(err, response) {
			cb(err, customer, response);
		});
	};

	gateway.customer.find(MY_USER_ID, function(err, customer) {
		if(!err) {
			// we found the customer!
			getTokenForCustomer(customer);
		} else if(err.type == "notFoundError") {
			// customer not found, must be created
			gateway.customer.create({id:MY_USER_ID}, function (err, customer) {
				getTokenForCustomer(customer);
			});
		} else if(err) {
			// other error
			cb(err);
		}
	});
};
```
Is there something different about the first session after creating a user? Or is there a way on the client side to pull the customer ID of the `authorization` to make sure it's getting passed correctly?

I've tried `client.request({endpoint:'customers/MY_USER_ID', method:'get'})` but that doesn't seem to work.

**Comment by crookedneighbor** [comment]
```js
gateway.customer.create({id:MY_USER_ID}, function (err, customer) {
```

This calls back with a result object, not a customer directly. Thape is like:

```
{
  customer: { /* the customer object */ },
  success: true
}
```

So when you call `customer.id`, that equals `undefined`, so it's like you're not passing an id at all. When you reload the page, the customer already exists, so you are generating the client token with the actual id.

You want this instead:

```js
gateway.customer.create({id:MY_USER_ID}, function (err, result) {
  getTokenForCustomer(result.customer);
});
```

**Comment by yeldarby** [comment]
Thank you! That fixed it.
