### ISSUE TITLE
NPM Module Doesn't work when Using import syntax

### ISSUE THREAD

**Issue by jamesdixon** [braintree/braintree-web-drop-in#426]
### General information

* SDK/Library version: 1.13
* Environment: Sandbox
* Browser and OS - Chrome on Mac

### Issue description

Hi, when attempting to initialize an instance of drop-in ui, I'm getting the following error message: 

`Uncaught Error: Channel ID must be specified`

Any ideas? I was using v2 of the drop-in ui without issue.

Thanks!

**Comment by crookedneighbor** [comment]
I can't reproduce the issue. Do you see the same issue here? https://braintree.github.io/braintree-web-drop-in/

Does it occur in incognito mode?

Can you provide a github repo that can reproduce the problem?

I can see that happening if the `hash` is somehow being stripped out of the hosted fields iframes when they are trying to initialize (which is what is used to sync up the post messaging between the iframes and the parent page). Do you have some Chrome extension that may be doing that?

**Comment by jamesdixon** [comment]
I just left my computer but will try this evening. Is channel ID something that now needs to be included when creating the authorization?

**Comment by jamesdixon** [comment]
@crookedneighbor couldn't reproduce with that link. I will try and work up a github repo to reproduce. 

I will tell you that I'm upgrading my [Ember addon](https://github.com/scoutforpets/ember-braintree-components) to use v3 and this is where the issue is occurring. You mentioned a hash possibly being stripped out; nothing that I know of would be doing that.

**Comment by crookedneighbor** [comment]
Very strange. I'm happy to look at a repo when it's available.

**Comment by jamesdixon** [comment]
Trying some different things and I thinking this might be an issue with not being able to import as an es6 module. Guessing this lib isn't built for it? I was able to get things working when using the version from the CDN rather than NPM

**Comment by crookedneighbor** [comment]
I've updated the issue title to reflect the issue. 

As far as I know, it _should_ be importable. If not, we should fix it. 

Are you using Babel? If so, what's your .babelrc?

**Comment by crookedneighbor** [comment]
I was able to run it in a very simple Angular 6 app just fine:

```
import { Component } from '@angular/core';
import dropin from 'braintree-web-drop-in';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'foo';

  ngOnInit() {
    dropin.create({
      authorization: 'sandbox_f252zhq7_hh4cpc39zq4rgjcg',
      container: '#dropin'
    })
  }
}
```

(though, it's also going to be using the browserified version in `dist/browser`, so that may be part of it)

**Comment by jamesdixon** [comment]
@crookedneighbor sorry, had to step away to run some errands. thanks for investigating! it must be something with the way Ember is consuming the file. I'll run some more tests and update you when I'm done in case someone else runs into a similar problem.

**Comment by jamesdixon** [comment]
@crookedneighbor finally got this working. it took some massaging to get ember to allow importing of the module directly from npm. used something called ember-auto-import to take care of this. sorry for leading you down a rabbit hole but i appreciate your help!

**Comment by crookedneighbor** [comment]
Glad we found an explanation for it. Thanks for the update!

**Comment by emhoracek** [comment]
I ran into this error when I accidentally had both drop-in JavaScript and another Braintree JavaScript library on my page. Removing the "braintree-2.32.1.min.js" script tag fixed the problem.
