### ISSUE TITLE
ui not detecting available payment methods based on gateway configuration

### ISSUE THREAD

**Issue by jamesdixon** [braintree/braintree-web-drop-in#429]
### General information

* SDK/Library version: 1.13
* Environment: Sandbox
* Browser and OS: Mac/Chrome

### Issue description

Hi again. In v2 of Drop In UI, I didn't need to pass any specific Paypal options to get it to work properly. It seems Braintree indicated to the UI which payment methods are available. If I now configure paypal manually by passing in something like `{ paypal: { flow: 'vault' }}` and PayPal hasn't been configured, it stills shows up but disables it and has a "developer error" message that it needs to be enabled. Is there some way it can automatically detect what payment methods are available as in v2 and if not, how can I get the payment methods available so I can properly display the UI with those payment methods?

Thanks!

**Comment by crookedneighbor** [comment]
That behavior should _only_ happen in sandbox. In production, it just won't show PayPal as an option if you don't have it enabled in the Braintree control panel.

The reason for this is that originally, Braintree mocked all the PayPal sandbox interactions, so all Braintree sandbox accounts have PayPal enabled. However, PayPal started requiring all PayPal integrations to use [checkout.js](https://github.com/paypal/paypal-checkout) to manage the PayPal UI, and it is incompatible with the mocked PayPal sandbox that Braintree provided.

We chose to show the Developer error in sandbox to make it easier for merchants to turn on PayPal in sandbox for testing.

Again, in production, it simply won't show the PayPal option if you're not enabled for it in the Gateway: https://github.com/braintree/braintree-web-drop-in/blob/8328b79bef9ab5f99e959511e37105241eab4948/src/views/payment-sheet-views/base-paypal-view.js#L107-L112

**Comment by jamesdixon** [comment]
Thanks, @crookedneighbor. I do have PayPal enabled on my sandbox but I do see now where it says to enter credentials for a mock PayPal account. Is this what you were talking about with regards to Braintree accounts no longer being compatible?

**Comment by crookedneighbor** [comment]
Yes. Originally, we were able to skip having merchants sign up for a PayPal sandbox account by mocking out the flow, but since checkout.js is a requirement for integrating now, and it is incompatible with Braintree's mocked flow, each merchant must now sign up for a PayPal sandbox account to do testing in sandbox.

**Comment by jamesdixon** [comment]
Got it. Thanks a ton. I appreciate your help!

Also while I have your attention, do you have any idea when ACH may be available in the other drop-in UIs? and also available with Braintree Recurring Billing?

**Comment by crookedneighbor** [comment]
I do not know. You can contact our support team directly with questions like that: https://articles.braintreepayments.com/forms/contact

**Comment by jamesdixon** [comment]
Thanks, will do. Is it not supported in this version of drop-in UI? Not actually seeing anything in the docs for setting it up even though it's supposedly been enabled on my account.
