### ISSUE TITLE
Braintree iOS card number input box not capturing card number every first-time issue

### ISSUE THREAD

**Issue by swapnilhpatil** [braintree/braintree-web-drop-in#430]
**General Information**

* SDK/Library version: 1.13.0
* Environment: IPhone 6
* Browser and OS : IOS version 11.4.1

**Steps to reproduce** 
1. Select card tab
2. Press the keyboard
3. Touch to expire date input box
4. Enter expire date
5. Return to card number input box
6.Enter card number

**Issue Description**

When landed to payment screen and tried entering card details - specifically card number. Input box seems to be disabled/not accepting the keyed numbers in card number input box. If I select or touch "Expire Date" input tab and then return to "Card number" input tab. That time, we don't have issue with capturing card number in input box.

I have created a video demonstrating the issue. Please refer [_the link_](https://www.youtube.com/watch?v=glUDYP9NNBQ).  I hope this will give you a clear view of the issue..

**Comment by crookedneighbor** [comment]
I still can't reproduce this. 

Are you doing this inside a webview? If so, what kind?

Does the same behavior occur at https://braintree.github.io/braintree-web-drop-in/ ?

**Comment by swapnilhpatil** [comment]
Hi @crookedneighbor,
I've provided a video regarding issue.
Yes, the same behavior is not occurring at https://braintree.github.io/braintree-web-drop-in/ .
I just generated IPA file and tested in my iPhone 6 device.
if you need and details. I will provide you.
Thanks

**Comment by crookedneighbor** [comment]
Yes, I've seen the video, but like I said, I have not yet been able to reproduce the issue on my own device.

You said:

> I just generated IPA file and tested in my iPhone 6 device. if you need any details. I will provide you.

Can you provide more details about your setup? Or a github repo or staging site that can reproduce the issue?

As you noted, the behavior is _not_ occurring in [the demo](https://braintree.github.io/braintree-web-drop-in/). So there's something specific in your setup that is causing the issue.

**Comment by swapnilhpatil** [comment]
We are using Ionic 3 framework and Angular 4 for our project. My project configurations as below : 

Ionic:

ionic (Ionic CLI) : 4.0.1
Ionic Framework : ionic-angular 3.9.2
@ionic/app-scripts : 3.1.11

Cordova:

cordova (Cordova CLI) : 8.0.0
Cordova Platforms : browser 5.0.3, ios 4.5.5

System:

ios-deploy : 2.0.0
NodeJS : v8.11.3 (/usr/local/bin/node)
npm : 6.4.1
OS : macOS High Sierra
Xcode : Xcode 9.4.1 Build version 9F2000

**Comment by crookedneighbor** [comment]
I can't even get Drop-in to load within a basic ionic installation. (works in the browser, but not in an emulator)

Looks like the iframes are never getting set up. Is there something I need to configure in the setup to get it to work?

**Comment by swapnilhpatil** [comment]
on Saturday, I mailed you the required files of the code that is implemented in my project regarding Braintree payments system.Please review those files.

**Comment by crookedneighbor** [comment]
Do you mind if I just copy the files here so other developers have a record of the code? If not, I can just forward them to my team instead.

**Comment by crookedneighbor** [comment]
### ReadMe

>```bash
>$ sudo npm install -g ionic cordova
>//do not use below command , if you have already created project
>$ ionic start mySideMenu sidemenu
>```
>
>```bash
>$ ionic cordova platform add ios
>```
>
>Braintree Specific Plugin Commands
>
>Braintree
>=========================================
>1. sudo npm install --save braintree-web-drop-in
>2. sudo ionic cordova plugin add cordova-plugin-braintree
>3. sudo npm install --save @ionic-native/braintree
>
>jquery Plugin
>=================================
>1. sudo npm install jquery --save
>2. sudo npm install @types/jquery
>
>----------------------------------------------------------------------------
>changes to make in app.module.ts 
>
>1. import { Braintree} from '@ionic-native/braintree';
>2. import * as dropin from 'braintree-web-drop-in';
>
>
>3. Add " Braintree" inside providers
> providers[Braintree]

### payment.ts

```ts
import { Component, Renderer, ElementRef, ViewChild } from '@angular/core';
import { IonicPage, NavController, NavParams, App, AlertController, normalizeURL,LoadingController,ViewController } from 'ionic-angular';
import { Storage} from '@ionic/storage';
import { Http,Headers,RequestOptions } from '@angular/http';
import { Keyboard } from '@ionic-native/keyboard';

import { Braintree, ApplePayOptions,PaymentUIResult, PaymentUIOptions } from '@ionic-native/braintree';
import * as dropin from 'braintree-web-drop-in';
import * as $ from 'jquery';


@IonicPage()
@Component({
  selector: 'page-payment',
  templateUrl: 'payment.html',
})
export class PaymentPage {

private BRAINTREE_TOKEN;
public paymentData : any;
public payAmount : any;

constructor(
    public http: Http,private storage: Storage,
    public viewCtrl: ViewController,
    public app: App,
    private loadingCtrl: LoadingController,
    private alertCtrl: AlertController,
	  private braintree: Braintree,
	  private keyboard:Keyboard,
    private renderer: Renderer,
	  private elementRef: ElementRef
    ) {
	
	  this.payAmount = 10;
	  this.paymentData ="Pay";
	
	}
	
	
  navToHomePage(){
    this.keyboard.close();
	//if you navigated to this page from other page, u can uncommnet below line
    //this.navCtrl.pop();
  }



  focusOut() {
    //let activeElement = <HTMLElement>document.activeElement;
    //activeElement && activeElement.blur && activeElement.blur();
    this.keyboard.close();
  }
  
  paydata(){


	  let loading = this.loadingCtrl.create({content:'Processing... please wait'});
				loading.present();
				setTimeout(() => {
				  loading.dismiss();
				},3000);

	  console.log("-----paydata()--------call");
	  $('#confirmData').hide();
	  $('#confirmmsg').hide();
	  $('#confirmdonation').show();

  
  
  $("#donate").html("Donate");
  var self = this;
  var form = document.querySelector('#nonce-form');
  var hiddenNonceInput = document.querySelector('#my-nonce-input');
  var form = document.querySelector('#payment-form');
      dropin.create({
        authorization: this.BRAINTREE_TOKEN,
        container: '#dropin-container',
         paypal: {
            flow: 'checkout',
            singleUse: true,
            amount: this.payAmount,
            currency: '$',
          }
      }, function (err, dropinInstance) {
           $('#shareAmount').hide();
		   
		   if (err) {
		     console.log("err 1 : "+err);
		     console.error(err);
		     return;
		   }
        
          form.addEventListener('submit', function (event) {
             event.preventDefault();

          dropinInstance.requestPaymentMethod(function (err, payload) {
             if (err) {
              console.log("err 2 : "+err);
              return;
             }
         	  console.log("-----paydata() payload--------");
		        console.log("payload 2 : "+JSON.stringify(payload));
			      console.log("payload.nonce : "+payload.nonce);
            
            if(payload.nonce !==undefined){
               self.paymentDetailsSave(payload.nonce);  
            }
            $("#donate").hide();
            $('#confirmdonation').hide();
            $('#Authenticating').show();
           
          });
        });
      });
     }
  paymentDetailsSave(payloadNonce){
    console.log('payloadNonce :' + payloadNonce);
  }
}
```

### payment.module.ts

```ts
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { PaymentPage } from './payment';

@NgModule({
  declarations: [
    PaymentPage,
  ],
  imports: [
    IonicPageModule.forChild(PaymentPage),
  ],
})
export class PaymentPageModule {}
```

### payment.html

```html
<ion-header>
	 <ion-toolbar style="padding: 0%;">
		 <ion-buttons>
		  <ion-row>
			<ion-col col-2>
			   <button ion-button clear (click)="navToHomePage()" class="mdButton buttonheaderios" style="background: #d82140" >
			       <ion-icon name="ios-arrow-back"  style="font-size:20px"></ion-icon>
			   </button>
		    </ion-col>
		    <ion-col col-10 class="headername">
			  <span><b>Payment Confirmation</b> </span>
		    </ion-col>
		 </ion-row>
		</ion-buttons>
	 </ion-toolbar>
</ion-header>

<ion-content style="background:color:#fff" >
    <div id="confirmmsg" style="background-color: #d1d8d5;">
	   <ion-row col-12 > 
		   <ion-col col-1>
			 <ion-icon name="information-circle" style="font-size: 18px;color:#d5b114"></ion-icon>
		  </ion-col>		
		  <ion-col col-10   text-left>
			 <b>Please confirm on below details</b>
		  </ion-col>
	  </ion-row>
	</div>
	<div  id="confirmdonation"  style="background-color: #d1d8d5; display:none;">
		<ion-row col-12 > 
		   <ion-col col-1>
			  <ion-icon name="information-circle" style="font-size:18px;color:#d5b114"></ion-icon>
		   </ion-col>		
		   <ion-col col-10   text-left>
			   <b> Please select appropriate payment details </b>
		   </ion-col>
	    </ion-row>
    </div>
	
	<div *ngIf="paymentData == 'Pay'">

		<div id="confirmData">
		
			  <ion-row col-12>
				<ion-col col-5>
					  <span>Amount</span>
				  </ion-col>
				 <ion-col col-7>
					  <span>${{paymentDetails.amount}}</span>
				 </ion-col>
			 </ion-row>
			 
		</div>
		
		<div id="successfulPay" class="success"></div>
        <form id="payment-form" style="padding: 2%">
             <div id="dropin-container"></div>
			    <ion-row>
                   <button (click)="paydata();" id="donate"  ion-button round outline type="submit" style="background-color: #d82140;color:#fff;width: 100%;margin-top:8%;margin-bottom: 11%;text-transform: uppercase;">Confirm</button>
                </ion-row>
		</form>

        <form id="nonce-form">
    	     <div id="dropin-container"></div>
		</form>
    </div>
</ion-content>	
```

### payment.scss

```scss
page-payment {
	
	.buttonheaderios {
		border: 1px solid #d82140;
	}
   
   .headername{
      color:#ffffff;
      margin-top:12px;
      font-size: 17px;
      text-align: left;
   }
	[text-canter] {
		text-align: canter !important;
	}
	.label-ios {
		margin: 0;
	}
	.label-md {
		margin: 0;
	}
}
```

**Comment by swapnilhpatil** [comment]
Do you implemented our above code and do you check the issue?

I have a suggestion for you . can you just check "Braintree-form__field-secondary-icon" class, that used in main.html only for "card number" and "cvv"?

**Comment by crookedneighbor** [comment]
I have not had a chance yet.

> I have a suggestion for you . can you just check "Braintree-form__field-secondary-icon" class, that used in main.html only for "card number" and "cvv"?

Not sure what you're asking here.

**Comment by swapnilhpatil** [comment]
Actually, we are not using '@ionic-native/braintree' package. It was creating some dependency issue in our project. we removed that import from our project. Right now, it's unused import in our project. It's my mistake. I apologize for that.
we are using 'braintree-web-drop-in' only.
Yes,You can remove that import package.

**Comment by crookedneighbor** [comment]
So far I haven't been able to reproduce the issue. There's too many elements in the files you provided that are missing, so I couldn't integrate exactly like you are integrating.

But starting a new project and adding `<allow-navigation href="*" />` to config.xml allowed the iframes to load. I'm not seeing any problems with the keyboard, however.

I suspect it has something to do with `@ionic-native/keyboard` though. Can you try commenting out the `this.keyboard.close` calls?

If you provide a full repo that reproduces the problem, I'm happy to look at it further. You don't need to make your whole app available on github, of course, just a sample app that reproduces the issue.

**Comment by swapnilhpatil** [comment]
> 
> 
> So far I haven't been able to reproduce the issue. There's too many elements in the files you provided that are missing, so I couldn't integrate exactly like you are integrating.
> 
> But starting a new project and adding `<allow-navigation href="*" />` to config.xml allowed the iframes to load. I'm not seeing any problems with the keyboard, however.
> 
> I suspect it has something to do with `@ionic-native/keyboard` though. Can you try commenting out the `this.keyboard.close` calls?
> 
> If you provide a full repo that reproduces the problem, I'm happy to look at it further. You don't need to make your whole app available on github, of course, just a sample app that reproduces the issue.

Yes, we already have `<allow-navigation href="*" />`   in our config.xml file.
And After filling all payment details, the keyboard was not going to close automatically anyhow. so that, I manually close the keyboard using '@ionic-native/keyboard' import. that's why I added `this.keyboard.close();`  line of code at last.

> If you provide a full repo that reproduces the problem, I'm happy to look at it further. You don't need to make your whole app available on github, of course, just a sample app that reproduces the issue.
Yes, I can do that. I will create repo of a sample app.

**Comment by crookedneighbor** [comment]
@swapnilhpatil Any update on this?

**Comment by swapnilhpatil** [comment]
I was not available last week. within three days, I will provide a repo. I apologize for replying late.

**Comment by swapnilhpatil** [comment]
Hi @crookedneighbor ,
I created a repo of implemented lines of code used in my project. Here is the link  [https://github.com/swapnilhpatil/IonicBraintreePaymentSystemIntegration](url)

**Comment by crookedneighbor** [comment]
Had to make a few updates so that it would run in the xcode simulator: https://github.com/swapnilhpatil/IonicBraintreePaymentSystemIntegration/pull/1

I was able to run it in the xcode simulator without issue. Having a little trouble getting it to run on my actual device.

Are you having issues in _both_ the simulator and a real device? Or just a real device?

**Comment by crookedneighbor** [comment]
Just ran it on my actual device with no issue. Can you try running the PR I made and see if you still have issues?

**Comment by crookedneighbor** [comment]
![img_86d5e9169097-1](https://user-images.githubusercontent.com/2916945/46234353-aac00d80-c33b-11e8-9022-1db050f84192.jpeg)

**Comment by swapnilhpatil** [comment]
> Are you having issues in _both_ the simulator and a real device? Or just a real device?

The issue is only occurring on the real device. On the simulator, App is working fine.

> 
> 
> Just ran it on my actual device with no issue. Can you try running the PR I made and see if you still have issues?
Yes, I will check the PR you made.

**Comment by swapnilhpatil** [comment]
Hi @crookedneighbor ,
After checking the PR you made, I updated the node package  "@ionic-native/braintree": "^4.15.0" because I had an older version in my project "^4.11.0", and added the Cordova plugin "cordova-plugin-ionic-webview": "^2.1.4".
Now, It is working as expected. If you want a video of the working application of payment system. I can post here.
Thanks for your help.

**Comment by crookedneighbor** [comment]
Glad to know it's working, no need to post a video. 

Makes sense that an older version of the ionic and cordova dependencies would have a bug involving iframes. Glad we were able to figure it out.
