### ISSUE TITLE
Brunch fails packaging latest release from npm

### ISSUE THREAD

**Issue by xadhoom** [braintree/braintree-web-drop-in#432]
### General information
* SDK/Library version: 1.13.0
* Build Environment: npm 5.6.0, node v8.94, brunch 2.10.17

### Issue description

Installed latest braintree-web-drop-in with "npm install" and now brunch fails compilation because of:
`error: Processing of node_modules/braintree-web-drop-in/dist/browser/dropin.js failed. Error: Could not load module '../../browser-detection' from '/home/matteo/test/assets/node_modules/braintree-web-drop-in/dist/browser'. Make sure the file actually exists.`

Previous release was ok. If I manually remove the `browser` key from `node_modules/braintree-web-drop-in/package.json` it works correctly.

Other packages that use the `browser` key in package.json are ok, so I don't think is a brunch issue?

**Comment by crookedneighbor** [comment]
We'll take a look, thanks.

**Comment by xadhoom** [comment]
> var dropin = require('braintree-web-drop-in/index.js')

confirmed, in this way is pulled in correctly.

**Comment by crookedneighbor** [comment]
So far I haven't found a way to solve this, but I've brought it up in an issue on the Brunch repo. https://github.com/brunch/brunch/issues/1618

**Comment by hgshoggins** [comment]
The same is happening with `browserify` and using
> var dropin = require('braintree-web-drop-in/index.js')

solved my issue!

**Comment by crookedneighbor** [comment]
I'm puzzled why browserify would have trouble with this. We use browserify to create the browser version, and I _thought_ browserify builds the files in such a way that they can be required again.

**Comment by hgshoggins** [comment]
I'm clearly not the expert here, here's my workflow, maybe it's flawed from the beginning:
- Here's my `test.js` file:
```javascript
var braintree = require('braintree-web');
var dropin = require('braintree-web-drop-in');
```
- Then I simply run:
```bash
browserify test.js
```
- And I get the following errors, either the first or the second one, randomly chosen:
```bash
Error: Cannot find module './load-stylesheet' from '/root/node_modules/braintree-web-drop-in/dist/browser'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```
or
```bash
Error: Cannot find module './load-script' from '/root/node_modules/braintree-web-drop-in/dist/browser'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

Sometimes it's about `./load-script`, sometimes it's `./load-stylesheet`.
As you suggested, I could overcome this issue with:
```javascript
var braintree = require('braintree-web');
var dropin = require('braintree-web-drop-in/index.js');
```
so it's not much of a big deal to me as I now have a workaround, but maybe this can help you understanding the specifics of `browserify` with my setup.
My `browserify` version is `16.5.0`.

**Comment by crookedneighbor** [comment]
I'm not doubting you, just very surprised. Definitely warrants investigation, so thanks for all the info.
