### ISSUE TITLE
Dynamically show and hide payment methods

### ISSUE THREAD

**Issue by pho3nixf1re** [braintree/braintree-web-drop-in#435]
### General information

* SDK/Library version: 1.0.4
* Environment: Sandbox
* Chrome on MacOs

### Issue description

I need to dynamically show or hide payment options based on various conditions. Unfortunately I cannot figure out how to update the configuration without completely unmounting (in React) the component and re-rendering it. I have tried the following calls:

- `instance.updateConfiguration('paypal', null)`
- `instance.updateConfiguration('paymentOptionPriority', ['card'])`

What is the recommended way to show and hide payment methods that does not require an entire re-render of the component (including all the teardowns, bindings, and un-bindings)?

**Comment by crookedneighbor** [comment]
This is not currently part of the functionality of Drop-in.

Can you explain your use case a little more? Why would you need to dynamically change which payment methods are shown?

As a workaround, since the elements are on the page, you have the ability to manipulate them. You can always remove and add them yourself. For example:

```js
var paymentOptionContainer = document.querySelector('[data-braintree-id="payment-options-container"]')
var cardOption = document.querySelector('.braintree-option.braintree-option__card')

paymentOptionContainer.removeChild(cardOption) // take it away
paymentOptionContainer.appendChild(cardOption) // put it back at the bottom of the list
```

**Comment by pho3nixf1re** [comment]
We are actually discussing if this is needed anymore as it might be a legacy hold-over from an earlier era. For now your suggestion is the approach I was going to take but it worried me that things could break in hard to find ways if I did that.

Our use case is that we didn't want to use paypal for certain kinds of purchases (recurring subscriptions) and the purchase options can be changed on the page that has the drop in UI. This renders fine when first mounted but once the drop in component is rendered I cannot actually change the configuration for which methods appear.

I'll close this issue and use the suggested workaround if needed. If the workaround does not work then I'll post back here for more discussion.
