### ISSUE TITLE
Document required values for CSP

### ISSUE THREAD

**Issue by dpolivy** [braintree/braintree-web-drop-in#442]
### General information

* SDK/Library version: 1.10.0 (old, I know)
* Environment: both

### Issue description

The [braintree-web](https://braintree.github.io/braintree-web/current/) documentation includes details on the necessary values to add to a CSP for it to work. However, this is not sufficient for the drop-in; I'm getting a number of CSP errors while using those values. Is it possible to provide a complete list of the required values to allow the drop-in to work with a strict CSP?

**Comment by crookedneighbor** [comment]
Hi, you're absolutely right that we missed adding that to the docs. I've opened a PR to add it: https://github.com/braintree/braintree-web-drop-in/pull/443

I _think_ I covered everything, but it'd be great if you could try it out (reproduced below):

|             | Sandbox                                                                                                                   | Production                                                                                                            |
|-------------|---------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| script-src  | js.braintreegateway.com<br/>assets.braintreegateway.com<br/>www.paypalobjects.com<br/>c.paypal.com<br/>pay.google.com     | js.braintreegateway.com<br/>assets.braintreegateway.com<br/>www.paypalobjects.com<br/>c.paypal.com<br/>pay.google.com |
| style-src   | 'unsafe-inline'<br/>assets.braintreegateway.com                                                                           | 'unsafe-inline'<br/>assets.braintreegateway.com                                                                       |
| img-src     | assets.braintreegateway.com<br/>checkout.paypal.com<br/>data:                                                             | assets.braintreegateway.com<br/>checkout.paypal.com<br/>data:                                                         |
| child-src   | assets.braintreegateway.com<br/>c.paypal.com                                                                              | assets.braintreegateway.com<br/>c.paypal.com                                                                          |
| frame-src   | assets.braintreegateway.com<br/>c.paypal.com<br/>*.cardinalcommerce.com                                                   | assets.braintreegateway.com<br/>c.paypal.com<br/>*.cardinalcommerce.com                                               |
| connect-src | api.sandbox.braintreegateway.com<br/>client-analytics.sandbox.braintreegateway.com<br/>*.braintree-api.com                | api.braintreegateway.com<br/>client-analytics.braintreegateway.com<br/>*.braintree-api.com                            |

 Including `www.paypalobjects.com` and `c.paypal.com` in `script-src`, `img-src`, `child-src` and `frame-src` are only required if you are using [PayPal](http://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~paypalCreateOptions).
Including `pay.google.com` in `script-src` is only required if you are using [Google Pay](http://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~googlePayCreateOptions).
Including `*.cardinalcommerce.com` in `frame-src` is only required if you are using [3D Secure](http://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~threeDSecureOptions).

**Comment by dpolivy** [comment]
With the above, I'm still getting the following errors:

````
[Report Only] Refused to load the script 'https://www.paypal.com/tagmanager/pptm.js?id=grenache.lan&t=xo' because it violates the following Content Security Policy directive

[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: 

[Report Only] Refused to connect to 'https://www.paypal.com/xoplatform/logger/api/logger' because it violates the following Content Security Policy directive:

[Report Only] Refused to frame 'https://www.sandbox.paypal.com/' because it violates the following Content Security Policy directive: 

[Report Only] Refused to connect to 'https://www.paypal.com/xoplatform/logger/api/logger' because it violates the following Content Security Policy directive: 

[Report Only] Refused to load the image 'https://b.stats.paypal.com/counter.cgi?i=127.0.0.1&p=b045c85cafed47a5df094557b1a730ee&t=1539361409.135&a=14' because it violates the following Content Security Policy directive

[Report Only] Refused to load the image 'https://slc.stats.paypal.com/counter2.cgi' because it violates the following Content Security Policy directive
````

**Comment by crookedneighbor** [comment]
I see, many paypal subdomains. Should probably just change `c.paypal.com` to `*.paypal.com` in that case 😞 

I'm going to see if I can dig up some PayPal documentation for using content security policies with checkout.js that we can link to.

If no documentation exists, I'll see about fixing these up.

**Comment by dpolivy** [comment]
Yes, changing `c.paypal.com` to `*.paypal.com` for `script-src`, `frame-src` and `child-src` helps. It also needs to be added to `image-src`, and `www.paypal.com` needs to be added to `connect-src`. I think that does the trick, although I am still getting an inline script error. Stack trace for that (though not sure how helpful it is) is:

````
K @ dom.js:191
(anonymous) @ index.js:1162
p @ promise.js:156
e.dispatch @ promise.js:147
e.then @ promise.js:240
(anonymous) @ index.js:1138
e.try @ promise.js:393
n.createPrerenderTemplate @ index.js:1125
openContainer:memoized @ decorators.js:13
(anonymous) @ index.js:167
p @ promise.js:156
e.dispatch @ promise.js:147
e.then @ promise.js:240
(anonymous) @ index.js:166
e.try @ promise.js:393
n.tryInit @ index.js:1283
n.render @ index.js:115
(anonymous) @ index.js:488
e.try @ promise.js:393
n.render @ index.js:487
callOriginal @ util.js:338
(anonymous) @ hacks.js:170
e.(anonymous function) @ util.js:334
(anonymous) @ dropin.min.js:8
````

**Comment by dpolivy** [comment]
@crookedneighbor Thanks for the commit! It looks like there may be some formatting issues with `frame-src` and `connect-src`, though.

Also, I don't think this addresses the inline script error I mentioned above. I think that may be this issue: https://github.com/paypal/paypal-checkout/issues/447. It'd be great if you could escalate that internally.

**Comment by crookedneighbor** [comment]
That's understood, but a requirement for checkout.js, so it must be included. There's a note about how it's only required for checkout.js.

Best course of action is to keep commenting on that issue. I've subscribed to the issue, so I can update the CSP if/when it gets resolved.

**Comment by dpolivy** [comment]
Looks like PayPal is working on a new Payments SDK that will accept a nonce parameter to address the CSP issue. When do you think that might make its way into the Braintree JS SDK/drop-in?

**Comment by crookedneighbor** [comment]
We've been working with the PayPal team on the Payments SDK. When it's in general availability, we'll make the switch, unless it would involve a breaking change to integrate, then we'll have to wait till a new major version of Drop-in to incorporate it.

**Comment by fl3xman** [comment]
I have problem with CSP `connect` to AWS API gateway of `https://kg668dbov0.execute-api.us-east-1.amazonaws.com/prod/log` which is part of `https://songbird.cardinalcommerce.com/edge/v1/miva.js.map`

**Comment by crookedneighbor** [comment]
@fl3xman I've brought it up to Cardinal, our 3DS provider. to have them set up that endpoint under a `cardinalcommerce.com` domain. In the meantime, you can safely ignore those calls, as they are just logs and should not affect your ability to process transactions.
