### ISSUE TITLE
Merge request hungarian translation

### ISSUE THREAD

**Issue by alephlg** [braintree/braintree-web-drop-in#445]
### General information

https://github.com/braintree/braintree-web-drop-in/pull/444
* SDK/Library version: master
* Environment: Production

### Issue description

I create a new supported language to card accepting frontend.
Could you please merge to master or send me a feedback.

**Comment by crookedneighbor** [comment]
Closing, see https://github.com/braintree/braintree-web-drop-in/pull/444#issuecomment-429884398
