### ISSUE TITLE
Braintree drop-in stopped showing client's saved payment methods

### ISSUE THREAD

**Issue by Celebes** [braintree/braintree-web-drop-in#446]
### General information

* SDK/Library version: 
"braintree-web": "^3.37.0",
"braintree-web-drop-in": "^1.13.0",

* Environment: Sandbox 
* Browser and OS: FireFox 62.0.3, Chrome  70.0.3538.67, Windows 7

### Issue description

1) I create user in Braintree with payment method
2) I successfully download client token using client ID
3) I successfully setup dropin using client ID, so it should show payment method from step 1), but it shows only fresh form to input payment methods (it doesn't remember anything)

The funny thing is - it worked yesterday. I didn't change anything and it stopped today suddenly. I tried running my earlier projects where it also worked, and it doesn't work today. Some problem on your servers?

**Comment by crookedneighbor** [comment]
Thanks for the report, we're looking into it.

**Comment by crookedneighbor** [comment]
I've confirmed there's an issue in Sandbox with client token generation, where the customer id is not being encoded.

This is not happening in Production.

**Comment by crookedneighbor** [comment]
This should now be fixed in Sandbox.
