### ISSUE TITLE
Customer specified in authorization fingerprint does not exist

### ISSUE THREAD

**Issue by straube** [braintree/braintree-web-drop-in#449]
### General information

* SDK/Library version: 1.13.0
* Environment: Sandbox
* Browser and OS: Chrome 70.0.3538.77 (Official Build) (64-bit) on MacOS 10.14 (18A391)

### Issue description

I'm building a web application on top of React that uses the Drop-in UI. When loading the fields into the app, I'm getting the following error:

> Customer specified in authorization fingerprint does not exist

The message is returned from `https://api.sandbox.braintreegateway.com/merchants/[ID]/client_api/v1/payment_methods`.

Does anyone know what this error means? I googled for it but didn't find any result for that exact phrase.

P.S.: I guess that `[ID]` in the URL is some kind of token, so I omitted it.

**Comment by crookedneighbor** [comment]
The `id` is just your merchant public id, it's fine to include it. 

I would only expect you to see that error if you had created a client token with a customer id for a customer that exists, but then deleted the customer before loading the Drop-in. (or attempting to request a payment method nonce)

If that doesn't sound like what you did, can you give us more information about how you are setting up Drop-in? Can you share your client and server code?

**Comment by straube** [comment]
This is the client-side code:

````
import dropin from 'braintree-web-drop-in' ;

const renderDropInFields = (token) => {
    return dropin.create({
        authorization: token,
        container: '#braintree-dropin',
        card: {
            cardholderName: true,
        },
        paypal: {
            flow: 'vault',
        },
        googlePay: {
            merchantId: 'merchant-id-from-google', // Placeholder ID
            transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPrice: '123.45',
                currencyCode: 'USD',
            },
        },
    }).then((instance) => {
        client = instance;
    });
};
````

I retrieve the token from an internal API. I'm contacting our back end team to get details on how they generate the client token on the server side.

**Comment by crookedneighbor** [comment]
@straube Any update from you server side team?

**Comment by straube** [comment]
@crookedneighbor It seems they just found an issue on our back end. I'm closing this one for now. Thank you for your time.
