### ISSUE TITLE
Support requiredBillingContactFields for ApplePay

### ISSUE THREAD

**Issue by nathanlenz** [braintree/braintree-web-drop-in#452]
### General information

* SDK/Library version: 3.35.0
* Environment: Sandbox

### Issue description

When using ApplePay, I need to be able to use requiredBillingContactFields to request the name, address and email so that the customer does not have to type in their contact information.

When this is added to the paymentRequest:
```
  requiredBillingContactFields: [
                        "name", "postalAddress", "email"
                    ]
```
Apple Pay does inform the customer that they will provide it. However, the payload returned to the callback does not contain the information.

Side note: the Google Pay feature does support this functionality via Drop In UI.

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll get this added.

**Comment by dpolivy** [comment]
+1 to this. I just learned that we're getting charged $0.10 per authorization from VISA for not passing the billing postal code with the transaction, and as I investigate this it seems that I can't even get the data back to do so.

**Comment by crookedneighbor** [comment]
Hmmm... looking at the view, I'd expect it to be added here: https://github.com/braintree/braintree-web-drop-in/blob/2f94461ecfaef30075f28e07d3e537b4d48965be/src/views/payment-sheet-views/apple-pay-view.js#L77

And the tests seem to indicate that too: https://github.com/braintree/braintree-web-drop-in/blob/master/test/unit/views/payment-sheet-views/apple-pay-view.js#L284-L306

I'll need to do some investigation tomorrow to confirm. We may be pulling the wrong property off the event or something.

**Comment by dpolivy** [comment]
I'm not seeing that property on the payload. I just see:

````
{
   binData: {...}, // just a bunch of fields set to 'Unknown'
   details: {...}, // just the card type, cardholder name, last two of card
   deviceData: ...,
   nonce: ....,
   type: "ApplePayCard"
}
````

**Comment by dpolivy** [comment]
@crookedneighbor You probably know this code better than I, but I can take a quick stab at a PR to move things along more quickly.

**Comment by dpolivy** [comment]
OK, PR submitted. This seems to do the trick with my testing -- the billingContact data is now available on the payload. I followed the Google Pay property naming convention, but if you prefer to use something else, feel free to modify. Let me know once you can get an official build out for this.

**Comment by crookedneighbor** [comment]
This should be out now in v1.15.0
