### ISSUE TITLE
Slovak Localization

### ISSUE THREAD

**Issue by matejLukasik** [braintree/braintree-web-drop-in#455]
What needs to happen for you to provide Slovak language localization? Would you accept the localization sk_SK.js file as an open-source contribution from me?

**Comment by crookedneighbor** [comment]
Currently, we can only officially support [languages that the PayPal flow supports](https://developer.paypal.com/docs/integration/direct/rest/locale-codes/#supported-locale-codes).

You can supply your own translations during the Drop-in creation though. See our [reference documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#create-examples) and see the `Use your own translations` example.
