### ISSUE TITLE
Maintain form opened

### ISSUE THREAD

**Issue by carlos12silva94** [braintree/braintree-web-drop-in#458]
Why it is not possible to maintain the form opened when i have already added a payment method?

For example, i enter the page and i see previous added cards and the button to add another one, but I want to see the form already ready to be filled

**Comment by crookedneighbor** [comment]
So I understand correctly, are you asking for something like this:

<img width="587" alt="screen shot 2018-11-26 at 10 36 08 am" src="https://user-images.githubusercontent.com/2916945/49028064-289b6c00-f167-11e8-9d9c-76c296d6ca69.png">

Or do you mean something else?

**Comment by carlos12silva94** [comment]
that's it

**Comment by carlos12silva94** [comment]
Because with css, the form may be opened but you cant submit it. Also I want to hide the already added cards and only show them in another page. So, everytime I enter my page i want to see the form to add a new card. Also, after adding, for example, my first card, I want to be ready to submit a second one, and dont want to be forced to click in "choose another way to pay" to see the form, because that's not so intuitive for the user

**Comment by crookedneighbor** [comment]
Sounds like you want more full control over the look and flow of the credit card form. In that case, I'd recommend using [Hosted Fields](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v3), which is what Drop-in is using to render the form. This will give you complete control over how the card form is presented. 

Alternatively, you can follow the instructions to fork and modify Drop-in found here: https://github.com/braintree/braintree-web-drop-in#customization

**Comment by carlos12silva94** [comment]
That's what i'm using right now: But still think that drop-in should allow that :)
