### ISSUE TITLE
Venmo drop in not shown on page

### ISSUE THREAD

**Issue by neowithyou** [braintree/braintree-web-drop-in#460]
### General information

* SDK/Library version: .Net SDK 4.7.0.0, javascript SDK 1.14.1
* Environment:  Sandbox 
* Browser and OS  Chrome 70.0.3538.110 (64-bit) on Windows 1803

### Issue description

I followed [enable Venmo in your sandbox Control Panel.](https://articles.braintreepayments.com/guides/payment-methods/venmo#testing) to enable Venmo payment drop in, and followed  https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#venmo to create drop in, but venmo is not shown on page. My guess is the token that I generate from SDK does not support Venmo?
The client token I used was "eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiI4NzE3ZjFiMmZlZGMwZWVkMmZlMjc1YTRiNDg4NzUwNDJkN2EyZTA5YWU0NTFmODY0NTE4OTcxMDhlZjEzMGE2fGNyZWF0ZWRfYXQ9MjAxOC0xMi0wNFQyMDoxMDowOS44MTc3MzQ5MzUrMDAwMFx1MDAyNm1lcmNoYW50X2lkPTJ4aG5tZmJzZHh0dDZwa2hcdTAwMjZwdWJsaWNfa2V5PTk2d3dibWIzaDd0eGc4YnkiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMnhobm1mYnNkeHR0NnBraC9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJncmFwaFFMIjp7InVybCI6Imh0dHBzOi8vcGF5bWVudHMuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbS9ncmFwaHFsIiwiZGF0ZSI6IjIwMTgtMDUtMDgifSwiY2hhbGxlbmdlcyI6WyJjdnYiLCJwb3N0YWxfY29kZSJdLCJlbnZpcm9ubWVudCI6InNhbmRib3giLCJjbGllbnRBcGlVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMnhobm1mYnNkeHR0NnBraC9jbGllbnRfYXBpIiwiYXNzZXRzVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhdXRoVXJsIjoiaHR0cHM6Ly9hdXRoLnZlbm1vLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhbmFseXRpY3MiOnsidXJsIjoiaHR0cHM6Ly9vcmlnaW4tYW5hbHl0aWNzLXNhbmQuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbS8yeGhubWZic2R4dHQ2cGtoIn0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInBheXBhbEVuYWJsZWQiOmZhbHNlLCJtZXJjaGFudElkIjoiMnhobm1mYnNkeHR0NnBraCIsInZlbm1vIjoib2ZmIiwiYXBwbGVQYXkiOnsic3RhdHVzIjoibW9jayIsImNvdW50cnlDb2RlIjoiVVMiLCJjdXJyZW5jeUNvZGUiOiJVU0QiLCJtZXJjaGFudElkZW50aWZpZXIiOiJtZXJjaGFudC5jb20uc3d5Y2hhcHAuc3d5Y2hhcHAuaW50ZXJhY3QiLCJzdXBwb3J0ZWROZXR3b3JrcyI6WyJ2aXNhIiwibWFzdGVyY2FyZCIsImFtZXgiLCJkaXNjb3ZlciJdfX0=".
Could anyone help me to solve the problem, thank you in advance.

**Comment by crookedneighbor** [comment]
Venmo is only available on mobile browsers, so it makes sense that you are not seeing it on Desktop Chrome.

I checked your authorization and you are enabled for Venmo, just need to load Drop-in within iOS Safari or Android Chrome :)
