### ISSUE TITLE
3D Secure with several currencies 

### ISSUE THREAD

**Issue by timbertlt** [braintree/braintree-web-drop-in#466]
### General information

* SDK/Library version: 1.14.1
* Environment: any
* Browser and OS: any

### Issue description

I'm implementing 3D secure support. In production we have two currencies enabled (EUR/USD), linked to two merchant accounts. As described in documentation to enable 3D secure I should use dropin.create with 3D secure option:
braintree.dropin.create ({
  authorization: 'CLIENT_AUTHORIZATION',
  container: '#dropin-container',
  threeDSecure: {
    amount: '10.00'
  }
}, callback);
But how can I specify currency or merchant account for this transaction?

**Comment by crookedneighbor** [comment]
When you generate a client token, you can specify a merchant account id. The currency on that merchant account will be used.

See https://developers.braintreepayments.com/reference/request/client-token/generate/#merchant_account_id
