### ISSUE TITLE
Unable to delete cards if multiple cards have been added

### ISSUE THREAD

**Issue by andismith** [braintree/braintree-web-drop-in#468]
### General information

* SDK/Library version: 1.14.1
* Environment: Sandbox
* Browser and OS: Chrome 71/Safari

### Issue description

If you add multiple cards to the web drop in, and then try to delete one, it is not removed from the list.

- Add multiple (2 or more) cards to the web drop in.
  - We have used the following numbers for testing: `4242424242424242` and `4111111111111111`
- Note that these cards appear in the list in the web drop in.
- Remove a card from the list by clicking the 'Edit' button and the red X.
- Note that the card still appears in the list. The list may have reordered if the card selected for deletion was not the most recent.
- Attempting to pay with the deleted card results in a failed payment.

We are not using subscription payments. No errors are returned in the console. Braintree returns 200 OK for all requests.

**Comment by crookedneighbor** [comment]
I was not able to reproduce the issue.

![delete](https://user-images.githubusercontent.com/2916945/51692167-f6b95100-1fc1-11e9-9d89-eddba5729997.gif)

Are there any messages in the console? Any failed requests in the network tab?

**Comment by andismith** [comment]
Thanks for your assistance.

I cannot replicate this issue now either, which makes me suspect it might have been our Wifi connection in the office, which is poor at the best of times.

So I'm closing for now.
