### ISSUE TITLE
Deleting card shows weird gray box and "Undefined"

### ISSUE THREAD

**Issue by mohamedhafez** [braintree/braintree-web-drop-in#474]
### General information

* SDK/Library version: 1.15.0 (and earlier, starting with at least 1.13.0)
* Environment: both
* Browser and OS: all browsers

### Issue description
If a card has been used with a subscription/recurring payment before, then even after the subscription is cancelled, if you have the Vault Manager enabled and click 'Edit' in the drop in UI and try to delete it, it displays a weird gray box and an "Undefined" message above the red X, as shown in the screenshot below:

<img width="1280" alt="bug" src="https://user-images.githubusercontent.com/1011417/52170192-c9c01900-26fa-11e9-8d8e-7dd19c44d3e9.png">

It still works just fine, but it would be nice if it didn't look buggy. Thanks!

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll get this fixed up.

**Comment by crookedneighbor** [comment]
Fixed in 1.16.0
