### ISSUE TITLE
Cancelling deletion of payment in vault fires paymentMethodRequestable (while it should not)

### ISSUE THREAD

**Issue by pontikis** [braintree/braintree-web-drop-in#477]
### General information

- braintree-web-drop-in 1.16.0
- Sandbox
- Chrome Version 72.0.3626.109 (Official Build) (64-bit) 
- Linux Xubuntu 16.04.5 LTS

### Issue description

Hello!

Congrats for this great work!

I use ``paymentMethodRequestable`` and ``noPaymentMethodRequestable`` to toggle [Pay now] button.

But, when you press Cancel trying to delete of payment in vault, ``paymentMethodRequestable`` is fired (while it should not, I suppose).

See the gif animation and the Console.

Thanks!

![cancel_delete_payment_in_vault](https://user-images.githubusercontent.com/814012/52880929-f731ab80-316b-11e9-9e18-f42b725fe8ca.gif)

**Comment by crookedneighbor** [comment]
Yep, that's definitely a bug. Thanks for the report and thorough explanation, we'll get that fixed.

**Comment by hollabaq86** [comment]
Hi @pontikis- we just released version 1.17.0 which includes a fix to this issue.
