### ISSUE TITLE
All payment options failed to load

### ISSUE THREAD

**Issue by Thkasis** [braintree/braintree-web-drop-in#478]
### General information

* SDK/Library version:  1.16.0
* Environment: Sandbox
* Browser and OS : Tried both on Chrome 72.0.3626.109 (64bit) and Mozilla Firefox 

### Issue description
Adding dropping, providing token from server, all goes fine except I get the error below when trying to render the drop in on client. 

> message: "All payment options failed to load."
> name: "DropinError"

Below is the snippet I use to add the droping, I have added the script in my <head> and all seems fine. 
```
const container = this.$.containerId; //this returns the node
braintree.dropin.create({
            authorization: "ValueOfTokenFromServer",
            container: container 
        }, function(createErr, instance) {
            if (createErr) console.log(`error `, createErr);
        
        });

```

**Comment by crookedneighbor** [comment]
Can you provide a github repo or other code sample that reproduces the problem you are experiencing?

I suspect the client token that you are generating does not have permission to process credit cards.

There's a sandbox demo here that's working just fine: https://braintree.github.io/braintree-web-drop-in/

**Comment by Thkasis** [comment]
My apologies for getting back with delay. I resolved the issue and problem was on my part not setting up the Braintree correctly. It would be nice if support for shadow dom would be added in case of rendering the element in web components. Thanks for all the good work. I close this issue.

**Comment by crookedneighbor** [comment]
The reason it doesn't seem to work with the shadow dom is because it relies on some interaction between iframes on a shared braintree domain to coordinate the tokenization of the credit card fields. That behavior is eliminated when stuff inside a shadow dom. 

You can however insert Drop-in into a shadow dom, like this: https://codepen.io/braintree/pen/YgXaoP

```html
<div id="braintree-dropin">
  <div id="dropin-container"></div>
</div>

<template id="braintree-dropin-template">
  <form action="/" id="my-sample-form" method="post">
    
    <content select="#dropin-container"></content>

    <input id="submit" type="submit" value="Pay" />
  </form>
</template>
```

```js
// setup shadow dom
var dropinContainer = document.querySelector("#braintree-dropin");
var shadow = dropinContainer.createShadowRoot();
var template = document.querySelector("#braintree-dropin-template");

shadow.appendChild(template.content);

template.remove();

// setup bt
braintree.dropin.create({
  authorization: 'sandbox_f252zhq7_hh4cpc39zq4rgjcg',
  container: '#dropin-container',
  paypal: {
    flow: 'vault'
  }
}, function(dropinErr, dropin) {
  if (dropinErr) {
    console.error(dropinErr);
    return;
  }

  var btn = shadow.querySelector('#submit');

  btn.addEventListener('click', function(event) {
    event.preventDefault();

    dropin.requestPaymentMethod(function(err, payload) {
      if (err) {
        console.error(err);
      } else {
        console.log('Send payload.nonce to server: ' + payload.nonce);
      }
    });
  });
});
```
