### ISSUE TITLE
Braintree drop in ui not sending back the call back in case of success

### ISSUE THREAD

**Issue by suraj728** [braintree/braintree-web-drop-in#488]
I am trying to integrate brain tree drop in ui in html and javascript.

the issue i am facing is that the requestpaymentmethod is not giving the call back in case of success. however it send call back when there is any error.

the code is 

    braintree.dropin.create(
		{
			authorization: CLIENT_TOKEN_FROM_SERVER,
			container: '#dropin-container'
		},
		
		function (createErr, instance)
		{
			button.addEventListener('click', function ()
			{
				var avlbl = instance.isPaymentMethodRequestable();
					
				var promise = instance.requestPaymentMethod();
				
				setTimeout(function() {
					instance.requestPaymentMethod(
					function (err, payload)
					{
						if(err)
							alert(err.message);
						else
							alert("paylod nonce received");
					});
				},'200');
			});
		});

**Comment by hollabaq86** [comment]
Hi @suraj728- please contact [Braintree Support](https://help.braintreepayments.com/), who can assist in troubleshooting your issue.
