### ISSUE TITLE
Strange dependency on the package "8"

### ISSUE THREAD

**Issue by raRaRa** [braintree/braintree-web-drop-in#490]
I upgraded `braintree-web-drop-in` today and noticed a new dependency on a package called '8'.

Ref: https://github.com/braintree/braintree-web/issues/422
8: https://www.npmjs.com/package/8

**Comment by crookedneighbor** [comment]
Closing this as a duplicate of the issue you posted on the braintree-web repo: https://github.com/braintree/braintree-web/issues/422
