### ISSUE TITLE
Vault manager (delete card) has teeny font-size with Bootstrap 3

### ISSUE THREAD

**Issue by sbull** [braintree/braintree-web-drop-in#497]
### General information

* SDK/Library version: 1.17.2
* Environment: Production
* Browser and OS: Chrome 72.0.3626.121 on Windows 10

### Issue description

When using Bootstrap 3.3.7 on my site, the Vault Manager feature has very tiny text in the delete-confirmation dialog. This is because Bootstrap sets
`html { font-size: 10px; }`
and Braintree sets
`.braintree-delete-confirmation { font-size: .85rem; }`

Maybe the `rem` can be replaced? It sounds like this was addressed for other issues in the Changelog for 1.9.1, "Fixes styling applied by frameworks like Bootstrap", but perhaps that wasn't font-size related.

![image](https://user-images.githubusercontent.com/1115369/56405791-c0871880-6222-11e9-9e7c-9ef27abd8581.png)

**Comment by demerino** [comment]
@sbull Thanks for raising this issue. We'll take a look at the styling and verify that it works correctly.
