### ISSUE TITLE
Access expirationDate field value

### ISSUE THREAD

**Issue by sl0thentr0py** [braintree/braintree-web-drop-in#500]
### General information

* SDK/Library version: 1.17.2
* Environment: Sandbox
* Browser and OS: Chromium Version 74.0.3729.108 (Official Build) Arch Linux (64-bit)

### Issue description

I would like to store the `expirationDate` field on our server, but it's not present in `cardPaymentMethodPayload`. Is there an easy way to access the value stored in this field so I can store it before doing the tokenization?

**Comment by demerino** [comment]
The Client SDKs do not expose the expiration date. But you should be able to get that information on the server side from a payment method token: https://developers.braintreepayments.com/reference/response/credit-card/ruby#expiration_date
