### ISSUE TITLE
Problem with PayPal add button

### ISSUE THREAD

**Issue by delphiy** [braintree/braintree-web-drop-in#507]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.18.0/js/dropin.min.js
* Environment: Sandbox
* Browser and OS: Chrome   on MacOS 10.13.6

### Issue description
When I click choose other payment method and choose PayPal , Paypal windows appear and disappear 
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
logger.js:63 ppxo_no_token_passed_to_payment Objectcountry: "US"env: "production"host: "localhost:8888"lang: "en"pageID: "b69745c40c"path: "/nile-river-restaurant/checkout.php"prev_corr_ids: ""referer: "localhost:8888"timestamp: 1558184783537uid: "8b786f13ed_geztumbshiytm"ver: "4.0.268"windowID: "1f633ddd05"__proto__: Object
A @ logger.js:63

**Comment by crookedneighbor** [comment]
This sounds to me like you have something wrong in your PayPal configuration. What does your `paypal` configuration look like?

**Comment by delphiy** [comment]
Hi,
Thanks for your comment , I have solved the problem . It was linked to wrong sandbox Paypal account

**Comment by steunix** [comment]
Hi,
I have the very same error.

The code to initialize dropin:

braintree.dropin.create({
            // Insert your tokenization key here
            authorization: '<omitted>',
            container: '#dropin-container',
            locale: "de_DE",
            paypal: {
              flow: "vault",
            }
          }, function (createErr, instance) {
...

**Comment by Selvdrap** [comment]
@delphiy what was your problem with sandbox account? 

I'm getting the same error although the paypal payment works with Tokenization Key. I need to use a client token because I'm trying to implement 3D-secure.

**Comment by crookedneighbor** [comment]
@Selvdrap please reach out to our support team for assistance: https://help.braintreepayments.com/

**Comment by Selvdrap** [comment]
> @Selvdrap please reach out to our support team for assistance: https://help.braintreepayments.com/

I managed to solve it on my own. The issue was due to passing `merchantId` instead of `merchantAccountId` to generate function.

**Comment by juanmirocks** [comment]
I had the same problem and again the only issue was that my (sandobox) PayPal credentials were wrong.

For future readers, make sure to use the credentials of the API Credentials --> Rest App 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/102431/110795406-15990100-8277-11eb-8747-4cc5e7599671.png">
