### ISSUE TITLE
ApplePay option insists that 'Add a supported card to your Apple Pay wallet.'

### ISSUE THREAD

**Issue by Cookizza** [braintree/braintree-web-drop-in#522]
### General information

* SDK/Library version: JS v3
* Environment: sandbox
* Browser and OS: all browsers that support apple pay

### Issue description

I am trying to get ApplePay working with the web dropin using JS SDK v3.

I have setup the certificates in the apple portal, as well as verifying the domain with apple.

However, even with 5 different cards in my apple wallet, the dropin says:

> Add a supported card to your Apple Pay wallet.

![image](https://user-images.githubusercontent.com/1787216/60670571-f3779a80-9e68-11e9-8f56-2f5096e799d5.png)

My configuration object is simple:

     dropin.create({
            authorization: r.data.token,
            locale: 'en_GB',
            threeDSecureOptions: {
              amount: parseFloat(this.data.amount)
            },
            card: {},
            paypal: {
              flow: 'checkout',
              amount: parseFloat(this.data.amount),
              currency: 'GBP',
              commit: false
            },
            applePay: {
              displayName: 'My Store',
              paymentRequest: {
                countryCode: 'GB',
                supportedNetworks: ['amex', 'visa'],
                currencyCode: 'GBP',
                total: [
                  {
                    label: 'Payment for store',
                    amount: parseFloat(this.data.amount).toString()
                  }
                ]
              }
            },
            googlePay: {
              transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPrice: parseFloat(this.data.amount),
                currencyCode: 'GBP'
              }
            },
            container: '#dropin-container'
          }, this.braintreeInitCallback);

I get no errors in console :( According to the Braintree docs I should be able to test just fine using my live device.

Any help here is much appreciated as the portal support is very basic and there is clearly something technical going on here.

**Comment by Cookizza** [comment]
As an update, on safari I can get the popup, despite this message.

![image](https://user-images.githubusercontent.com/1787216/60671812-d98b8700-9e6b-11e9-82a6-69000482dbd2.png)

**Comment by Cookizza** [comment]
Ok I have managed to extract a response from apple:

    {
    "error": {
        "message": "Invalid validation URL for sandbox (make sure you are logged into an iTunes Connect sandbox tester account, see: https://developer.apple.com/support/apple-pay-sandbox/)"
    },
    "fieldErrors": []
}

**Comment by Cookizza** [comment]
To anyone finding this from google.

Ignore Braintree's documentation, you MUST use the Apple test accounts and test cards to test your Apple Pay setup in the Drop in widget.

- Make an apple sandbox account
- Login to your device with the iCloud test account
- Verify the email of the sandbox account
- Add an Apple test card to your wallet
- TEST APPLE PAY

Nowhere does Braintree seem to say we should be following the Apple sandbox setup for testing the drop in.

**Comment by Epreuve** [comment]
The Drop-in guide in the docs calls out right away that you will need to complete the Apple Pay configuration steps before including Apple Pay in the Drop-in [here](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#apple-pay).  Then, [those docs](https://developers.braintreepayments.com/guides/apple-pay/configuration/javascript/v3) then call out in the first section that you do indeed need to setup the appropriate iCloud account type based on the environment (Sandbox/Production).  

If you were looking at an area of the docs where these steps weren't called out, please feel free to suggest clarification using the `Send Feedback` button at the bottom of the page.

**Comment by crookedneighbor** [comment]
Gonna re-open this, because I think it's worth investigating if we can send out a better message in the case of an environment mismatch.

> Ignore Braintree's documentation, you MUST use the Apple test accounts and test cards to test your Apple Pay setup in the Drop in widget.

Definitely point out the page where there is misleading or inaccurate info. We want to fix that!

**Comment by Cookizza** [comment]
Sorry for late reply,

Here is the page, paragraphs 2 and 3: https://developers.braintreepayments.com/guides/apple-pay/testing-go-live/php

At the time they read in a way that made me think Braintree ignored real card data in test mode and instead just populated the nonce with dummy info. I know the initial Apple pay dropin article states quite prominently that you need to be logged into a test icloud account, but nowhere (including apples own docs) clearly stated how to actually login to a test icloud - a process that was so unclear, but of course nothing to do with Braintree.

Perhaps it could be good to add a reference that you will need to add test apple credit card to a test icloud account via the wallet app to use Braintree apple pay in test mode.

Thanks so much for your help in this, and of course for the dropin - it's brilliant!

**Comment by crookedneighbor** [comment]
I've passed your feedback onto our docs team. Thanks!

**Comment by crookedneighbor** [comment]
A better error message will be emitted in a sandbox environment in the next release. Thanks for brining this to our attention!

**Comment by crookedneighbor** [comment]
This is out in v1.20.2

**Comment by Cookizza** [comment]
Awesome guys! Our gateway is now live and performing very well. Thanks so much for all you do.
