### ISSUE TITLE
Moving dropin around the page using .appendChild results in errors

### ISSUE THREAD

**Issue by saoudrizwan** [braintree/braintree-web-drop-in#528]
I'm trying to show the dropin in multiple places on the page. Instead of creating multiple dropins (is this even possible?) I just create one and hide it until the user wants to see it in a certain place, at which point I use .appendChild to move the dropin container div into the new div at this certain place. However the dropin doesn't let me input credit card details or select paypal payment.

Is there a recommended approach to showing the dropin in multiple locations on the page? Thanks

### General information

* SDK/Library version: 1.19.0
* Environment: Sandbox
* Chrome

### Issue description
Chrome logs
```
Uncaught Error: No handler found for post message: zoid_init from...
```

**Comment by saoudrizwan** [comment]
I ended up having to teardown and recreate the dropin anytime the user wants to see the payment form at different parts of the page. So there's only one dropin on the page which is good, but now there's a loading period the user has to wait.

Any advice on moving the dropin around would still be appreciated, but I'm closing this issue for now.

**Comment by crookedneighbor** [comment]
Forgot to follow up on this. Tearing down and recreating is the correct thing to do here. Simply moving it via `appendChild` will sever the post message connection to the iframes used by PayPal (which is why you were getting that error)
