### ISSUE TITLE
Custom translation, {{lastFourCardDigits}} not working

### ISSUE THREAD

**Issue by peter5slo** [braintree/braintree-web-drop-in#530]
### General information

* SDK/Library version: PHP library 3.40, Drop-in UI 1.19.0
* Environment: sandbox
* Browser and OS: tried latest Chrome and Firefox on OSX 10.12.6

### Issue description

If I include a custom translation into Drop-in UI configuration, {{lastFourCardDigits}} code in "endingIn" translation is not parsed.
If I omit this string in translation, it works - last 4 digits are displayed (displays default English text).

**Comment by crookedneighbor** [comment]
Works just fine for me in the demo page: 

```
https://braintree.github.io/braintree-web-drop-in/?translations={"endingIn":"This card ends in {{lastFourCardDigits}}"}
```

<img width="598" alt="Screen Shot 2019-07-25 at 1 01 06 PM" src="https://user-images.githubusercontent.com/2916945/61897251-4aa6e300-aedc-11e9-8b65-59d9ab6e5d1c.png">


Are you certain that `endingIn` and `{{lastFourCardDigits}}` were spelled correctly? That's the only reason I can see it not working.

Can you supply sample code or a demo app where it doesn't function?

**Comment by peter5slo** [comment]
You are correct, not a Drop-in UI bug, sorry!

If anyone else stumbles upon this weird issue - the template engine I use uses {} delimiters for its variables and the usual ways of putting the curly braces in a template apparently did not work if one put two braces one after another.  Tried many different ways but in the end the only one that worked was by putting entire braintree.dropin.create function in a separate JS file and call it via <script>.

Thanks for pointing me in the right direction!

**Comment by crookedneighbor** [comment]
:+1:
