### ISSUE TITLE
Issues handling non-ascii characters

### ISSUE THREAD

**Issue by lucasRolff** [braintree/braintree-web-drop-in#536]
### General information

* SDK/Library version: v1.19.0
* Environment: Sandbox and Production
* Browser and OS : Any browser and OS

### Issue description

With 3D-Secure 2.0, we're advised to send a `billingAddress` 'object', this object contains things such as given name, surname, address - however, someone came up with the idea to only accept printable ASCII characters in these fields, meaning anyone that lives in a country with letters being non-ascii (even with letters being in the "extended ascii") can apparently not complete orders with the drop-in UI due to the API call below only accepts ASCII.

```
https://api.sandbox.braintreegateway.com/merchants/XXXXXX/client_api/v1/payment_methods/XXXXXXX/three_d_secure/lookup
```

Supplying a non-ascii name, such as "Jørgen" will result in the message:

```
{"error":{"message":"Billing given name format is invalid."},"threeDSecureInfo":{"liabilityShifted":false,"liabilityShiftPossible":false}}
```

Braintree is able to create customers containing non-ascii characters (such as æ, ø, å, ü etc) - so I can't see why the lookup shouldn't support it.

In this case, what's the advised way of handling this? As far as I know, there's no standardized way to convert non-ascii to ascii in javascript (if anyone knows a library that does this.. please share!) - and from a 3DS integration perspective, what format does banks expect?

The `billingAddress` object is used for banks to determine whether there should be a challenge or not - so in case we have a bank with a customer that contains non-ascii characters, then, do they expect `Jorgen`, `joergen`, or what format is expected to be accepted?

To replicate the issue, simply use the codepen provided in the #480 issue, and change `Jane` to `Jørgen` and see stuff fail.

**Comment by crookedneighbor** [comment]
The 3DS spec requires there to be no non-ascii characters in the name fields: https://www.emvco.com/wp-content/plugins/pmpro-customizations/oy-getfile.php?u=/wp-content/uploads/documents/EMVCo_3DS_Spec_v220_122018.pdf (page 185)

![image (1)](https://user-images.githubusercontent.com/2916945/62489257-ed3c4d00-b78b-11e9-9064-ea9a79f250e4.png)

The appendix in that doc:
![image (2)](https://user-images.githubusercontent.com/2916945/62489287-00e7b380-b78c-11e9-8538-63e5eb76acdc.png)

We're in the process of updating our documentation to make this clearer. I'll keep this issue open until the documentation is updated.

**Comment by lucasRolff** [comment]
Great :) So, since this is a requirement, despite it's not enforced when creating cards using the PHP SDK (At least I have cards registered in Braintree with non-ascii), and the world issues cards with non-ascii characters, then once again, how is this going to be handled? What should we pass in case non-ascii characters are used? Additionally, being a non-javascript developer, do you or anyone else have a suggestion for a JS library that will handle cases like this then?

I'm curious how others will handle it, since we'll have to come up with an ascii-version of every possible non-ascii letter in the world.

However, looking at the migration guide, I guess I can just skip the whole `billingAddress` object, and then people will always get a challenge. That's easier until someone comes up with a unified library to handle those 99% of countries in the world that has names with non-ascii characters.

**Comment by hgshoggins** [comment]
If I'm correct, the `cardholderName` field is supposed to be the name that appears on the physical card, not the actual name of the bank account holder or so. If it's the case, then there are no other characters than ASCII, as it's always capital letters without accented characters.
At least that's the case for France, where accented characters in people's name are very common.

**Comment by lucasRolff** [comment]
@hgshoggins in denmark we write æ, ø, å on the card, which is non-ascii, but are a part of ascii-extended, which sadly isn't accepted by the 3ds implementation. It's easy to solve for a small set of characters, I can just string replace them, but then again, that being handled in drop-in would kinda be useful, or if someone knows a library, then at least it can be written in the "international representation" that is ascii compatible.

**Comment by hgshoggins** [comment]
So I was completely wrong, I understand this can be a real problem. I'm afraid the specs are simply english-centric, then.
I wonder how card verification should handle this. Does the verification pass when the "aæéø" word is compared to... what... "aaeeo", or will it just fail because there is no actual match?

**Comment by lucasRolff** [comment]
@hgshoggins - that's what's hard to check until banks actually put 3DS 2.0 into production .. So I guess we'll find out what happens, maybe it will be fixed in 3DS 3.0 in 10 years.

**Comment by lucasRolff** [comment]
A small update - I contacted the danish divisions of VISA and Mastercard - and they indeed confirmed that they use æ, ø and å and even é (e.g. if people e.g. are called René) when issuing cards - so both VISA and Mastercard apparently goes against their own rules.

**Comment by hgshoggins** [comment]
Early systems using ASCII only did not bother much, everything was in English, everywhere. It's amazing to think that nowadays extended character sets are still not that common, and almost _discarded_ when writing modern specs.

**Comment by lucasRolff** [comment]
I've been in contact with EMVCo, after they realized that it's quite common that cardholder schemes use UTF-8 in cardholder names, EMVCo will update their endpoints to support UTF-8.

The official reply:
> Hi,
> 
> The Character set of “cardholdername” will be updated from ASCII to UTF-8 in the next specification bulletin.
> 
> Please continue to visit the EMVCo website for further updates.
> 
> Kind regards,
> The 3DS team

**Comment by jayvisel2626** [comment]
Hi, any new updates on this issue please? recently we face same issue with 3DS where it rejected transaction due to non-ascii characters in billing address info.

**Comment by crookedneighbor** [comment]
OK, finally have an update here. The Braintree API should now be converting non-ascii characters from the billing name fields automatically, so this can be closed.

Definitely comment here if y'all are still experiencing issues.
