### ISSUE TITLE
Drop-in cardholder name field with differs from other fields

### ISSUE THREAD

**Issue by morungos** [braintree/braintree-web-drop-in#537]
### General information

* SDK/Library version: 1.19.0
* Environment: Sandbox
* Browser and OS Chrome 75.0.3770.142 (Official Build) (64-bit) on MacOS 10.14.6

### Issue description

When adding a cardholder name field to the drop-in UI, the width of the field is very different to all other fields. I can't even work out where the difference comes from in the CSS, so I can't easily see what to do to override it.

The attached screenshot shows this in action. Note that on smaller/responsive screens, this appears to be handled okay. So it only affects resolutions with a screen width >396pixels (on my environment). 

![image](https://user-images.githubusercontent.com/442090/62649409-d5e39800-b922-11e9-8ab9-3f4351a26388.png)

**Comment by morungos** [comment]
There are more styling issues that this when new fields are added like this. A second one, which does show when using smaller screens, is that fields can fall out of the bottom of the form. All seems fine without a cardholder name field, but if one is added, then fields start crossing over out of the bottom of the box. Validation error messages increase this spillover. 

Here's an example of this: 
![image](https://user-images.githubusercontent.com/442090/62655909-0a5e5080-b931-11e9-9767-4c78cbfc4d88.png)

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll add it to our backlog.

**Comment by crookedneighbor** [comment]
This is partially fixed with 1.25.0 (the cardholder name is now a hosted field instead of a regular input). The UI overflow issue is being tracked in 664, so I'm going to close this since that encompasses the more general problem of elements overflowing.
