### ISSUE TITLE
Local Payment Methods

### ISSUE THREAD

**Issue by MixMe** [braintree/braintree-web-drop-in#539]
Drop in is amazing, Local Payment Methods will be supported ?
https://developers.braintreepayments.com/guides/local-payment-methods/overview

**Comment by crookedneighbor** [comment]
This is not currently on our roadmap, but is in discussion. I'll leave this issue open so others that are interested in this being added to Drop-in can comment.

**Comment by sl0thentr0py** [comment]
We would also be interested in local EU wide methods (especially SEPA transfer).

**Comment by nickwinger** [comment]
we also need SEPA, also for subscriptions

**Comment by samuelgiles** [comment]
We'd also be interested in seeing this - We're considering forking the repo adding in support for this. The fallback and webhook flows involved in local payment methods do make it pretty fun to support so I can see why it hasn't been included so far.

**Comment by crookedneighbor** [comment]
It's mostly a matter of prioritization. We're juggling a lot of things right now, and adding local payments to Drop-in is in our backlog, but not at the top of it.

@samuelgiles If you're going to do the work anyway, feel free to open a PR. That'll go a long way to speeding up it's inclusion in Drop-in.

**Comment by wuspum** [comment]
Is it possible to use both dropin and local payments instances on same checkout? It seems that they conflict with each other
![image](https://user-images.githubusercontent.com/54791755/137304679-70dbb686-343c-466b-bcca-995868a919d4.png)

**Comment by pccooper** [comment]
Are there any updates on this? We are using Drop In and I've been asked to add Klarna, which I see is available as a Local Payment option, but how do I go about integrating this alongside Drop In?

If they are going to conflict and there are no plans to add this to Drop In then I guess my only option is to migrate to Hosted Fields, but I'd rather avoid that!

**Comment by diegodisepio** [comment]
Is it possible to estimate the time needed to release the integration between Drop-in UI and Local Payments?
Is it an active work in progress?

**Comment by pccooper** [comment]
@crookedneighbor, has there been any movement on this?

**Comment by hollabaq86** [comment]
👋 hey folks, going to close this issue as it's a feature request and not a 🐛, but it'll stay at the top of our repo's issues since it's pinned for future folks to find.

Please do not ping crookedneighbor, he does not work at PayPal anymore.

I don't have an ETA on if/when we'll add this to the Drop-In or when we'll have any updates. But this request has been registered with the right folks to get evaluated and prioritized. We're a small team with a big codebase to manage 😅 so we're doing our best to work through some of our outstanding requests.
