### ISSUE TITLE
Subscription / Recurring billing options for drop in ui

### ISSUE THREAD

**Issue by brandonburkett** [braintree/braintree-web-drop-in#545]
### General information

* SDK/Library version: 1.20.0
* Environment: Sandbox

### Issue description

Apologies in advance if this exists and I was unable to find it, but is there documentation around options to pass in for each payment type when using drop in ui for recurring billing?
- EX: PayPal flow vault vs checkout
- EX: card: vault.vulatedCard - true?
- EX appleplay: I did not see a vault option?

Note on the backend we are creating a new customer via braintree php sdk and using the returned payment method to create the subscription... but I was trying to nail down the options to pass into the braintree drop in ui specifically for recurring billing.

Thank you

**Comment by hollabaq86** [comment]
👋  @brandonburkett, our [reference documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create) should have everything you need. If you have any questions about getting your Drop-In integration up and running, please contact [Braintree Support](https://help.braintreepayments.com/).
