### ISSUE TITLE
Base.S3Writer: s3 client not initialized

### ISSUE THREAD

**Issue by Okar** [braintree/braintree-web-drop-in#558]
### General information

* SDK/Library version: 1.20.1
* Environment: Sandbox
* Browser and OS: Chrome 76.0.3809.132 (64-bit) on macOS 10.13.6

### Issue description

Console error after `requestPaymentMethod` from https://songbirdstag.cardinalcommerce.com/edge/v1/9a1cc817eb1b1f693268/5.9a1cc817eb1b1f693268.songbird.js

```
VM21594 5.9a1cc817eb1b1f693268.songbird.js:1 Base.S3Writer: s3 client not initialized
n.cerror @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
n.sendLogItemsConsole @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
i.sendBatch @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
i.log @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
t.log @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
t.error @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
logRouter @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
h @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:1
capture @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:12
capture @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:12
receiveMessage @ VM21595 10.9a1cc817eb1b1f693268.songbird.js:1
(anonymous) @ VM21594 5.9a1cc817eb1b1f693268.songbird.js:12
10:53:10.666 
```

No errors in the network tab, not sure why it would try to log to S3.

**Comment by crookedneighbor** [comment]
I was able to reproduce this. We'll pass this onto Cardinal, our underlying 3ds provider, but it doesn't look like it's interfering with verification. There are no changes needed to the sdk, so I'm going to close this. Thanks for pointing it out.
