### ISSUE TITLE
How to get cardholderName when setting the threeDSecure object

### ISSUE THREAD

**Issue by raRaRa** [braintree/braintree-web-drop-in#561]
Hey,

I have the `cardHolderName` set as required, and I want to use the name set in that field when calling `requestPaymentMethod` with the threeDSecure object. Is there a way to fetch the name from the dropIn instance?

**Comment by hollabaq86** [comment]
👋 @raRaRa, thanks for reaching out - When we added support for 3DS 2 to the Drop-In, we should have also included functionality that takes the value for `cardholderName` in our card-form and supplies it in the 3DS verification request. This is a miss on our part. I'm going to leave this issue open and we'll update when we're closer to releasing this functionality to the Drop-In library.

**Comment by raRaRa** [comment]
Great, thanks! It would also be great if we could add more optional fields that could help with 3DS.

**Comment by crookedneighbor** [comment]
Yep, that's the long term plan for Drop-in to support configurable customer info fields.
