### ISSUE TITLE
Dropin should automatically disable 3D Secure for non-credit card payment instruments

### ISSUE THREAD

**Issue by matohavo** [braintree/braintree-web-drop-in#562]
### General information

* SDK/Library version: 1.20.1
* Environment: Sandbox
* Browser and OS: Any

### Issue description

Currently, when dropin is initialized with 3D secure option enabled, it fails to verify paypal token for obvious reasons.
This behavior prevents its usage with multiple (non-card) payment methods with 3D secure enabled.

Unless I'm missing something, it would really make sense for drop-in to verify only card payment methods, because currently I can use drop-in only for gathering payment method tokens and  verifying it in next step with hosted fields flow mentioned in the docs.
This prevents the usage of fast flow (get payment method and verify it in one step) - I need to get payment method token and change the flow according to the method - verify or don't verify in the next step.

**Comment by crookedneighbor** [comment]
3ds doesn't verify for paypal payment methods. Only credit card ones:

https://github.com/braintree/braintree-web-drop-in/blob/a6151e0d819d06b53d16a95f6a78125f501e6b18/src/dropin.js#L697

Can you provide a staging site or reproducible example to show that Drop-in is attempting 3ds verification for non-card payment methods?

**Comment by matohavo** [comment]
You're correct - my mistake, it happened in hosted fields flow, where I should check if it is paypal token before trying to 3D verify.
Thank you

**Comment by crookedneighbor** [comment]
Im curious why you're integrating with both Drop-in and Hosted Fields, would love to hear more if you want to reach out to our support team at https://help.braintreepayments.com/ and reference this issue.
