### ISSUE TITLE
Braintree Dropin stop firing events after using 4000000000001125

### ISSUE THREAD

**Issue by vbarbarosh** [braintree/braintree-web-drop-in#563]
### General information

* SDK/Library version: dropin/1.20.1
* Environment: Sandbox
* Browser and OS: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

### Issue description

I've noticed that after credit card 4000000000001125 was stored in the vault, Drop-in stops firing 
 noPaymentMethodRequestable, paymentMethodRequestable, and paymentOptionSelected events.

In order to reproduce it:
1. Create a client token with customerId
2. Submit 4000000000001091 card
3. Submit 4000000000001125 card
4. Now, changing payment method in dropin will not fire any events

I also created [this codepen](https://codepen.io/vbarbarosh/pen/XWrLJVy?editors=1010) for reproducing this bug.

**Comment by hollabaq86** [comment]
👋 @vbarbarosh I believe the issue you've presented is the same as #499, could you confirm?

**Comment by vbarbarosh** [comment]
@hollabaq86 Yes, it seems to be the same issue.

**Comment by crookedneighbor** [comment]
Gonna close this duplicate. Feel free to subscribe to #499 for updates.

**Comment by crookedneighbor** [comment]
This is fixed in v1.22.1
