### ISSUE TITLE
3DS: Automatic fallback in case of "unsupported_card" response

### ISSUE THREAD

**Issue by fapdash** [braintree/braintree-web-drop-in#569]
### General information

* SDK/Library version: 1.20.3
* Environment: Production
* Browser and OS: 69.0.2 (64-bit) on Ubuntu 18.04

### Issue description

I'd expect the drop-in to automatically fall back to a normal payment request if the 3DS request returns "unsupported card". Or there at least being a way for us to tell the drop-in to behave this way. Is this functionality planned? Is there something in the backend that we can do to recover from this error without having the customer reenter their credit card to get a new nonce?

**Comment by crookedneighbor** [comment]
Can you provide steps to replicate what you're seeing, as well as your merchant ID so we can inspect the settings on your account?

**Comment by crookedneighbor** [comment]
If you don't want to share your merchant ID publicly, reach out to our support team: https://help.braintreepayments.com/

**Comment by fapdash** [comment]
This was actually a problem with the registration for AMEX SafeKey that got handled by the support team. Closing now, thank you.

**Comment by marijadstankovic** [comment]
Hello, have the same question here.

I'm using sandbox environment (as I understand [3D Secure is automatically enabled for all merchants](https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration#:~:text=3D%20Secure%20is%20automatically%20enabled%20for%20all%20merchants)), have 3ds on client side with hosted fields. With setup like this I try [regular testing cards](https://developer.paypal.com/braintree/docs/reference/general/testing#credit-card-numbers) and for some of them I get "unsupported_card"  (ex 6011000991300009 or 36259600000004) with message "Merchant account does not support 3D Secure verifications for card type" and can't save those payment methods in Vault. How can I skip 3ds for unsupported cards?

**Comment by crookedneighbor** [comment]
@marijadstankovic please reach out to our support team for assistance: https://developer.paypal.com/braintree/help/

**Comment by marijadstankovic** [comment]
Yes, I have, last week, and still no answer :( I will send the request again.+

**Comment by vladsm** [comment]
Hello @marijadstankovic!

I've experienced the same issue with the cards that are not supported for 3DS for the marchant. Did you get any answer? Is it just the sandbox environment issue?

**Comment by marijadstankovic** [comment]
Hello @vladsm I contacted the support team then, and here is what they responded: _The card types associated with the general test cards 6011000991300009 (Discover) and 36259600000004 (Diners Club) are not currently supported for 3D Secure with Braintree._
I think this applies to all regular testing cards.

**Comment by Hamdael** [comment]
Hamdaeladnan2@gmail.com
