### ISSUE TITLE
Issue Braintree Drop-In UI in OS Yosemite in Safari

### ISSUE THREAD

**Issue by bonny3** [braintree/braintree-web-drop-in#573]
### General information

* SDK/Library version: 4.5.0 Drop-In UI JS library 1.20.4. 
* Environment: Production
* Browser OS Yosemite Safari 10.1.2 and 9.1.2

### Issue description

Hi,
I have encountered a  Issue with Braintree Drop-In UI
in OS Yosemite in the browser Safari 10.1.2 and 9.1.2 on the desktop
the 3D securcode pop-up is not opened
I ask to verify the problem and resolve...
Thanks

**Comment by bonny3** [comment]
I add screenshots of the Issue
![thumbnail_image0](https://user-images.githubusercontent.com/19350758/67763628-70e29e80-fa48-11e9-92f2-a11dfef1273b.jpg)

**Comment by hollabaq86** [comment]
:wave: @bonny3, thanks for reaching out & providing the screenshot. We're going to need some additional information to look into the issue further in partnership with our MPI provider CardinalCommerce. Can you [contact Support](https://help.braintreepayments.com/) referencing this issue along with the following:

- Your merchant ID
- Timestamps of the verifications that did not result in a popup being generated
- First six or last four digits of the card used (do not provide the full credit card number)
- The directives you're setting for your Content Security Policy

**Comment by hollabaq86** [comment]
We're re-opening this issue: on further investigation, Cardinal's `songbird.js` library cannot be loaded on Safari for older desktop OS's (Yosemite, Maverick) because the root SSL certificate for the URL to dynamically load `songbird.js` is not trusted by older OS truststores.

We're escalating to CardinalCommerce and will post updates here as we receive them.

**Comment by bonny3** [comment]
Great!
you after closing the my problem twice, you realized that the problem is real.. better late than never .. I waiting for updates
Thanks

**Comment by bonny3** [comment]
Hi,
nothing new?

**Comment by crookedneighbor** [comment]
We have an update from Cardinal. The truststore for some older Mac operating systems use ciphers that are not supported by the cdn that hosts Cardinal's songbird.js library. Our plan is to detect browsers unsupported by songbird.js (but _are_ supported by Braintree) and switch the workflow to a legacy 3DS v1 flow that does not depend on songbird.js. 

According to our logs, about %0.2 of customers are using these unsupported browsers. When we have something ready to address this, we will update here.

**Comment by crookedneighbor** [comment]
We've added some code to Drop-in to fallback to a 3ds v1 flow in the event that the v2 SDK fails to setup. This should take of the issue.

**Comment by atta1234** [comment]
hell i have the same issue,,dropin ui not showing in safari,,,,same error

JReferenceError: Can't find variable: braintree
js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.jsGET https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js An SSL error has occurred and a secure connection to the server cannot be made.

**Comment by crookedneighbor** [comment]
@atta1234 please contact our support team so we can investigate your integration. https://help.braintreepayments.com/

**Comment by atta1234** [comment]
> @atta1234 please contact our support team so we can investigate your integration. https://help.braintreepayments.com/

i have done that 3 days ago but no response!

**Comment by atta1234** [comment]
i have solved the above issue it was the outdated safari, that's why it was  not working, but i have two other issue, apple pay button not showing and  the paypal on web return error pending payment not supported and in android ,it's just display declined, the debit card and google pay working perfectly

**Comment by crookedneighbor** [comment]
We checked in with Braintree Support who confirmed they've received your inquiry and respond to inquiries in the order they are received. Please note, response times are currently delayed due to an influx of inquiries, and our Support team is working as quickly as possible to get to your questions.
