### ISSUE TITLE
Passing 3D secure billing address fields longer than 50 characters cause cardinal exception.

### ISSUE THREAD

**Issue by adamduke** [braintree/braintree-web-drop-in#574]
### General information

* DropIn version 1.20.4
* Environment: Production
* Browser and OS: Any

### Issue description

When passing a threeDSecure.billingAddress object as part of a requestPaymentMethod call, a client exception is thrown from cardinal js components if any of the individual address fields are longer than 50 characters (Error: Billing line1 format is invalid).

The exception raised looks like this:

{"name":"BraintreeError","code":"THREEDS_LOOKUP_VALIDATION_ERROR","message":"The data passed in `verifyCard` did not pass validation checks. See details for more info","type":"CUSTOMER","details":{"originalError":{"name":"BraintreeError","code":"CLIENT_REQUEST_ERROR","message":"There was a problem with your request.","type":"NETWORK","details":{"originalError":{"error":{"message":"**Billing line1 format is invalid**."},"threeDSecureInfo":{"liabilityShifted":false,"liabilityShiftPossible":false}},"httpStatus":422}}}},"sessionId":"4a5d8aec-5910-4c7c-adb8-c040e195ddd5"}

I can find references to various field length limitiations for the 3dsecure object in the php documention, but this appears to be listed as deprecated, not to mention being server-side.

https://developers.braintreepayments.com/reference/general/validation-errors/all/php#3d-secure

Also, these requirements are **not** listed in the newest documention for the client-side code at:
https://braintree.github.io/braintree-web/current/ThreeDSecure.html

**Suggested fix**:
- Add code to the braintree library to **truncate fields** passed in the 3d-secure setup call longer than the maximum expected by cardinal.
- Improve the documentation in this regard to explicitly list requirements for each object.  This also applies to the billing givenname and surname fields, which after much digging have to be stripped of diacritic and other non-ascii characters (for this we are using the remove-accents library).

Adam

**Comment by hollabaq86** [comment]
👋 @adamduke, thanks for the feedback! You're totally right that our documentation can be improved. I'm forwarding this to our Fraud Tools and Docs teams for review.

**Comment by chalov-anton** [comment]
Can this issue be reopened? This has also been closed https://github.com/magento/magento2/issues/30339

**Comment by hollabaq86** [comment]
@chalov-anton we updated our documentation from the original feedback we received. If you have additional suggestions on how we can improve the docs or a separate issue with your 3DS 2 integration, please [contact Support](https://help.braintreepayments.com/).

**Comment by yannickjemmely** [comment]
Hi guys,

For you information, I'm facing the same issue with drop-in : 1.36.1

Cheers
