### ISSUE TITLE
Paypal locale doesnt work

### ISSUE THREAD

**Issue by kr1stjans** [braintree/braintree-web-drop-in#580]
### General information

* SDK/Library version: 1.20.4
* Environment: Production
* Browser and OS: Chrome 78.0.3904.108  (64-bit) on MacOS 10.13.6

### Issue description

Paypal button supports localization (https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#button-styles), but it doesn't work when I pass it to Braintree.dropin.create function like so:

`
paypal: {
                                                                    flow: 'checkout',
                                                                    amount: value,
                                                                    currency: 'EUR',
                                                                    buttonStyle: {
                                                                        color: 'gold',
                                                                        shape: 'pill',
                                                                        size: 'large',
                                                                        label: 'pay'
                                                                    },
                                                                    locale: 'de_DE'
                                                                }
`

Button text and popup text is always en_US.

**Comment by crookedneighbor** [comment]
The `locale` should be passed in at the top level, not in the `paypal` object: https://github.com/braintree/braintree-web-drop-in/blob/f9d14bbc653aff6b7b574e11324c3fc9abf71325/src/views/payment-sheet-views/base-paypal-view.js#L48
