### ISSUE TITLE
3D Secure Drop-in for Subscriptions

### ISSUE THREAD

**Issue by chris-pauley** [braintree/braintree-web-drop-in#585]
### General information

* SDK/Library version: JS 3.55.0
* Environment: Sandbox
* Browser and OS Chrome/Firefox Latest on Ubuntu

### Issue description

I should be able to create a payment method using the 3DSecure drop-in for subscription payment methods, however any way to verify the card (braintree.verifyCard or dropin.requestPaymentMethod) using 3D Secure requires an 'amount' parameter to be sent with the 3D Secure options. [The docs](https://developers.braintreepayments.com/guides/3d-secure/recurring-transactions/javascript/v3#braintree-recurring-billing-subscriptions) seem to suggest this is possible.

How are subscription payment methods meant to be created when the amount is not known?

**Comment by scannillo** [comment]
Hi @chris-pauley. Reaching out to [Braintree Support](https://help.braintreepayments.com/) will be your best bet. They can explain how to set up recurring transactions using 3DS in more detail.

**Comment by tenshis** [comment]
Hi @chris-pauley , have you solved this? Would you mind giving us some tips?

**Comment by chris-pauley** [comment]
No I ended up dropping braintree due to their limited support for subscriptions.

**Comment by crookedneighbor** [comment]
Reaching out to Braintree support is still y'all's best bet. I believe the 3D Secure team has this on their roadmap: https://help.braintreepayments.com/
