### ISSUE TITLE
Add a method to Drop-in UI to return supported payment types

### ISSUE THREAD

**Issue by marko-rbn** [braintree/braintree-web-drop-in#594]
### General information

* SDK/Library version: 1.22.0
* Environment: Sandbox and Production
* Browser and OS: any browser

### Feature request

I have a requirement to be able to detect whether or not Venmo is supported on the client browser, in order to provide further instructions to the user.  This would be useful for any other payment method as well.

I currently use a workaround where I check an array within "clientInstance" parameter, however this is not guaranteed to work with future releases.

`clientInstance._mainView.paymentMethodsViews.model.supportedPaymentOptions.includes('venmo')`

Please add a method like "clientInstance.isSupportedPaymentMethod(_paymentMethod_)".

See support ticket #2723511 for reference.

**Comment by crookedneighbor** [comment]
Thanks for the suggestion @marko-rbn . I think that's a good idea to add.

**Comment by crookedneighbor** [comment]
This will go out in the next release. Re-opening until that happens.

**Comment by crookedneighbor** [comment]
This is out in v1.24.0
