### ISSUE TITLE
[IOS][Payment UI] - unable to remove expiration date it has been input

### ISSUE THREAD

**Issue by lijuan-wee** [braintree/braintree-web-drop-in#615]
**Integration Details (please complete the following information):**
 - SDK/Library Version: [e.g. 4.33.0] - braintree 3.6.0
 - Environment: [e.g. Sandbox or Production] - Sandbox
 - iOS Version: [e.g. iOS 13.0]
 - Device [e.g. iPhone 6s] - Iphone X
 - Integration type & version [e.g. CocoaPods 1.1.1, Carthage 0.18.1]  Cordova platform 4.4.0

![expiration date ](https://user-images.githubusercontent.com/64088446/79931410-8aa3f200-847d-11ea-881d-d8ce3c6fccc1.gif)

**Describe the bug**
Description of what the bug is. Please include as many details as possible.

At payment page, our application is loading the card detail UI from brain tree. 
Upon adding the expiry date, user is unable to remove the expiry date input. 

**To Reproduce**
3. See error 

**Expected behavior**
User should be able to amend the card expiry date input

**Screenshots**

**Comment by crookedneighbor** [comment]
What version of web drop-in are you using? You listed the sdk as `braintree 3.6.0`, but the latest version of Drop-in is 1.22.1.

I suspect this is a known issue with iframes in safari webviews. We've added multiple workarounds to deal with the buggy behavior with ios webviews in the underlying BT SDK, so I'd update to the latest version of Drop-in first and see if that solves your issue.

**Comment by crookedneighbor** [comment]
Most likely the cursor is at the beginning of the line. I'd recommend reworking your UI so that the expiration date field is visible so your customer can adjust where their cursor marker is positioned.

**Comment by gesa** [comment]
oh yeah i can say with about 99% confidence that this is a known issue where inputs behind the iOS Safari virtual keyboard will frequently not scroll into view if they're technically within the viewport. (the viewport is not impacted by the presence of the virtual keyboard, and javascript cannot detect it). newer versions of braintree-web (i think >= 3.52.1, drop-in >= 1.20.1) have some clever workarounds in them, but it's an OS-level issue.
