### ISSUE TITLE
More undocumented changes impacting Content Security Policy?

### ISSUE THREAD

**Issue by Mneroen** [braintree/braintree-web-drop-in#622]
For the 3D Secure iframe i had to enable more URIs in my Content Security Policy.

https://songbird.cardinalcommerce.com/edge/v1/91ae5edca378ad3af82e/11.91ae5edca378ad3af82e.songbird.js calling these URIs for the 3D Secure iframe:

www.clicksafe.lloydstsb.com
pay.activa-card.com
3dsecure-1.wirecard.com
acssv.otpbank.hu
acs.sia.eu
idcheck.acs.touchtechpayments.com

Are there any more?

Are these URI's country specific? Like the otpbank.hu for Hungary or the lloydstsb.com for United Kingdom customers?

**Comment by crookedneighbor** [comment]
Let's just track this in the underlying SDK: https://github.com/braintree/braintree-web/issues/497
