### ISSUE TITLE
Issue Braintree Drop-In Internet Explorer

### ISSUE THREAD

**Issue by bonny3** [braintree/braintree-web-drop-in#624]
General information

* SDK/Library version: 1.22.1
* Environment: Production
* Browser and OS Interne Explorer 11 Version:11.778.18362.0 Version Update 11.0.185
* Win 10 and Win 7

Issue description:

Hi,

I received a report from a user who was unable to finish the transaction on Braintree in "internet Explorer" on "Windows 7 Pro"
I tried on my "internet Explorer" "Win 10" actually it stop on "please wait" after entering the 3D Secure Code ...

![2020-05-15_204920](https://user-images.githubusercontent.com/19350758/82085594-933ebf80-96ed-11ea-9463-26b2237726d5.png)

transactions with Internet Explorer are not possible

Thanks
Best Regards
Alessandro

**Comment by bonny3** [comment]
> 
> 
> I think we need more information.
> 
> Are there any console messages? Failed network requests?
> 
> Are all 3DS transactions failing in internet explorer? Or only from specific banks?

Hi crookedneighbor,

I'll send you the message screen on the console
I have tried from three different types of credit cards
both mastercard and visa,
the operation is correct up to the insertion of the 3d Secure Code code,
when I insert the code, it writes the correct code, it reloads the page and it stops on "please wait"
remains as per screenshot

**Comment by crookedneighbor** [comment]
Can you dig into the error in the callback function? Where is that coming from?

**Comment by bonny3** [comment]
HTML1300: Navigation occurred.
checkout
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
checkout
HTML1114: Codepage iso-8859-1 from (HTTP header) overrides conflicting codepage utf-8 from (META tag)
vereqauthid=34313130727336506A787A2B69444A3736633136492B77413D3D53F0248E9D
HTML1114: Codepage iso-8859-1 from (HTTP header) overrides conflicting codepage utf-8 from (META tag)
formauthid=3438654463397846506E337A616957767147454A6D3264773D3DFB3377D68F
Error in callback function
TypeError: Unable to get property 'nodeName' of undefined or null reference
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: {
               [functions]: ,
               __proto__: null
            },
            message: "",
            name: "Error"
         },
         message: "",
         name: "TypeError"
      },
      description: "Unable to get property 'nodeName' of undefined or null reference",
      message: "Unable to get property 'nodeName' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'nodeName' of undefined or null reference




this is what I see in the console

**Comment by crookedneighbor** [comment]
Can you tell where that error is emitting from? Is it from the BT SDK? Your own code? The underlying Cardinal SDK that is doing the 3ds work?

**Comment by crookedneighbor** [comment]
And do you experience the same issues in sandbox? Or just production?

**Comment by bonny3** [comment]
I only tried in production,
if you want I can give you the name of the site for
try the problem ...

**Comment by bonny3** [comment]
watch the video:
https://www.occhialando.it/2020-05-15.mp4

**Comment by bonny3** [comment]
maybe I found the problem,
but I have to check with the developer,
I'll update you tomorrow

Thanks!

**Comment by bonny3** [comment]
Hi,

after many hours of work the problem is solved,
it was due to a .js that interfered with Braintree's Drop-in
this happens if I am in "Internet Explorer"
I confirm that Braintree's Drop-in is working properly.
thanks for the assistance

Thanks
Best Regards
Alessandro
