### ISSUE TITLE
Hello i have two issue with braintree

### ISSUE THREAD

**Issue by atta1234** [braintree/braintree-web-drop-in#631]
first,
i m getting this two error, when select paypal button payment,
An error occurred with the message: PayPal pending payments are not supported

second apple pay button is not showing on chrome safari, even on mac, have not tested in iphone,,is that will be shown in iphone only?not supported in web please clear my confusion,
i have impletemen apple pay certificate on braintree, but still not working

**Comment by crookedneighbor** [comment]
See https://github.com/braintree/braintree-web-drop-in/issues/161#issuecomment-301501211 for the pending payments issue.

Please reach out to our support team regarding apple pay. By "chrome safari", I assume you mean Safari on a Mac as Apple Pay is not compatible in the Chrome browser. https://help.braintreepayments.com/

**Comment by atta1234** [comment]
thank you for reply, yes i have checked in mac as well,but apple pay not showing, and for the pay-pal pending issue i have done that setting already but still same issue,,

**Comment by atta1234** [comment]
when i use paypal smart check oout button, i dont' face any issue,with error An error occurred with the message: PayPal pending payments are not supported
it's occur when i use brain tree sdk

**Comment by crookedneighbor** [comment]
Your best course is to contact our support team so they can inspect your account: https://help.braintreepayments.com/
