### ISSUE TITLE
Does #teardown() actually unsubscribe events?

### ISSUE THREAD

**Issue by dminkovsky** [braintree/braintree-web-drop-in#632]
### General information

* SDK/Library version:1.22.1
* Environment: N/A
* Browser and OS: N/A

### Issue description

I was [adding the `off` method](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45832) to the DT definition when I noticed the changelog said:

> Add off method for unsubscribing from events without tearing down

I looked at `#teardown()`, but could not see where it unsubscribes any subscribed event emitter handlers. Is this correct?

**Comment by crookedneighbor** [comment]
The events shouldn't be able to emit once it's torn down, so it shouldn't matter. If you call teardown, you do not also need to `off`.

**Comment by crookedneighbor** [comment]
(if you've found a case where that isn't true, and events are still being emitted after it has been torn down, let us know!)

**Comment by dminkovsky** [comment]
Is this not a memory leak situation?
