### ISSUE TITLE
Version 3.62.2 undefined array

### ISSUE THREAD

**Issue by paymentplugins** [braintree/braintree-web-drop-in#633]
### General information

* SDK/Library version: 3.62.2
* Environment: Production and Sandbox
* Browser and OS - Chrome 83.0.4103.116

### Issue description

When using Braintree SDK version 3.62.2 with Dropin version 1.22.1, the console error issues the following message:

`Uncaught TypeError: Cannot read property 'push' of undefined`. 

The error is occurring at the following minified line of code: `t.args.push(t.reply))`. 

Reverting to Braintree SDK version 3.62.1 resolves the issue so it appears specific to 3.62.2. It should be noted that this message does not appear to interfere with the checkout experience, but I have several reports from merchants that are concerned about the message appearing in their dev console.

![dropin](https://user-images.githubusercontent.com/17156041/86608651-accaed80-bf5f-11ea-994e-f2420856bf6e.PNG)

Kind Regards,

**Comment by crookedneighbor** [comment]
Can you explain how you are using Drop-in in conjunction with the standalone sdk? That's not a normal style of integration.

**Comment by paymentplugins** [comment]
My solution gives merchants the ability to present payment methods like Apple Pay, GPay, Venmo, etc in addition to the credit card form. Regardless of whether the dropin form is used, the code loads all the required Braintree scripts that the other payment options would need.

Here is a screenshot showing all of the Braintree scripts that are loaded on the checkout page, based on the payment options the merchant has enabled.
![dropin](https://user-images.githubusercontent.com/17156041/86611786-09300c00-bf64-11ea-9fe5-eb5adb623054.PNG)

**Comment by crookedneighbor** [comment]
I need to do a little investigation on this, but if it's due to a mismatch in versions of the core sdk, this should be fixed in version 1.23.0 of Drop-in and 3.63.0 of the core sdk.

Going to leave it open for a bit to do some further exploration, but in general, you will probably want to stick with the version of the core sdk used by Drop-in if you're going to use both of them side by side.

**Comment by paymentplugins** [comment]
I tested version 3.63.0 of the SDK alongside version 1.23.0 of the dropin and the error message is no longer present.

Kind Regards,
