### ISSUE TITLE
Google pay cardRequirements field is does not exist

### ISSUE THREAD

**Issue by AndresPrietoTucasi** [braintree/braintree-web-drop-in#637]
### General information

* SDK/Library version: https://js.braintreegateway.com/web/dropin/1.22.1/js/dropin.min.js
* Environment: Sandbox
* Browser and OS Google Chrome is up to date Version 83.0.4103.116 (Official Build) (64-bit)

### Issue description
To add google pay to the drop in UI I followed the documentation on the following link
https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3
With which i added the following code:
`googlePay: {
 	    googlePayVersion: 2,
 	    merchantId: googlePayMerchant,
 	    transactionInfo: {
 	      totalPriceStatus: 'FINAL',
 	      totalPrice: transactionTotalvalue,
 	      currencyCode: currency
 	    },
 	    cardRequirements: {
 	      billingAddressRequired: true
 	    }	    
 	  },
I noticed that when i started up the page i was gettin te following in the chrome console:
`
![image](https://user-images.githubusercontent.com/68009089/87321543-44ae7580-c524-11ea-9ede-9be8b7dc9bd8.png)
Upon selecting google pay for payment it would open up the view but i would get an error message:
![image](https://user-images.githubusercontent.com/68009089/87321867-ac64c080-c524-11ea-8569-8870fe599dc0.png)

Ive noticed that if i remove the cardRequirements section, the page loads without any problems. Is the cardRequirements no longer suported? as it seems without it the billingAdress is required anyway.

**Comment by gesa** [comment]
Yeah, Google's request object shape changed a bit with v2. Check out [their migration guide](https://developers.google.com/pay/api/web/guides/resources/update-to-latest-version#apiversion-2)—specifically I think the [billing address](https://developers.google.com/pay/api/web/guides/resources/update-to-latest-version#billing-address) section is what you're looking for.

I see the sample code you pointed out in our own Guides, I'll take a look at updating that code.

**Comment by gesa** [comment]
Actually I'll leave this open until the docs are fixed.

**Comment by gesa** [comment]
My apologies for not updating this issue—updated docs have been deployed.
