### ISSUE TITLE
Finnish Translations Support

### ISSUE THREAD

**Issue by AlexanderCollins** [braintree/braintree-web-drop-in#641]
Hi there!

My Finnish team were in need of some Finnish translations so we made some and thought we would share them here!

I read the contributing guideline and it looks like translation requests are not allowed and also would only be included if the language is listed within [PayPal's accepted language codes](https://developer.paypal.com/docs/api/reference/locale-codes/#supported-locale-codes) which luckily appears to be the case. (fi_FI priority 0)

Regarding the translations themselves, I have a native Finnish speaker with C2 english level proficiency who has completed the translations from english and have also had the translations verified by another native Finnish speaker. I've prepared a [pull request: 639](https://github.com/braintree/braintree-web-drop-in/pull/639).

It would be great if this could be escalated to the localisation team for verification. In the mean time we will use the translations directly with the translations prop as per the [braintree-web-drop-in documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#create-examples).

Many Thanks!

**Comment by crookedneighbor** [comment]
I've notified our localization team, thanks for the heads up. Had no idea we were missing some translations in the project.

**Comment by AlexanderCollins** [comment]
Not a problem, Thanks!

**Comment by crookedneighbor** [comment]
I pinged the localization team about this again, still waiting on an ETA.

**Comment by crookedneighbor** [comment]
Re-opening this until it actually gets released.

We finally got the translations in for this, so this will go out in the next release.

**Comment by davidtomcik** [comment]
> Re-opening this until it actually gets released.
> 
> We finally got the translations in for this, so this will go out in the next release.

Please, what date is the next release?

**Comment by crookedneighbor** [comment]
We're currently waiting on some translations for this PR: https://github.com/braintree/braintree-web-drop-in/pull/661

Hoping to get a release out next week.

**Comment by crookedneighbor** [comment]
The PR I mentioned has been merged, hoping to get the release out early next week.

**Comment by crookedneighbor** [comment]
This is released with v1.25.5

**Comment by crookedneighbor** [comment]
^ v1.25.0, not 1.25.5

**Comment by davidtomcik** [comment]
> This is released with v1.25.0

Thank you. I am going to update.
