### ISSUE TITLE
Dropin copies 3 first chars of credit card number to the end of it after the paste

### ISSUE THREAD

**Issue by Fifciu** [braintree/braintree-web-drop-in#650]
### General information

* SDK/Library version: 1.22.1
* Environment: Sandbox
* Browser and OS: Chrome 83.0.4103.83, Android 10/9/8/7/5

### Issue description

If we paste Credit Card number to dropin's field on Chrome, Android. It copies 3 first numbers from credit card to the end of number. It doesn't happen on iOS or Firefox.

![Example](https://user-images.githubusercontent.com/57936972/84513569-ed6d7900-acc9-11ea-8ec9-5afd49e85d09.gif)

**Comment by crookedneighbor** [comment]
Couple of questions:

A) have you verified this on a real device, or only through the virtual device on browserstack?
B) have you made substantial changes to the style of Drop-in? It doesn't look like the normal Drop-in integration. I don't think that will have anything to do with the paste handling in the card iframe, just want to make sure we're troubleshooting the right thing.

**Comment by crookedneighbor** [comment]
I'm able to reproduce on a real device. Thanks for the report. Looking into it.

**Comment by Fifciu** [comment]
Yup it is a real problem in our app. What is the status @crookedneighbor ? Is someone taking care of that or it is somewhere in the queue?

**Comment by crookedneighbor** [comment]
I've tracked down the underlying issue. We'll need to get it released in the input formatting library we use: https://github.com/braintree/restricted-input/pull/78

Then update the core sdk with the new version and release that, then update Drop-in with that new version of the sdk and release it to resolve this issue.

**Comment by crookedneighbor** [comment]
Hoping to get a fix out for this sometime this week.

**Comment by Fifciu** [comment]
How is it going @crookedneighbor ?

**Comment by crookedneighbor** [comment]
Sorry, was out of office all last week. This should be fixed now in v1.24.0
