### ISSUE TITLE
`options.preselectVaultedPaymentMethod` does not preselect the active vaulted payment method

### ISSUE THREAD

**Issue by adamhenson** [braintree/braintree-web-drop-in#652]
### General information

* SDK/Library version: 1.23.0
* Environment: sandbox and production
* Browser and OS: any

### Issue description

When initializing with `braintree.dropin.create` with a token connected to a customer ID the [`preselectVaultedPaymentMethod` is `true` by default](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create), but a different card shows at the top of the UI and is selected than the users active payment method.

The below is what I would expect and to me this seems like an issue... or I'm doing something wrong. Would someone clarify if this is expected?

**Expected**:
The users active payment method should show selected at the top of the UI list of payment methods.

**Actual**:
A random payment method is selected and shown at the top of the list of payment methods in the UI.

> payload from `gateway.paymentMethod.find(token)`
> https://developers.braintreepayments.com/reference/request/payment-method/find/node
<img width="212" alt="Screen Shot 2020-08-22 at 2 13 25 PM" src="https://user-images.githubusercontent.com/747743/90962928-c4afef80-e481-11ea-87df-c6cbcba11bb3.png">

> issue (note the text we add from the user's active payment method conflicting with the selected card.
<img width="889" alt="Screen Shot 2020-08-22 at 2 13 51 PM" src="https://user-images.githubusercontent.com/747743/90962962-12c4f300-e482-11ea-8c06-5dbb0d6bd549.png">

**Comment by crookedneighbor** [comment]
That's very odd and not what I would expect. I'll have to dig into this.

**Comment by imkane** [comment]
We're also seeing this. Any update, Braintree?

**Comment by crookedneighbor** [comment]
I have not had a chance to dig into this yet. 

Question: is the default payment method expired by any chance?

**Comment by imkane** [comment]
Nope, this is in sandbox, too. The expiry dates are years away.

> I have not had a chance to dig into this yet.
> 
> Question: is the default payment method expired by any chance?

**Comment by crookedneighbor** [comment]
We're definitely fetching with the intent to show the default first: https://github.com/braintree/braintree-web-drop-in/blob/8f0cecf750551a99e438a717c30a93de6ab9ffc9/src/dropin-model.js#L304

But one edge case where this could get messed up is if the default payment method is expired, and there's a duplicate payment method on the customer that is not the default, and is not expired. In that case, the payment methods returned would consolidate the expired and non-expired version and only show the non-expired version, which is not the default.

@imkane @adamhenson 

Do y'all have staging sites that can reproduce the issue I can take a look at?

**Comment by adamhenson** [comment]
@crookedneighbor - I don't. I ended up just disabling this functionality altogether since it's broken with `preselectVaultedPaymentMethod: false`. I was able to reproduce this with any user in sandbox and production. I'd imagine you could reproduce this with a standard setup based on the "general information" I provided in the description.

**Comment by imkane** [comment]
@crookedneighbor We got it sorted! Just had to add the `options` field as shown below:

```
var result = await BTGateway.paymentMethod.create({
      customerId: customerId,
      paymentMethodNonce: nonce,
      options: {
        makeDefault: true,
      },
    });
```

**Comment by crookedneighbor** [comment]
@adamhenson I can't reproduce:

![Screen Shot 2020-11-16 at 9 45 25 AM](https://user-images.githubusercontent.com/2916945/99274907-7c8a3a00-27f0-11eb-8e01-c908c735e942.png)

![Screen Shot 2020-11-16 at 9 45 15 AM](https://user-images.githubusercontent.com/2916945/99274916-7eec9400-27f0-11eb-93fc-bb119048e6ad.png)


One question of clarification, when you say "active card", you mean the payment method that is marked as the customer's default, right?

**Comment by adamhenson** [comment]
Correct, @crookedneighbor - the one returned from [`gateway.paymentMethod.find`](`https://developers.braintreepayments.com/reference/request/payment-method/find/node). I would expect that to be the one last used, but maybe I need to do some extra legwork to make that happen? I'm looking at @imkane's example setting `makeDefault: true`, which I haven't seen before. Give me a week or so to get back to test and get back.

**Comment by crookedneighbor** [comment]
@adamhenson OK, I think I see what the confusion is. There's a difference between the customer's default payment method and the last one used. If you never update the customer to change the default payment method, the default will be the customer's _first_ payment method.

The underlying API endpoint for fetching payment methods does support showing the _last_ payment method used, so it should be a very simple matter of updating Drop-in to allow that to be configured, instead of just always configuring it to show the default payment method.

https://github.com/braintree/braintree-web-drop-in/blob/8f0cecf750551a99e438a717c30a93de6ab9ffc9/src/dropin-model.js#L304

**Comment by adamhenson** [comment]
Thanks @crookedneighbor - then this seems like a confusion on my part. Closing. Thanks again for your help!

**Comment by crookedneighbor** [comment]
I think allowing it to be configured could still be valuable, so I opened a PR for it: https://github.com/braintree/braintree-web-drop-in/pull/675

With this PR, if you configure it to _not_ show the default payment method first, then the API will decide, which will typically be the latest payment method _added_ to the customer. I say typically because the order is _not_ guaranteed. 

I think for your use case in particular, I'd go ahead and just update the `default` payment method on your customer when your system adjusts the active payment method in your backend.

**Comment by adamhenson** [comment]
Thanks @crookedneighbor.

**Comment by crookedneighbor** [comment]
This was added in v1.26.0

**Comment by adamhenson** [comment]
#675 helps with this however my issue still exists. Intuitively, I think the **most recently used** card should be the default. I wouldn't expect any extra configuration for this to work out of the box, but it seems like in order to accomplish this - I'll need to build a server side flow to allow users to manage payment methods in a way that makes any normal sense.
