### ISSUE TITLE
Logged into a sandbox account with cards added, but still can't test Apple Pay

### ISSUE THREAD

**Issue by jlucki** [braintree/braintree-web-drop-in#656]
### General information

* SDK/Library version: 1.23.0
* Environment: Sandbox
* Browser and OS: MacOS Safari latest

### Issue description

I've setup the DropIn UI and it works like a charm with card, paypal and google pay. Apple Pay is proving to be trickier. I've added the certificate and domains. It looks now as if I've setup everything correctly but I'm getting the following error:

`Developer Error: Something went wrong. Check the console for details.`

In the console, I get this: `Could not find an active card. This may be because you're using a production iCloud account in a sandbox Apple Pay Session. Log in to a Sandbox iCloud account to test this flow, and add a card to your wallet. For additional assistance, visit  https://help.braintreepayments.com`

However, on my mac I am logged into a apple tester sandbox account, with two test cards added to my wallet.

I can actually still click on the black Apple Pay button. A payment window for Apple Pay briefly pops up. It has the test card details and it's got a spinning Processing animation. Then it errors again and I see this in the console:

`Failed to load resource: the server responded with a status of 417 ()`

`{
    "error": {
        "message": "Payment Services Exception merchantId=*** unauthorized to process transactions on behalf of merchantId=*** reason=\"*** is not a registered merchant in WWDR and isn't properly authorized via Mass Enablement, either.\""
    },
    "fieldErrors": []
}`

I'm not sure if I've setup something wrong, or if this is a bug?

**Comment by hollabaq86** [comment]
👋 @jlucki please [contact Support](https://help.braintreepayments.com/)- they can assist in troubleshooting your Apple Pay integration.
