### ISSUE TITLE
paypalCreateOptions buttonStyle is type "string" but requires type "object" for configuration.

### ISSUE THREAD

**Issue by J-Gonzalez** [braintree/braintree-web-drop-in#658]
### General information

* SDK/Library version: 1.24.0
* Environment: N/A
* Browser and OS N/A

### Issue description

When creating a Drop In component with Paypal enabled, buttonStyle is only of type "string", but configuration is an object.
You can see here in the current docs that the paypalCreateOptions for buttonStyle is only of type string and not an object. This is causing errors with Typescript as the types don't match.

https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~paypalCreateOptions

**Comment by crookedneighbor** [comment]
You're right that the jsdoc needs updating.

Note that if you're using a typescript package to get types for this repo, that is not maintained by Braintree, and you will need to contact the maintainer for that repo.

**Comment by crookedneighbor** [comment]
The docs have been fixed and will go out in the next release.
