### ISSUE TITLE
UI: Fields and Errors overflow and overlap when stacked (on small displays)

### ISSUE THREAD

**Issue by J-Gonzalez** [braintree/braintree-web-drop-in#664]
### General information

* SDK/Library version: 1.24.0
* Environment: N/A
* Browser and OS: Chrome Web, Chrome + Pixel2, iPhone
### Issue description

When the drop-in UI is presented on small screens and all fields stack, fields and error messages overflow when errors are presented. I've copied the Braintree Codepen to reproduce (using a different sandbox authorization) so that all fields (postal, cvv, cardholder name ) are showing:

https://codepen.io/jgonzlez722/pen/oNxPaWB
![image](https://user-images.githubusercontent.com/1047598/93527710-42431000-f907-11ea-9ad0-e417548f0fbe.png)

This issue was sort of documented here: https://github.com/braintree/braintree-web-drop-in/issues/537#issuecomment-519258506 but I didn't see a Github issue just for this UI/overflow issue

**Comment by crookedneighbor** [comment]
Thanks for the report, you're right that it's related to #537 but should be a distinct issue. (the core of 537 will be solved with a recent PR)

**Comment by IP-Developer** [comment]
Can confirm that the problem still persists on smaller screens.
