### ISSUE TITLE
Changing the Paypal flow to vault results in a refused transaction

### ISSUE THREAD

**Issue by kaplantm** [braintree/braintree-web-drop-in#667]
### General information

* SDK/Library version: 1.1.2
* Environment: Sandbox
* Browser and OS Chrome 85.0.4183.121 (64-bit) on MacOS 10.14.6

### Issue description

I am creating the drop-in with the following options:

```
{
        container: '#dropin-container',
        authorization: clientToken,
        card: {
          vault: {
            vaultCard: true,
          },
        },
        dataCollector: { paypal: true },
        paypal: {
          flow: 'vault', 
        },
      }
```

This results in transaction.sale returning a long error, with this notable section:
```
       "processorResponseCode": "2046",
        "processorResponseText": "Declined",
        "additionalProcessorResponse": "2046 : TRANSACTION_REFUSED",
```

the params I am sending to gateway.transaction.sale:
```
{
      amount, // e.g. 10
      paymentMethodNonce: nonceFromTheClient, // e.g. "f828a53b-ddd3-06ff-570d-72f33bc432a2"
      deviceData: deviceDataFromTheClient, // e.g. '{"correlation_id":"97d54753a521ebe22fa54df950950675"}'
      options: {
        submitForSettlement: true,
      },
    }
```

However, when i change the drop in creation options to use the paypal checkout flow, the transaction succeeds.
```
paypal: {
          flow: 'checkout',    
          amount: 10,
          currency: 'USD',
        },
```

I'm wondering if this is a bug, or if this is undocumented additional setup needed to use the vault flow?

**Comment by crookedneighbor** [comment]
It sounds like something in your PayPal account is not set up to use the billing agreement (vault) flow. Reach out to our support team so they can investigate it. https://help.braintreepayments.com/
