### ISSUE TITLE
Using chrome payment autofill in the cardholder name field not detecting a card number has been entered.

### ISSUE THREAD

**Issue by mambose** [braintree/braintree-web-drop-in#676]
### General information

* SDK/Library version: 1.25.0
* Environment: Sandbox
* Browser and OS Chrome Version 87.0.4280.67 (Official Build) (x86_64) Mac and Windows

### Issue description

If you use Chrome's payment autofill from the cardholder name field it successfully autofills all the fields but the UI does not register that a card number has been entered. In previous versions (1.24.0) chrome would only suggest address autofill options for this field but now in 1.25.0 is now showing payment autofill options.

If you autofill starting with the card number field though everything works as expected.

**Comment by crookedneighbor** [comment]
Thanks for the heads up. We recently updated Drop-in to allow for autofilling the cardholder name, but there must be a bug in the implementation.

**Comment by kr1stjans** [comment]
Any workaround for this?

**Comment by crookedneighbor** [comment]
There's no workaround other than not collecting cardholder name in drop-in. We're working on fixing this in the underlying JS SDK

**Comment by crookedneighbor** [comment]
This is now fixed in v1.26.0
