### ISSUE TITLE
threeDSecure example lookup_error fail on UK regions

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree-web-drop-in#678]
### General information

* SDK/Library version:  1.25.0
* Environment: Sandbox
* Browser and OS Chrome

### Issue description

According to https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~additionalInformation
```
shippingAddress: {
  region: '',
}
```
> "The 2 letter code for US states, and the equivalent for other countries."

In the UK our regions have full names (and no letter codes). Passing e.g. 
```
{
  countryCodeAlpha2: 'GB'
  region: 'Dorset'
}
```
always results in a `lookup_error`

This can be replicated on your codepen here: https://codepen.io/braintree/pen/KjWqGx by 
* autofilling 
* set region : Dorset
* country: GB
* entering 4000000000001000

![image](https://user-images.githubusercontent.com/13466620/101914095-c1b94600-3bbb-11eb-9af3-9781f9c0b57a.png)

**Comment by crookedneighbor** [comment]
Thanks, we've passed this along to the team that maintains the lookup API.

**Comment by bohford** [comment]
Hi @ChrisHSandN , apologies, we will update the documentation and error message to be clearer.

For this billingAddress and shippingAddress region fields, the maximum length is 3 characters as dictated by the 3DS 2 spec. The value for these fields is intended to be the appropriate ISO-3166-2 subdivision code. [Here is a list for Great Britain](https://en.wikipedia.org/wiki/ISO_3166-2:GB). For example, the region code for Dorset would be `DOR`. With countries where region codes are not particularly common (like the UK) we've also seen merchants simply omit the region in the 3D Secure call. Hope this helps.

**Comment by ChrisHSandN** [comment]
Thanks for your help, I did not even know ISO-3166 went down to sub-region level like that. your 3DS documentation definitely needs to make it clear that this is mandatory.

Unlike US states which haven't changed in 60 years, UK sub divisions have over 30 changes just in the last 10 years so I think I will stick to not including region with my 3DS data!

It would also be nice if the validation returned a descriptive error rather than `lookup_error`, e.g. if you miss country off you get a proper 422 status error with a message:
![image](https://user-images.githubusercontent.com/13466620/102060833-99fbf500-3dea-11eb-9613-cff89526bf83.png)

**Comment by crookedneighbor** [comment]
@ChrisHSandN we can't make that error change in the current version of the SDK, because that would (unfortunately) be a breaking change.

We are however in the beginning stages of building out the next major version, and we intend to forefront the underlying errors that get buried in the currently deeply nested errors, which should make it much easier to inspect the errors.
