### ISSUE TITLE
venmo option not show on desktop website

### ISSUE THREAD

**Issue by LeVuMinhHuy** [braintree/braintree-web-drop-in#686]
braintree.create(
        {
          authorization: userStore.braintreeTokenId,
          container: '#checkout-container',
          paypal: {
            flow: 'vault',
          },
          venmo: {
            allowNewBrowserTab: false,
          },
        },

I've already accept venmo option on braintree sandbox, but for now dropin just only show payment method card and paypal. 

![Screenshot from 2021-01-14 15-11-18](https://user-images.githubusercontent.com/36370320/104562337-cc637100-567a-11eb-97fb-4e31a5e0d4ed.png)

**Comment by crookedneighbor** [comment]
You need to specify:

```
venmo: {
  allowDesktop: true
}
```

**Comment by crookedneighbor** [comment]
Or in your case:

```js
venmo: {
  allowNewBrowserTab: false,
  allowDesktop: true
}

**Comment by lnogueracmnhospitals** [comment]
Do you plan to add these options to the types any time? Because if we use the types we don't get them and we our app doesn't compile if we add them. But if we remove the types they work fine.
