### ISSUE TITLE
Venmo Page Refresh Preventing Venmo from Working

### ISSUE THREAD

**Issue by deanpeterson** [braintree/braintree-web-drop-in#687]
### General information

* SDK/Library version: Javascript 1.26.0
* Environment: Production
* Browser and OS Chrome on Android

### Issue description

Paying with venmo on an Angularjs 1.x application does not work. When returning to the application from Venmo app, the page refreshes and the payment state is wiped out and users return to landing page. 

The page refresh is entirely unnecessary. The "paymentMethodRequestable" event fires and seems to be ready for submission. The page refresh wipes everything out. How can I prevent that page refresh when paying with Venmo? Credit cards and paypal work fine. Why does Venmo have to behave differently? I think if I can stop it from refreshing the page it should work. I know about the allowNewBrowserTab: false property but I don't want to eliminate browsers like Androids chrome browser that everyone uses just because Venmo feels the need to refresh the page.

**Comment by crookedneighbor** [comment]
:wave: Drop-in is not refreshing the page. When Drop-in app switches to Venmo, the venmo app then switches back to the website and adds to the page's hash. Most likely your Angular router is detecting the hash change and doing some app routing based on that.

We're doing some work on the venmo component to eliminate the need for the hash change at all, but it'll likely be a while before that change is fully implemented into the Venmo app (which is doing the hash change), so you'll likely have to handle the hash change in your router config.

**Comment by crookedneighbor** [comment]
I'm going to close this due to inactivity. Please reach out if you need additional help.

**Comment by lnogueracmnhospitals** [comment]
Hello @deanpeterson, did you find a workaround for this? We're having the same issue in an Angular SPA as well.
