### ISSUE TITLE
Sandbox THREEDS_CARDINAL_SDK_ERROR while testing

### ISSUE THREAD

**Issue by brandonburkett** [braintree/braintree-web-drop-in#689]
### General information

* SDK/Library version: 1.26.0
* Environment: Sandbox
* Browser and OS: Chrome 87.0.4280.141 and MacOS 11.1

### Issue description

Testing 3d Secure in sandbox specifically with the card numbers listed on "Error on Authentication" (last set of [test card numbers](https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/php) ) results in an **THREEDS_CARDINAL_SDK_ERROR**

```
{
    name: "BraintreeError", 
    code: "THREEDS_CARDINAL_SDK_ERROR", 
    message: "A general error has occurred with Cardinal. See description for more information.", 
    type: "UNKNOWN", 
    details: {
        originalError: {
            code: 1050
            description: "Error Processing PARes"
        }
    }
}
```

All other test card numbers worked (for me), it was only the last set for "Error on Authentication" that produced this error.  I plan to handle this on the front end since it returned as the `requestPaymentMethod` callback err param, but did not see anything in the braintree 3ds docs about having to handle this specific error.

Assume it is a 3ds outage on the customer's bank side?

Thanks,
Brandon

**Comment by crookedneighbor** [comment]
I'll check in with our 3ds team on this.

**Comment by crookedneighbor** [comment]
This is expected for this test card. This error happens at the Cardinal SDK level, before communication with Braintree.

https://cardinaldocs.atlassian.net/wiki/spaces/CCen/pages/903577725/EMV+3DS+Test+Cases#Test-Case-12:-Error-on-Authentication
