### ISSUE TITLE
No UI feedback presented for 3DS BraintreeError

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree-web-drop-in#694]
### General information

* SDK/Library version: 1.25.0
* Environment: Sandbox and Production
* Browser and OS: Chrome on Windows 10

### Issue description

The DropIn doesn't show any UI feedback when `requestPaymentMethod()` errors due to a 3DS issue.

#### To Replicate
* Go To https://codepen.io/braintree/pen/KjWqGx
* Use the "Error on Authentication" 3DS test card `4000000000001125`, `01/2024`
* Click "Pay Now"
* You can see the error showing in the console but there is no feedback to the user that anything has gone wrong
![image](https://user-images.githubusercontent.com/13466620/107638891-15054e80-6c68-11eb-9bd6-59da6b93e8af.png)

Compare that to the feedback given for things like invalid card number:
![image](https://user-images.githubusercontent.com/13466620/107637983-e0dd5e00-6c66-11eb-80ea-8b129f4eb42d.png)

*** 

As a 2nd point to this; if we are supposed to handle the UI of these errors ourselves, how are we supposed to differentiate between the errors which the DropIn has already presented feedback for and the ones which it has not?

Currently I am doing `if (error.name === 'DropinError' && error.message === 'No payment method is available.')` to detect the handled ones but that feels very fragile.

**Comment by crookedneighbor** [comment]
Hey, sorry for the delay.

I'm talking with our 3d secure team about what the right approach for this kind of error is. What we're currently doing is definitely not right, since it leaves Drop-in in a state where it looks like the nonce can be used, when it has already been consumed and will error if you try to call `requestPaymentMethod` again.

**Comment by ChrisHSandN** [comment]
From a actual customer standpoint, we were getting complaints that they would fill in their details, press the submit button, perform 3DS validation on the popup and then have nothing happen. It took a while before we realised what was going on and that these specific types of 3DS error don’t show anything.

As a “Drop-In” we expected all errors to be surfaced to the customer, especially as:
1.	We have no control over the elements hosted in the iframe.
2.	All the documentation says about the error parameter of the `requestPaymentMethod` callback is “The first argument will be an error if no payment method is available and will otherwise be null”. Inferring what each error object means would seem to be beyond the public API surface.

**Comment by memblin-taurus** [comment]
Hi any update on this? We are seeing complaints about this also from some customers.

**Comment by capelito** [comment]
Hi, 
we also often get feedback from customers that this is very confusing. We didn't know where the problem was at first because we didn't expect the Dropi-in not to display the corresponding error messages.
Thanks

**Comment by crookedneighbor** [comment]
After talking with the 3ds team further, it seems like we've got 2 paths forward here. Either we:

1) pass an error to `requestPaymentMethod` when this error occurs (meaning y'all would handle displaying to the customer that some kind of error occurred)
2) we return the customer to the card form with some generic error message displayed to them about how verification failed

I _think_ option 2 is the more user friendly version of this. (and we can add an event that emits when this happens so it can still be logged if desired on y'all's end)

**Comment by memblin-taurus** [comment]
Thanks for the update. I agree option 2 is more user friendly and is the behavior I would expect from the drop-in - handling all validation and error states as a self contained component. 

What's the approx ETA on this?

**Comment by crookedneighbor** [comment]
This is out in v1.29.0
