### ISSUE TITLE
Missing Paypal CSP rules

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree-web-drop-in#697]
### General information

* SDK/Library version: 1.26.0
* Environment: Sandbox
* Browser and OS: Chrome/Windows 10

### Issue description

Adding the CSP rules from the `PayPal Specific Directives`  https://braintree.github.io/braintree-web-drop-in/docs/current/#browser-support results in the following 2 CSP errors when PayPal is enabled in the dropin:

```
Refused to load the image 'https://t.paypal.com/ts?...' because it violates the following Content Security Policy directive: "img-src 'self' checkout.paypal.com".
```

```
Refused to connect to 'https://www.paypal.com/xoplatform/logger/api/logger' because it violates the following Content Security Policy directive: "connect-src 'self'".
```

Possibly the docs need the `img-scr` changed to `*.paypal.com` and a `connect-src` policy added to `*.paypal.com`?

**Comment by crookedneighbor** [comment]
Thanks for bringing this up, we'll get it fixed up. (if you'd like to open a PR, go for it)
