### ISSUE TITLE
Race condition in Dropin._setUpDependenciesAndViews

### ISSUE THREAD

**Issue by vaultwiki** [braintree/braintree-web-drop-in#700]
* Version: 1.26.1
* Environment: Sandbox
* Browser and OS: Chrome 87.0.4280.66 on Windows 10

### Issue description
This is a race condition, so it can be difficult to reproduce, but I've encountered it randomly in the past. Basically, sometimes the drop-in never finishes loading, or some parts of it are missing.

I first realized what was happening while looking at the code surrounding changes in another user's pull request, where I first commented about it.

As simply as I can describe, the problem is in
dropin.js _setUpDependenciesAndViews:

Designed flow
1. setupDataCollector -> dependenciesInitializing +1, 
2. setup3DSecure -> dependenciesInitializing + 1.
3+. mainView -> basically each payment option therein increases dependenciesInitializing further.

The problem is that each of these steps calls asyncDependencyReady whenever its promise happens to resolve. asyncDependencyReady reduces dependenciesInitializing by 1, and if it hits zero fires the asyncDependenciesReady event. 

Although we expect the event to fire *after* all these steps, it can occur *between* any of these steps (our race condition). Depending which ones we're currently between, we can have a situation where the drop-in never finishes loading (a behavior I've encountered), because when the asyncDependenciesReady event fires, some of the callbacks have code that expects the others to be ready at that time (commonly mainView is still undefined).

I have fixed this issue on my fork. Unfortunately I forgot to branch away from master a few days ago, so for now I can only show you the differences for the fixed files versus a complete pull request, unless you know how to do a pull request only spanning a few commits:
https://github.com/vaultwiki/braintree-web-drop-in/compare/master...vaultwiki:asyncdependencyfix

You'll note in the very top change I issue a warning. That basically if any asyncDependencyReady/asyncDependencyFailed call is not handled per the fix (e.g. in other forks, future code, etc), then the race condition will automatically trigger 100% of the time, and the drop-in never finishes loading. So I'm not sure how you want to handle this, as it could be a breaking change. Theoretically this could be fixed without introducing a breaking change, but it would require a major rewrite to the way payment methods are instantiated (they would need to be created before being added to the view, and added to the view when asyncDependenciesReady fires).

**Comment by crookedneighbor** [comment]
Thanks for the info, we'll take a look!

**Comment by crookedneighbor** [comment]
Fixed in the repo, but it's not been released yet. Re-opening this issue until the sdk is actually released.

**Comment by jplukarski** [comment]
This should be fixed in version 1.27.0.
