### ISSUE TITLE
Very slow creation of Dropin UI (~ 22 seconds)

### ISSUE THREAD

**Issue by ShaunDychko** [braintree/braintree-web-drop-in#715]
### General information

* SDK/Library version: 1.27.0
* Environment: Both
* Browser and OS Firefox 87.0 on MacOS 10.15.7

### Issue description

Loading the Dropin UI using Firefox can take either around 22 seconds (not a typo) or it goes quickly at around 2 seconds. A short load time usually follows a long load time. The Dropin hangs on an OPTIONS call to payments.braintree-api.com where it loads `graphql`. This is from the Network tab of the Firefox developer tools attached below. If you need further information, please don't hesitate to ask.

Using Safari and Chrome don't present this problem.
<img width="1679" alt="Screen Shot 2021-03-23 at 4 57 57 PM" src="https://user-images.githubusercontent.com/235214/112243853-86430480-8c0b-11eb-9e0f-5f4fc2fffa07.png">

**Comment by crookedneighbor** [comment]
We're looking in our logs to see if we can find anything. To help us narrow down our search, do you have a timeframe when you were doing this testing?

We were unable to reproduce it on our side. Can you reproduce it on our demo app? https://braintree.github.io/braintree-web-drop-in/

Are you using a client token or a tokenization key? (the demo link above is using a tokenization key)

**Comment by ShaunDychko** [comment]
I was testing from noon until 4:30PM PDT yesterday, and the problem also exists now (1:32 PM PDT Mar. 24th). I've attached a screenshot of the Network tab from the Firefox developer console below when visiting the demo app two times. The issue is peculiar since it isn't reliably reproducible. After waiting the ~22 seconds for an initial load, it sometimes (but now always) works fine on page refresh - even after clearing all cookies/data from the browser or using a new Private Window. The issue will then pop up again some time later.

I'm using `\Braintree\ClientTokenGateway::generate($payload)`, sometimes with `'customerId'` set, but usually not. Does that answer your question? 

<img width="1671" alt="Screen Shot 2021-03-24 at 1 28 29 PM" src="https://user-images.githubusercontent.com/235214/112379252-2a2cbe80-8ca5-11eb-9f8b-ad0dfead817b.png">
<img width="1677" alt="Screen Shot 2021-03-24 at 1 37 33 PM" src="https://user-images.githubusercontent.com/235214/112380074-2cdbe380-8ca6-11eb-8489-129e8b864a1e.png">

**Comment by ShaunDychko** [comment]
I'm also seeing a load time issue with Safari and Chrome and also in production. The screenshot shows assets sorted by load time from Safari on the demo app, and also from Chrome in my production application.
<img width="1574" alt="Screen Shot 2021-03-24 at 1 59 27 PM" src="https://user-images.githubusercontent.com/235214/112382580-429ed800-8ca9-11eb-815a-0f22a6760087.png">

<img width="1474" alt="Screen Shot 2021-03-24 at 1 54 27 PM" src="https://user-images.githubusercontent.com/235214/112382094-a8d72b00-8ca8-11eb-8f60-637e57cc705e.png">

**Comment by ShaunDychko** [comment]
A perplexing finding is that if I tether to my cell phone data plan the load time is OK. Sorry if I've caused undo alarm as this seems to be an ISP issue, although my internet connection speed test shows ~17 Mbps, which is decent, and the issue is with loading only specific resources... 
If you want to close this issue, I understand, but if you want me to test anything further in case other users have similar ISP issues just let me know.

**Comment by ShaunDychko** [comment]
I found this in the Console when visiting https://braintree.github.io/braintree-web-drop-in/ using Firefox:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://payments.sandbox.braintree-api.com/graphql. (Reason: CORS request did not succeed).`

**Comment by crookedneighbor** [comment]
Are you using any tooling that would proxy the requests? We got an issue earlier today re: the tool Fiddler that prevented requests entirely to the Braintree APIs (https://github.com/braintree/braintree-web/issues/562)

**Comment by ShaunDychko** [comment]
That's a good suggestion, but no, I'm not using anything like that. Furthermore I found the same issue yesterday when using a  different personal-use computer, so I'm thinking it must have something to do with our ISP. It's hard to make a clear conclusion though since a speed test shows a download speed of ~80 Mbps which should be more than enough. In any case, I'm not seeing the issue today for some reason... so I guess this issue can be closed unless you want me to look at anything else.

**Comment by crookedneighbor** [comment]
Thanks for following up. If you can find a pattern or a way to make it reproducible, happy to take a look. ~22 seconds to load is definitely not acceptable.

**Comment by zpyoung** [comment]
@crookedneighbor At the risk of resurrecting a closed issue, I found a pattern for this (at least for me). I use Speedify for channel bonding and as a VPN. When using Speedify, I can consistently cause the graphql call by the dropin to hang (same with hosted fields). The call will sometimes hang until the call times out at 60 seconds. If I turn off Speedify, it works normally.

Seems like my issue is :
- maybe related to using a VPN in general with the dropin?
- maybe related to the trustworthiness of the VPN?
- maybe related to the channel bonding?

I've seen the behavior both for me and another developer using Speedify.

**Comment by crookedneighbor** [comment]
Sorry for the late reply on this, but I would definitely reach out to Speedify about this issue.
