### ISSUE TITLE
I have no way to manage which payment method I want to make as default in the vault list

### ISSUE THREAD

**Issue by markos0886** [braintree/braintree-web-drop-in#719]
### General information

* SDK/Library version: 
* Environment: Sandbox
* Chrome 89.0.4389.90 (Official Build) (64-bit) on Windows 10.12.3

### Issue description
Hello, I am writing to you because I am having problems implementing a simple logic with the braintree dropin and I would like to know if it really supports what I need to do at the moment.
Attached I send 2 images, the first one is that I have some payment methods (vaulted) configured, selected by default the first one that was added appears.
But in the second image when I select another configured method and I make click in save, it does not set it as the default payment method, which represents a problem, and with the information sent by the payload it is not enough to update a payment method, only the information comes del nonce, but nevertheless I have selected a payment method visually that is not by default after doing save.
Is there a way to get enough to be able to update a payment method on the server side, like the token for example?
Or, does dropin have any configuration or method where it defaults to the selected payment method? This is essential if there can be several methods configured. I couldn't find any answer in the dropin documentation, nor in the Braintree API.

Best Regards

**Image 1.**
![1 saved methods](https://user-images.githubusercontent.com/17881419/114081937-3145f600-987b-11eb-8e32-9cce68efefa7.png)

**Image 2.**
![2 trying save to default](https://user-images.githubusercontent.com/17881419/114081941-31de8c80-987b-11eb-9beb-bcfb5ae4fb44.png)

**Comment by crookedneighbor** [comment]
:wave: You can't make that change from within Drop-in. For this, you'll have to first get the associated payment method object on your server, using the `PaymentMethod.create` method in your server sdk: https://developers.braintreepayments.com/reference/request/payment-method/create

If the nonce represents an un-vaulted payment method, calling `create` will create a new one. If the nonce represents an already vaulted payment method, calling `create` will instead return the payment method associated with the nonce. 

From there, you can take the token from the payment method and perform an update on it to make it the default: https://developers.braintreepayments.com/reference/request/payment-method/update/#options.make_default

If you need additional help, please reach out to our support team: https://help.braintreepayments.com/
