### ISSUE TITLE
Build Error on windows machines

### ISSUE THREAD

**Issue by ByungkwonJeon** [braintree/braintree-web-drop-in#72]
Hi There, 

Could you please help me what problem is? I can't build this. 

C:\workspace\parmica_new\braintree-web-drop-in>npm run build

> braintree-web-drop-in@1.0.0-beta.4 build J:\workspace\parmica_new\braintree-web-drop-in
> gulp build

[10:31:18] Using gulpfile J:\workspace\parmica_new\braintree-web-drop-in\gulpfile.js
[10:31:18] Starting 'build'...
[10:31:18] Starting 'clean'...
[10:31:18] Finished 'clean' after 4.39 ms
[10:31:18] Starting 'build:js:unmin'...
[10:31:18] Starting 'build:js:min'...
[10:31:18] Starting 'build:css'...
[10:31:18] Starting 'build:jsdoc'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn bash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Windows_NT 10.0.14393

Thanks,

**Comment by lilaconlee** [comment]
Thank you for reporting this! We'll take a look at these build issues as we get out of beta and have more time to make sure the project is easy to work on for external devs.

If you're not looking to contribute to `braintree-web-drop-in`, you can include the already built file in your project with a script tag like this:
```
  <script src="https://js.braintreegateway.com/web/dropin/1.0.0-beta.4/js/dropin.min.js"></script>
```
Drop-in will also be available to include via npm in the near future.

**Comment by crookedneighbor** [comment]
Looks like this is the offending line: https://github.com/braintree/braintree-web-drop-in/blob/b91c5d8c394ceec452c34edba18c800501a590df/gulpfile.js#L107

**Comment by EvanHahn** [comment]
It [looks like](https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback) Node has some issues with symlinking on Windows.

**Comment by juongithub** [comment]
Actually the error you are reporting means that, on Windows, npm cannot find bash (that is a Linux command). I suggest to edit gulpfile.js and to change the line:

`spawn('bash', ['-c', args.join(' ')], { [...]`

with lines:

```
var command = 'bash', opt = '-c';
  if (process.platform.indexOf('win')>=0) {
      command = 'cmd';
      opt = '/c';
  }
  spawn(command, [opt, args.join(' ')], { [...]
```

**Comment by crookedneighbor** [comment]
@juongithub Do you want to open a PR?

**Comment by juongithub** [comment]
Yes, I'm opening a PR

**Comment by juongithub** [comment]
Ok, I'm not able to open a PR... any advice?

**Comment by crookedneighbor** [comment]
What do you mean that you aren't able to open a PR?

**Comment by juongithub** [comment]
I'm not familiar to github, I'm not able to commit the new file.

**Comment by crookedneighbor** [comment]
Here is the Github help article for creating a pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by crookedneighbor** [comment]
You will first need to fork the repo so you have your own copy of the repo on Github. https://help.github.com/articles/fork-a-repo/

**Comment by crookedneighbor** [comment]
I will try out your change later today or tomorrow, but if you'd like to still open a PR before I get to it, feel free.

**Comment by juongithub** [comment]
Just created a PR, thanks :)

**Comment by crookedneighbor** [comment]
The symlink error I posted earlier was because you need to run the command prompt as an administrator when on windows. I'll update the docs to indicate this.
