### ISSUE TITLE
Vertical scrollbar appearing for saved payment method

### ISSUE THREAD

**Issue by dereksdev** [braintree/braintree-web-drop-in#724]
### General information

* SDK/Library version: 1.27.0
* Environment:  Sandbox (maybe Production?)
* Browser and OS: Chrome 90.0.4430.85/Windows 10

### Issue description

A vertical scrollbar appears in saved payment method next to the checkmark on the right side of the label. Removing the `overflow-x: hidden;` CSS rule resolves the issue, but not sure why it is there in the first place.

![scrollbars](https://user-images.githubusercontent.com/4105471/115933271-650c4880-a443-11eb-82a4-bf5d83cea341.png)

**Comment by crookedneighbor** [comment]
Thanks for the report, we'll look into it.

**Comment by crookedneighbor** [comment]
This is out in v1.28.0
