### ISSUE TITLE
Typescript: Subsequent variable declarations

### ISSUE THREAD

**Issue by saadrawasia** [braintree/braintree-web-drop-in#725]
### General information

* SDK/Library version: 1.27.0
* Environment: Sandbox (maybe Production?)
* Browser and OS: Mac OS

### Issue description

I am using react and typescript. Whenever I run npm run start it shows the error that I have to install @types/braintree-web-drop-in. After installing that when I run npm run start it shows the following error: 

ERROR in /../frontend/node_modules/@types/braintree-web-drop-in/index.d.ts(259,11):
259:11 Subsequent variable declarations must have the same type.  Variable 'braintree' must be of type 'typeof import("/../frontend/node_modules/@types/braintree-web/index")', but here has type '{ dropin: { create(options: Options, callback: (error: object | null, dropin: Dropin | undefined) => void): void; create(options: Options): Promise<Dropin>; }; }'.
    257 | 
    258 | declare global {
  > 259 |     const braintree: {
        |           ^
    260 |         dropin: {
    261 |             create(options: Options, callback: (error: object | null, dropin: Dropin | undefined) => void): void;
    262 |             create(options: Options): Promise<Dropin>;

I am unable to resolve the issue.

**Comment by crookedneighbor** [comment]
We do not maintain those type definitions.

The next major version of the core SDK and Drop-in will be written in Typescript, so you will no longer need this 3rd party type definition.

In the meantime, you can either supply your own type definitions, or ignore typing concerns for the Braintree SDK.

**Comment by JustFly1984** [comment]
@crookedneighbor  Do you have estimates on new version release?

**Comment by crookedneighbor** [comment]
I do not have an estimate yet. It's unlikely to be ready in the near future though. (first will come upgrading the core Braintree SDK that Drop-in uses internally to Typescript, then we can start the work of upgrading Drop-in to Typescript as well)
