### ISSUE TITLE
Inconcistency with 3d secure

### ISSUE THREAD

**Issue by antonisprovidakis** [braintree/braintree-web-drop-in#728]
### General information

* SDK/Library version: 1.26.1
* Environment: Sandbox
* Browser and OS Chrome 90.0.4430.85 (64-bit) on MacOS 10.15.7

### Issue description

3D Secure is not consistent when changing between some cards.

Even though I call:
```
instance.requestPaymentMethod({
  threeDSecure: {...data}
})
```
which means 3dsecure flow must run when changing to another card, that's not the case. For some reason, it is bypassed.

Specifically, I've noticed this for the card: [`4009348888881881`](https://developers.braintreepayments.com/guides/credit-cards/testing-go-live/ruby#test-value-4009348888881881). There might be other cards too that have the same behavior.

So, let's say that the currectly active card is XXX.
Either I add the card 4009348888881881 as a new one, or the 4009348888881881 is already added to the vault and I'm just selecting that one, and then call `requestPaymentMethod`, the 3dsecure flow does not run.

Is it something specific to the sandbox? Or is there some check that happens at the backend that bypasses the 3dsecure flow, maybe?

**Comment by crookedneighbor** [comment]
Only cards specifically enabled for 3ds will trigger the 3ds flow. In sandbox, these are the test cards: https://developers.braintreepayments.com/guides/3d-secure/testing-go-live/
