### ISSUE TITLE
Apple pay icon doesn't change to click cursor on hover - Safari desktop

### ISSUE THREAD

**Issue by splitmyfare** [braintree/braintree-web-drop-in#737]
### General information

* SDK/Library version: ^1.27.0
* Environment: Sandbox
* Browser and OS: Safari Version 14.1 (16611.1.21.161.6), Mac OS 11.3.1 (20E241)

### Issue description

The apple pay icon doesn't change to a "click" cursor when hovering over apple pay on the dropin ui, google pay works fine. Recording: https://share.getcloudapp.com/ApuY41jQ

**Comment by crookedneighbor** [comment]
Thanks for the heads up! This is fixed on `main` and will go out in the next release.
