### ISSUE TITLE
Cancelling 3D secure window adds 2 polluted back pages to the window

### ISSUE THREAD

**Issue by splitmyfare** [braintree/braintree-web-drop-in#738]
### General information

* SDK version: ^3.76.3
* Environment: Sandbox
* Browser and OS: Chrome Version 91.0.4472.77 (Official Build) (x86_64) Mac OS 11.3.1 (20E241)

### Issue description

Whenever the DropinUI 3D secure window is cancelled it adds 2 polluted back pages to the window. This happens on the official example here:
https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3

It does not happen on firefox

**Comment by crookedneighbor** [comment]
This is just a result of how iframes work in some browsers, unfortunately. Since the iframes do some posting and redirecting, it can pollute the history on the window for some browsers.

I've looked into some workarounds for this, but haven't been able to find anything that works particularly well.
