### ISSUE TITLE
The paymentOptionPriority with single option causes endless loading-indicator

### ISSUE THREAD

**Issue by andrew-itscript** [braintree/braintree-web-drop-in#739]
### General information

* SDK/Library version: ^1.27.0
* Environment: both Sandbox and Production
* Browser and OS: Any

### Issue description

In custom UI of checkout where different payment providers are used it's useful to create braintree web dropin instance just with one payment option selected  (selected in the list of buttons which represent different payment options from different solution providers e.g. Braintree, Adyen, Amazon etc). In versions prior 1.27.0 it was possible to set paymentOptionPriority = ['supportedOption'], but from version 1.27.0 we started to see endless loading-indicator without any error details.

[Documentation](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create) says 

> Use this option to indicate the order in which enabled payment options should appear when multiple payment options are enabled. By default, payment options will appear in this order: ['card', 'paypal', 'paypalCredit', 'venmo', 'applePay', 'googlePay']. **Payment options omitted from this array will not be offered to the customer.**

Please check next codepen links:
- [version 1.26.0](https://codepen.io/iao/pen/MWpOdGG)
- [version 1.27.0](https://codepen.io/iao/pen/OJpOYZb)

**Comment by andrew-itscript** [comment]
@crookedneighbor Have you had a chance to check the issue?

**Comment by crookedneighbor** [comment]
I have not yet, I as hoping to get to it today. I have a hunch about what went wrong here.

**Comment by andrew-itscript** [comment]
Great stuff. When do you plan to publish changes?

**Comment by crookedneighbor** [comment]
Hoping to get it out next week. I'll re-open this issue until it actually gets released.

**Comment by crookedneighbor** [comment]
This is fixed in v1.30.0
