### ISSUE TITLE
"Choose another way to pay" option

### ISSUE THREAD

**Issue by beworker** [braintree/braintree-web-drop-in#74]
Guys, after adding a credit card there is an option "Choose another way to pay" popping up in the UI. Is it possible to somehow avoid it? Thanks!

**Comment by lilaconlee** [comment]
We include the "Choose another way to pay" toggle to give users the opportunity to update their card details, but if you'd rather not show it you can add this to your css: 

```css
[data-braintree-id="toggle"] {
  display: none;
}
```

We may update our design or the `data-braintree-id` elements while we're in beta, so you'll want to make sure this fix still works any time you update the version.

For a full example, check out [this codepen](http://codepen.io/lilaconlee/pen/wJvdME).
