### ISSUE TITLE
Auto proceeding on the selection of apple pay or google pay.

### ISSUE THREAD

**Issue by adamwpe** [braintree/braintree-web-drop-in#743]
Hi All,

We getting a few customers who select 'Apple Pay' or 'Google Pay' - their phone makes a noise to confirm the selection of the payment (at least for apple pay) - thinking payment was successful. So they basically never press the submit button.

![image](https://user-images.githubusercontent.com/49768920/122073600-71cc6d80-cdf0-11eb-8262-500d19ecd1e1.png)

Has anyone also faced this issue? 

Maybe a redesign of my page might help, like fading the Braintree Drop in UI.
 
There are some Braintree events 'paymentMethodRequestable', 'noPaymentMethodRequestable' that I could utilise to try and auto submit - but that's quite risky.

Thanks,
Adam

**Comment by crookedneighbor** [comment]
> There are some Braintree events 'paymentMethodRequestable', 'noPaymentMethodRequestable' that I could utilise to try and auto submit - but that's quite risky.

Can you explain why this is risky? Those events were created exactly for this use case.

**Comment by crookedneighbor** [comment]
I don't see any drawbacks. Apple Pay and Google Pay typically want their flow to be the final thing that happens before authorization, so I think that makes sense. Really, it's only the card form that would be risky to auto-submit.
