### ISSUE TITLE
Problem with requestPaymentMethod

### ISSUE THREAD

**Issue by laurib** [braintree/braintree-web-drop-in#748]
### General information

* SDK/Library version: 1.30.0
* Environment: Production
* Browser and OS Chrome 91.0.4472 on Windows 10

### Issue description
Got an error when client did `requestPaymentMethod` : Something went wrong during 3D Secure authentication.

![Screenshot 2021-06-30 at 11 47 53](https://user-images.githubusercontent.com/1352991/123931720-73259a80-d999-11eb-8b20-9161c38a7e39.png)

**Comment by jplukarski** [comment]
Is this happening every time you call `requestPaymentMethod`, just for one customer, or sporadically?

Are you able to provide a staging site and steps to reproduce the issue? If you do not want to share your staging site publicly, we recommend [contacting our Technical Support Team](https://developer.paypal.com/braintree/help) along with a detailed description of your issue.

**Comment by laurib** [comment]
It is not happening every time. In fact it is like rare case and currently I see that it is happening to only one of our client. 
Unfortunately i don't have more information to reproduce this issue with steps.

**Comment by jplukarski** [comment]
Thank you for that clarification. It's worth noting that this error occurs when something went wrong during 3DS authentication, and does not necessarily indicate something wrong with the Drop-in. For this reason, I suggest [reaching out to our support team](https://developer.paypal.com/braintree/help) for further troubleshooting. In your request, please include a detailed description of your issue including the browser your client is using, timestamps (including timezone), and your [Braintree Merchant ID](https://developer.paypal.com/braintree/articles/control-panel/important-gateway-credentials#merchant-id)
