### ISSUE TITLE
Issue with reloading Dropin with different payment methods

### ISSUE THREAD

**Issue by kinowashere** [braintree/braintree-web-drop-in#749]
### General information

* SDK/Library version: 1.30.1
* Environment: Sandbox
* Browser and OS: Firefox 89.0.2 in Mac OS 11.4 and Safari 14.1

### Issue description

1. Try to `dropIn.create()` with, for example, `paypal = { ... }` and Credit Card
2. `dropIn.create()` again but just with Credit Card
3. `dropIn.create()` once again but add `paypal = { ... }` with Credit Card
4. You will only get Credit Card and PayPal will not show, despite the fact that you requested it.

This happens whether you reload the window or not. It seems like you have a timeout to get PayPal back again. It happens with `applePay = { ... }` as well. The issue also happens if you always try to `dropIn.create()` with `paypal = { ... }` and Credit Card, but instead switch `paymentOptionPriority = ['paypal', 'card']` to `paymentOptionPriority = ['card']` and back again. If you try to just`paymentOptionPriority = ['paypal']` after `paymentOptionPriority = ['card']` you'll get an error saying that `DropinError: No valid payment options available`.

I think this is related to the server not wanting to give different payment methods rather than the FE implementation of this repo. Still gotta ask whether this behaviour is supported or if it's an issue.

**Comment by crookedneighbor** [comment]
Do you have a staging site or github repo that reproduces this behavior? Are you calling `teardown` in between creating the new Drop-in instances?

**Comment by crookedneighbor** [comment]
I don't think I understand why you are creating an apple pay instance using the underlying `braintree-web` sdk. Why aren't you just creating it within the drop-in create configuration?

You can see here that the SDK is calling `createPaymentRequest` with your `paymentRequest` configuration. https://github.com/braintree/braintree-web-drop-in/blob/10f124d3022ca3361988aa60303ebf4ad760cedf/src/views/payment-sheet-views/apple-pay-view.js#L56

**Comment by kinowashere** [comment]
Heh, I was following the docs from `ApplePay.js` or something like that, completely forgot I can use the sdk for that. 

I don't think that's the cause of the issue though, since it happens as well with PayPal. But thanks for the note, will look into that.

**Comment by crookedneighbor** [comment]
I also don't think that's causing the issue, and we'll try to reproduce it with what you've given us. Just looking to simplify the integration if possible.

There's likely a bug in the `paymentOptionPriority` bit on our end. If you omit that and instead only set `createProperties` to have the configurations for the payment options you want to support (this will likely require you to set `card: false` in the `createProperties`, since that's enabled by default), I believe it will work.

**Comment by kinowashere** [comment]
Actually, that's how I started to implement this. `createProperties` used to have only the payment method we needed with `card` set to `false`. However, when switching from Card to Apple Pay the issue occured. Dummy me didn't want to make the post longer than it already is, but feels like I should have mentioned that as well.

**Comment by crookedneighbor** [comment]
On our demo app, we have query parameters that let us enable/disable payment methods. For instance, this one disables all payment methods except for PayPal and card: https://braintree.github.io/braintree-web-drop-in/?applePay=null&venmo=null&googlePay=null&paypalCredit=null

This one does the same thing and sets the paymentOptionPriority to put PayPal first, and card second: https://braintree.github.io/braintree-web-drop-in/?applePay=null&venmo=null&googlePay=null&paypalCredit=null&paymentOptionPriority=[%22paypal%22,%22card%22]

This one uses `paymentOptionPriority` to only display PayPal: https://braintree.github.io/braintree-web-drop-in/?applePay=null&venmo=null&googlePay=null&paypalCredit=null&paymentOptionPriority=[%22paypal%22]

This one omits card to only display PayPal: https://braintree.github.io/braintree-web-drop-in/?applePay=null&venmo=null&googlePay=null&paypalCredit=null&card=false

For each of these, I'm experiencing no issues. Are you having issues loading Drop-in on that demo site with your device/browser? 

It would be helpful if you could create a simple repo or staging site that does reproduce the issue you are seeing so we can dig into it.

**Comment by crookedneighbor** [comment]
Thank you for the video you sent, I still need some way to reproduce it on my end.

**Comment by kinowashere** [comment]
Hi. I've sent you via email some credentials and a link to test the issue out.

**Comment by crookedneighbor** [comment]
I tried the test site, but after I logged and and chose "cart", I see:

> Ooops!
Something went wrong!

**Comment by kinowashere** [comment]
Fixed that cart issue. Sorry for the wait.

**Comment by crookedneighbor** [comment]
OK, I see the problem now. You're not waiting for the modifications to the `createProperties` to be completed before creating the Drop-in instance. Basically, you're modifying the `createProperties` after creating a Braintree client instance and Apple Pay instance, which means that the version of the object that gets passed into `dropin.create` does not have those modifications yet. Sometimes they get applied, because the object is mutated before they are accessed in the Drop-in create code, but sometimes they don't so Drop-in is created with an object that does not have PayPal/Apple Pay applied and `card` set to `false`. 

You shouldn't even be using `braintree-web` in conjunction with Drop-in, so by simply removing the extra `braintree-web` code, you can solve your problem.

Here is the code you have on your site right now:

```javascript
    async create(paymentMethod, availableMethods, paymentConfig) {
        const { default: dropIn } = await import('braintree-web-drop-in');
        const { default: braintree } = await import('braintree-web');
        const authorization = await this.requestBraintreeClientToken();
        const configuration = await this.requestBraintreeConfig();

        // TODO: Remove for now, waiting for Braintree team to confirm implementation below
        // const braintreeAvailableMethods = availableMethods.filter((item) => BRAINTREE_METHODS.includes(item.code));
        // eslint-disable-next-line fp/no-let
        let applePayLabel = '';
        if (paymentMethod === APPLE_PAY) {
            applePayLabel = await this.requestApplePayMerchantName();
        }
        this.isThreeDSecure = configuration.is_three_d_secure;
        const createProperties = {
            authorization,
            container: `#${ this.containerId }`,
            threeDSecure: this.isThreeDSecure
        };

        braintree.client.create({ authorization }, (clientError, clientInstance) => {
            if (clientError) {
                return;
            }

            switch (paymentMethod) {
            case APPLE_PAY:
                braintree.applePay.create({ client: clientInstance }, (applePayErr, applePayInstance) => {
                    if (applePayErr) {
                        return;
                    }
                    const paymentRequest = applePayInstance.createPaymentRequest({
                        total: {
                            label: applePayLabel.braintree_applepay_merchant_name,
                            amount: paymentConfig.grandTotal
                        }
                    });

                    createProperties.applePay = {
                        displayName: applePayLabel.braintree_applepay_merchant_name,
                        paymentRequest
                    };
                });
                break;
            case PAYPAL:
                createProperties.paypal = {
                    checkout: 'flow',
                    amount: paymentConfig.grandTotal
                };
                break;
            default:
            }
        });

        if (paymentMethod !== BRAINTREE) {
            createProperties.card = false;
        }

        // TODO: We need to keep it for Braintree team to check
        // eslint-disable-next-line no-console
        console.log(createProperties);
        this.braintreeDropIn = await dropIn.create(createProperties);

        return true;
    }
```


You can change it to this, and it should just work:

```javascript
async create(paymentMethod, availableMethods, paymentConfig) {
  const { default: dropIn } = await import('braintree-web-drop-in');
  const authorization = await this.requestBraintreeClientToken();
  const configuration = await this.requestBraintreeConfig();

  // TODO: Remove for now, waiting for Braintree team to confirm implementation below
  // const braintreeAvailableMethods = availableMethods.filter((item) => BRAINTREE_METHODS.includes(item.code));
  // eslint-disable-next-line fp/no-let
  let applePayLabel = '';
  if (paymentMethod === APPLE_PAY) {
    applePayLabel = await this.requestApplePayMerchantName();
  }
  this.isThreeDSecure = configuration.is_three_d_secure;
  const createProperties = {
    authorization,
    container: `#${ this.containerId }`,
    threeDSecure: this.isThreeDSecure
  };

  switch (paymentMethod) {
    case APPLE_PAY:
      const paymentRequest = {
        total: {
          label: applePayLabel.braintree_applepay_merchant_name,
          amount: paymentConfig.grandTotal
        }
      };

      createProperties.applePay = {
        displayName: applePayLabel.braintree_applepay_merchant_name,
        paymentRequest
      };
      break;
    case PAYPAL:
      createProperties.paypal = {
        checkout: 'flow',
        amount: paymentConfig.grandTotal
      };
      break;
    default:
  }

  if (paymentMethod !== BRAINTREE) {
    createProperties.card = false;
  }

  // TODO: We need to keep it for Braintree team to check
  // eslint-disable-next-line no-console
  console.log(createProperties);
  this.braintreeDropIn = await dropIn.create(createProperties);

  return true;
}
```

Since this isn't an issue with the Drop-in, if you need further assistance with your integration, please reach out to our support team. https://developer.paypal.com/braintree/help
