### ISSUE TITLE
3DS “This content is blocked. Contact the site owner to fix the issue.”

### ISSUE THREAD

**Issue by ChrisHSandN** [braintree/braintree-web-drop-in#755]
### General information

* SDK/Library version: 1.30.1
* Environment: Production
* Browser and OS: Chrome Version:91.0.4472 Windows 10

### Issue description

We have had a number of reports from a small subset of users that during the 3DS flow the end result is a `This content is blocked. Contact the site owner to fix the issue.`.

I first suspected something on our end but seeing the screenshots (posted below) shows that the issue occurs within the 3DS modal which the DropIn popups, and hence is nothing under our control.

The error object returned to the `requestPaymentMethod()` contains only the following generic sounding messages:
```js
{
  'braintreeWebError.code'': 'THREEDS_CARDINAL_SDK_ERROR',
  'braintreeWebError.details.originalError.code': 10004,
  'braintreeWebError.details.originalError.description': 'A general error has occurred.',
  'braintreeWebError.message': 'A general error has occurred with Cardinal. See description for more information.',
  'braintreeWebError.name': 'BraintreeError',
  'braintreeWebError.type': 'UNKNOWN',
  'message': 'Something went wrong during 3D Secure authentication. Please try again.',
}
```

Also (but possibly a red-herring), during failed 3DS flows I note there are often a variation of lots of the following messages logged to the console by `PostMessageHandler` which seems to be something coming from the `songbird.js` file.

```js
{
  arguments: [
    Base.Events.PostMessageHandler: Unable to parse reponse [[object Object]] SyntaxError: Unexpected token o in JSON at position 1
  ], 
  logger: console
}
```

```js
{
  arguments: [
    Base.Events.PostMessageHandler: Unable to parse reponse [JTdCJTIydGFyZ2V0SWQlMjIlM0ElMjJNZXNzYWdlLlRvcEZyYW1lJTIyJTJDJTIybWVzc2FnZUlkJTIyJTNBJTIyRnJhbWVSZWFkeSUyMiUyQyUyMnNlbmRlcklkJTIyJTNBJTIyTWVzc2FnZS5GcmFtZS5kZmViNjZjOTFlYmUlMjIlN0Q=] SyntaxError: Unexpected token J in JSON at position 0
  ], 
  logger: console
}
```

We have not been able to reproduce the issue on sandbox or production ourselves.

![image](https://user-images.githubusercontent.com/13466620/127351948-de0279dc-6c9a-4db6-af15-d1b854321310.png)
![image](https://user-images.githubusercontent.com/13466620/127352068-412d77b2-cf68-4d7c-ade8-0fc5850ccb79.png)
![image](https://user-images.githubusercontent.com/13466620/127351706-e4c526a4-d497-4ac8-8ea5-d8b1b03bd420.png)

**Comment by crookedneighbor** [comment]
Thanks for the info. I'll pass this report on to our 3D Secure team and try to get an answer.

**Comment by crookedneighbor** [comment]
Do you know if these are all Visa cards that are having this issue? Or is it happening across card brands? Any other patterns with the failed requests?

**Comment by ChrisHSandN** [comment]
We have 2 confirmed (by screenshot) users with this “content blocked” issue. Without contacting them I can’t be sure what their card is but both are UK based and have previous expired vaulted VISA cards as their default payment method.

There are 6 others I have been able to cross reference in our logs for the last month with a cardinal 10004 general error, but they seem to be a mix of VISA and MasterCard.

**Comment by crookedneighbor** [comment]
Do you have timestamps for these events? That will help us track down what's going on. We'll likely have to pass the url of the bank in the 3ds modal to our MPI provider so they can investigate further.

**Comment by crookedneighbor** [comment]
It'd be ideal to get a payment method nonce for the affected customers, but since the error happens in the 3ds modal _after_ the initial 3ds authentication, I'd imagine it'd be difficult to correlate the nonce with the customer.

**Comment by ChrisHSandN** [comment]
One of them occurs on: 

* Timestamp: `Jul 16, 2021 5:20:57 PM UTC`
* Merchant ID: `dkgsx5wjkzf5gbm5`
* Users IPv4 address block: `81.0.0.0/8`

I regards to the payment method nonce, the callback payload of `requestPaymentMethod()` was `undefined`.  I also checked BT admin but no payment methods were vaulted for that customer on that date. I do have the following unique looking data logged from the front end which may help narrow it down?

* Component ID: `fc8a9200-4bc0-43f5-957b-daa50ad1a28d`
* analyticsMetadata.sessionId: `8e10f578-3f98-4310-b9ca-5a13b38acffa`

**Comment by ChrisHSandN** [comment]
As an update from our end, customers we were in contact with who were experiencing this issue have now been able to progress through the 3DS steps successfully. There also seems to be a dropoff in the requestPaymentMethod errors we are logging.

I’ll call that 'issue closed', but if you do hear back from the MPI it would be useful to know if they resolved a technical issue or this is just some coincidence.

**Comment by kylemacfarlane** [comment]
This started cropping up for us recently. Apparently 3DS2 iframes can be loaded from banks' own domains so the CSP needs changed to a wildcard domain.

The docs weren't updated until Jan 2022 so if you implemented 3DS2 earlier your CSP might be wrong: https://github.com/braintree/braintree-web-drop-in/pull/782/files
