### ISSUE TITLE
Prefilled Credit Card doesn't trigger event paymentMethodRequestable

### ISSUE THREAD

**Issue by andrew-ignatiev** [braintree/braintree-web-drop-in#761]
### General information

* SDK/Library version: ^1.31.1
* Environment: Sandbox and Production
* Browser and OS: Chrome 92.0.4515.131 (64-bit) on MacOS Big Sur 11.4

### Issue description

We use `clearFieldsAfterTokenization: false` to keep card data after call `clearSelectedPaymentMethod()` in error handler. We have noticed that after click on "new card" option the prefilled credit card form is being displayed correctly but it doesn't trigger the `paymentMethodRequestable` event, however the payment method is requestable. Can it be fixed to consolidate logic?

Please see attached example https://codepen.io/andrew-sp/pen/eYWxBoO

**Comment by crookedneighbor** [comment]
Thanks for reporting this! We have a fix PR'd here. https://github.com/braintree/braintree-web-drop-in/pull/763

Hoping to get a release out in the next few hours.

**Comment by crookedneighbor** [comment]
Re-opening this until we actually get the release out (should be soon).

**Comment by crookedneighbor** [comment]
Fixed in 1.31.2!
