### ISSUE TITLE
Webpack breaks paypal integration

### ISSUE THREAD

**Issue by kaitwalla** [braintree/braintree-web-drop-in#764]
### General information

* SDK/Library version: 1.31.2
* Environment: Sandbox
* Browser and OS: Windows 10, Firefox 91.0.2 and Chrome 92.0.4515.159

### Issue description
I attempted to use the drop-in UI for the platform we're building. Using the bog-standard config settings, I was able to get the buttons to load, but the Paypal option always said there was an issue. There were two errors in the console:

`Uncaught TypeError: invalid 'instanceof' operand HTMLElement validate.js:106:18`

and

`TypeError: global.paypal is undefined  dropin.js:16660:13`

I was able to narrow it down a problem with Webpack - this is on a Laravel site that uses Webpack Mix to transpile everything. When I left the barest script (console.log) that still loaded Webpack, I would receive the errors. When I left the script off and didn't have Webpack loaded, it worked perfectly. Please note that the script itself was not being called through webpack - it's loaded in via <script> tags on the page. I also tried compiling directly from the npm module, but had the same error.

I was able to find a workaround by including the PayPal v4 checkout.js script before calling the dropin script, which preloaded the global.paypal variable and avoided the issue. I'm not particularly enthralled by this as a long-term solution, however, owing to upgrades/changes would seem to have a high potential of breaking it.

**Comment by jplukarski** [comment]
Can you try adding `flow: 'vault'` to your [PayPal configuration object](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#~paypalCreateOptions)?

If that doesn't solve your issue are you able to provide a test site with steps to reproduce the issue so we can further troubleshoot?

**Comment by kaitwalla** [comment]
I did manage to resolve this, it was an overlapping set of problems with Typescript, not an underlying issue with your code. Apologies!
