### ISSUE TITLE
Feature request: enable customization of 3DS popup text (for subscription payment methods)

### ISSUE THREAD

**Issue by thijs** [braintree/braintree-web-drop-in#765]
### General information

* SDK/Library version: 1.31.2

### Issue

For our users we want to offer an option to change the payment method used to charge them for subscriptions. During the flow of adding a card using the braintree-web-drop-in we provide the (already known) 3DSecure data to `.requestPaymentMethod`. This however sometimes still pops up a 3DSecure OTP code form. This form contains the text (on sandbox, but production I assume is same or similar):

> You are paying Sandbox the amount of 99.00 using card ************0004.

However, at this time, there is **no** payment happening. So it would be good if this text could be customized, to avoid confusion for our customers.

**Comment by jplukarski** [comment]
Thanks for the suggestion, however, the [3DS challenge popups are provided by the issuing banks](https://developer.paypal.com/braintree/articles/guides/fraud-tools/3d-secure#processing) and therefore we have no control over the UI.
