### ISSUE TITLE
Asking for Street Address in dropin form

### ISSUE THREAD

**Issue by polgiron** [braintree/braintree-web-drop-in#768]
### General information

* SDK/Library version: any

### Issue description

Hey, I would like to know if there is any update regarding the support of asking for Street Address inside the dropin form?
I've stumbled uppon this issue from 2019 https://github.com/braintree/braintree-web/issues/475 FYI

**Comment by jplukarski** [comment]
Hello @polgiron, thank you for bringing this up. At this time we do not have an updated timeline for adding this support directly within the Drop-in. Our recommended solution, for now, is to collect address information outside of the Drop-in.

We do have a current issue open for this feature request, so I am going to close this issue for now. We will update Issue #486 once we are able to provide an update.
