### ISSUE TITLE
CSP inline styles

### ISSUE THREAD

**Issue by idontusenumbers** [braintree/braintree-web-drop-in#770]
### General information

* SDK/Library version: 1.31.2
* Environment: sandbox
* Browser and OS Microsoft Edge Version 93.0.961.52 (Official build) (arm64) on MacOS 11.6 (20G165)

### Issue description

I'm getting numerous (about 50 per page load) CSP errors because of inline styles. I'm self hosting the JS, it loads fine. As the script executes, it appears to attach styles. For example:

```
n._dropinWrapper.innerHTML = '<svg data-braintree-id="svgs" style="display: none">\n  
```

I understand `'unsafe-inline'` allows the code to run, but I'd prefer the safer CSP if possible.

**Comment by crookedneighbor** [comment]
Thanks for pointing this out! We'll see what we can do about the stuff that Braintree is responsible for. 

I do believe the PayPal SDK requires `unsafe-inline`, and there's nothing we can really do about that. So if you're using PayPal in your Drop-in integration, you will still need to include the `unsafe-inline` directive.

When Drop-in is updated to the newest version of the PayPal SDK, this should no longer be a problem, but as it will require some breaking changes to upgrade, it's a ways out.

**Comment by idontusenumbers** [comment]
While debugging the issue I found a few mentions of the PayPal SDK and pending update, though I'm just accepting credit cards.

**Comment by idontusenumbers** [comment]
> PRs are welcome here.

PR up: https://github.com/braintree/braintree-web-drop-in/pull/778

**Comment by idontusenumbers** [comment]
@crookedneighbor I forgot to add tests; though I'm not sure what the best option for a CSP test would be; they show up as warnings in Chrome/Edge when the content is requested. Are there integration tests that can test this?

**Comment by crookedneighbor** [comment]
If you want to open a PR in the publishing tests directory that makes sure that `style=` is not used in the HTML files, go ahead: https://github.com/braintree/braintree-web-drop-in/tree/main/test/publishing

A more comprehensive CSP test is probably a good idea, but the demo app in this repo is just a statically served HTML file, which makes including a CSP difficult.
