### ISSUE TITLE
Loading spinner is not centered

### ISSUE THREAD

**Issue by beworker** [braintree/braintree-web-drop-in#78]
<img width="105" alt="screen shot 2017-02-24 at 11 23 17" src="https://cloud.githubusercontent.com/assets/768721/23299992/eb791e52-fa83-11e6-8511-d4d00ba821ae.png">

As you can see in the attached image the loading spinner is slightly misplaced. It's not a big deal, but still looks weird.

Tested on Chrome version 56.0.2924.87 (64-bit)

**Comment by lilaconlee** [comment]
Thanks for reporting this! We're still actively working on our loading transitions but we'll make sure to take a look.

**Comment by crookedneighbor** [comment]
@beworker I have not been able to reproduce this on Chrome on a Mac or a Windows PC. Is it possible that some CSS on your page is affecting the style of the spinner?

**Comment by beworker** [comment]
I will check it out and let you know. Thanks for looking into the issue.

**Comment by crookedneighbor** [comment]
Let us know what you find out. It's possible that we need to adjust the CSS around the spinner to not be easily affected by a page's styling. If I had to guess, I'd say that you have some rules around how svgs behave.

**Comment by crookedneighbor** [comment]
I was able to reproduce this on a site using Semantic UI. Fixed.
