### ISSUE TITLE
Device Data for Dropin not the same as SDK

### ISSUE THREAD

**Issue by MSIH** [braintree/braintree-web-drop-in#798]
### General information

* SDK/Library version: 1.32.1
* Environment: N/A
* Browser and OS: N/A

### Issue description

The dropin documentation makes no reference to capturing or submitting Device Data. While the SDK says for Venmo [collection is required](https://developer.paypal.com/braintree/docs/guides/venmo/client-side#collect-device-data):
```
braintree.dataCollector.create({
  client: clientInstance,
  paypal: true
}).then(function (dataCollectorInstance) {
  // At this point, you should access the dataCollectorInstance.deviceData value and provide it
  // to your server, e.g. by injecting it into your form as a hidden input.
  var deviceData = dataCollectorInstance.deviceData;
}).catch(function (err) {
  // Handle component creation error
});
```
 and [submitting transaction required](https://developer.paypal.com/braintree/docs/guides/venmo/server-side#creating-transactions) device data:
```
gateway.transaction.sale({
  amount: "1000.00",
  paymentMethodNonce: nonceFromTheClient,
  options: {
    submitForSettlement: true
  },
  deviceData: req.body.device_data
}, function(err, result) {});
```

**Comment by jplukarski** [comment]
Hey @MSIH , thanks for pointing this out. Device data is still required for using Venmo in the Drop-In. The documentation needs to be updated. We'll add a task to update the Drop-In documentation for Venmo to include a note that device data is required and how to correctly create the Data Collector in the Drop-In. The correct way would be to include `dataCollector: true` in your `dropin.create` options:

```
braintree.dropin.create({
  authorization: 'CLIENT_AUTHORIZATION',
  container: '#dropin-container',
  venmo: {} // The `venmo` object requires no properties to instantiate.,
  dataCollector: true
});
```

We'll leave this issue open until we update the documentation. Thanks again for catching that.

**Comment by MSIH** [comment]
Will dataCollector: true handle both the client side javascript and html, and then the .net server side? if not, what else needs to be done. Thanks

**Comment by jplukarski** [comment]
@MSIH Great question. You will have to include the `deviceData` in your `transaction.sale` call like you do above. Additionally, you can grab the device data directly off the payload returned in `requestPaymentMethod` to send that to your server like this:

```
dropinInstance.requestPaymentMethod(function (err, payload) {
   if (err) {
     // handle error
     return;
   }
   hiddenNonceInput.value = payload.nonce;
   hiddenNonceInput.value = payload.deviceData
   form.submit();
 });
```

**Comment by MSIH** [comment]
Thanks. The strange thing is Venmo is working for me in both sandbox and production without providing deviceData. Where is the PayPal/Venmo API does it say DeviceData is required?

**Comment by armandodlvr** [comment]
Hi @MSIH You can find more details about `Venmo API - DeviceData` at https://developer.paypal.com/braintree/docs/guides/venmo/client-side#collect-device-data
