### ISSUE TITLE
Update Version to 3.8.0 Compatability

### ISSUE THREAD

**Issue by paymentplugins** [braintree/braintree-web-drop-in#80]
Hi Braintree,

The current version of the beta seems to only support version 3.7.0 when using the DropinInstance._client object to create a DataCollector. In order to generate device data using version 3.8.0 of the DataCollector, I believe the checks for version 3.7.0 will need to be updated to 3.8.0.

I updated my local copy of the dropin beta js file to check for version 3.8.0 and that appears to have resolved the issue should I choose to serve the js file from my own server.

Kind Regards,

**Comment by lilaconlee** [comment]
We'll update Drop-in to use the latest version of braintree-web in our next release and let you know when it's available here.

**Comment by crookedneighbor** [comment]
beta.5 is out and uses 3.10.0 (the latest version as of this writing)
