### ISSUE TITLE
verifyCard while using drop-in

### ISSUE THREAD

**Issue by anu-kailash** [braintree/braintree-web-drop-in#809]
### Issue description

https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side#verify-a-vaulted-credit-card

How can we do this using a drop-in? Can I call verifyCard from the dropinInstance?

**Comment by jplukarski** [comment]
Hello @anu-kailash , thanks for using the braintree web drop-in. You should be able to follow [the instructions for using 3DS with our Web Drop-In](https://developer.paypal.com/braintree/docs/guides/3d-secure/client-side#drop-in-ui) to verify a vaulted card. Under the hood, `requestPaymentMethod` will call [`verify`](https://github.com/braintree/braintree-web-drop-in/blob/404141eb1db73de06ae47f7089fee6403e9c38d3/src/dropin.js#L886) which will call [`verifyCard`](https://github.com/braintree/braintree-web-drop-in/blob/404141eb1db73de06ae47f7089fee6403e9c38d3/src/lib/three-d-secure.js#L58).

I am going to close this issue but please feel free to re-open if you have any further questions. Thanks.
