### ISSUE TITLE
Recollect CVV in Vault Flow

### ISSUE THREAD

**Issue by andrew-ignatiev** [braintree/braintree-web-drop-in#816]
Is it possible to recollect cvv in vault flow for Credit Cards in a way how it works in Adyen Web Drop-In ?
![Checkout 2022-05-18 11-23-08](https://user-images.githubusercontent.com/6745383/168956920-38e1c5aa-9595-40c2-a9ac-2f443b72fd33.png)

I was told it's possible todo via Hosted fields, please see example https://codepen.io/andrew-sp/pen/BaYWOQa

But if it's not the case in Braintree Web Drop-In then will be great to have this feature.

**Comment by jplukarski** [comment]
Hey @andrew-ignatiev , thanks for using the Braintree Web Drop-in. As of now, there is not a way through the Drop-in to collect a CVV for a vaulted payment.

There is a workaround you can try if you want to continue using the Drop-in. You can add a separate Hosted Field to collect a CVV, [create a CVV-only nonce](https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#using-a-cvv-only-nonce), then send that nonce along with the payment method token of the vaulted card into your transaction.sale call.

This is a great suggestion, as the current work around does involve a little bit more dev work. So, we'll add this to our list of enhancements for the next version of the Drop-In (we do not currently have a timeline to provide) and leave this issue open.

**Comment by hk43420** [comment]
We also looking for Drop-in to collect a CVV for a vaulted payment. This way if someone hacked to the users account, they still need the CVV number to submit order.

**Comment by hollabaq86** [comment]
Hey folks, I'm going to close this issue since it's a feature request and not a 🐛. That said, we are still evaluating this request and if/how we'd implement it in the Drop-In.

For internal tracking, issue 3210
