### ISSUE TITLE
CCV absent

### ISSUE THREAD

**Issue by vallettea** [braintree/braintree-web-drop-in#82]
Hello,

thanks for this awesome work.
My integration works well with the sandbox but I wonder if I need to do something for the CCV as i want to charge people in france and it seems mandatory.
Any help appreciated.

**Comment by lilaconlee** [comment]
The CVV field appears in Drop-in based on the [CVV rules configured in your Control Panel](https://articles.braintreepayments.com/support/guides/fraud-tools/basic/avs-cvv-rules#enabling-avs-and-cvv-rules). If your CVV rules are configured and you're still not seeing the CVV field let us know and we'll take another look!

**Comment by vallettea** [comment]
thx  a lot for your help. Works perfectly
