### ISSUE TITLE
Payment Method Deleted Event Feature Request

### ISSUE THREAD

**Issue by andrewstephens** [braintree/braintree-web-drop-in#826]
### Issue description

It would be great if, upon payment method deletion in the drop-in UI, an event could be emitted that contains the payment method information / nonce. I don't know if that would be a security concern, since it would only be emitted once. It's possible I've missed something reading the docs, but there is no unique identifier emitted when a payment method is deleted? 

#### Use Case
In my companies current system, we save some information about payments and subscriptions to the database. Right now, users can manually remove cards, which hits the API to handle removing the payment method, updating the subscriptions, etc. 

However, we just moved to the Drop-In UI and it wold be great if the Drop-In emitted an event (maybe hooking into `finishVaultedPaymentMethodDeletion` or similar) that contained the payment method nonce or a unique ID we could use to do that same manual process on our end through the API? A webhook for a removed payment would also be very useful.

Thanks!

**Comment by hollabaq86** [comment]
👋 @andrewstephens thanks for the detailed use case! I can definitely see how this would be helpful. I'm going to forward this feedback on to folks for vetting and prioritization. I can't guarantee it'll happen, or provide any kind of ETA on when this would get released. But this feature request **will be seriously considered**.

(for internal tracking, issue 397)
