### ISSUE TITLE
`threeDSecureInfo.status === 'challenge_required'` even though it is requested in `requestPaymentMethod()` function

### ISSUE THREAD

**Issue by ryangibbsnc** [braintree/braintree-web-drop-in#828]
### General information

* SDK/Library version: 1.33.4
* Environment: Production
* Browser and OS: Mainly Chrome / All 

### Issue description

We are having a number of transactions fail due to threeDSecure issues. We have added some logs to the client side code and noticed that some of the nonces we receive are returning a `nonce.threeDSecureInfo.status === 'challenge_required'` as if the user was never prompted to go through the 3DS process. 
We create an instance like so:
```javascript
await dropin.create({
 ...,
 threeDSecure: true
})
```

Our requestPaymentMethod() call looks like the following:
```javascript
const payload = await this.instance.requestPaymentMethod({
      threeDSecure: {
        amount: cart.verificationAmount.amount.toString(),
      },
})
```

Here is the log output from a specific instance where their transaction failed due to `Gateway Rejected: three_d_secure`
```javascript
{
  ...,
  liabilityShifted: False, 
  liabilityShiftPossible: True,
  threeDSecureInfo: {
    ...,
    acsUrl: https://3ds.fr.ing.com/acs-www/v2/brw/index.xhtml, 
    cavv: None, 
    eciFlag: 00, 
    enrolled: Y, 
    liabilityShifted: False, 
    liabilityShiftPossible: True, 
    paresStatus: None, 
    status: challenge_required,
    threeDSecureVersion: 2.1.0, 
    xid: None
   }
}
```

In terms of reproducing we have not found a way to replicate this error as it is intermittent.

**Comment by hollabaq86** [comment]
👋 @ryangibbsnc thanks for reaching out, can you [contact Support](https://developer.paypal.com/braintree/help) referencing this issue? They'll be able to help us investigate what's happening on the side of our MPI provider CardinalCommerce and hopefully we can piece together what's happening.

**Comment by hollabaq86** [comment]
They'll need to know your merchant ID (please don't post it here in this public forum) and any timestamps, last four digits of the card used or amount submitted for verification to help their investigation.

**Comment by ericklima-scandiweb** [comment]
Hey, @ryangibbsnc . Did they provide you with a solution for this issue?

**Comment by erickcomp** [comment]
Hey, @ryangibbsnc . Did they provide you with a solution for this?
