### ISSUE TITLE
Way to set field labels as there is no internalization

### ISSUE THREAD

**Issue by vallettea** [braintree/braintree-web-drop-in#83]
Hello,

is there an option to set the labels of the form ?
Best,

**Comment by lilaconlee** [comment]
At the moment, we can't recommend a way for your to set the labels of the form. We'll update you here when translations are available, which should be soon!

**Comment by vallettea** [comment]
👍

**Comment by crookedneighbor** [comment]
The next release will include internationalization.

**Comment by intelliot** [comment]
Today's release of 1.0.0-beta.6 includes translations. Let us know if there's other internationalization you'd like to see!

**Comment by Cracken6** [comment]
Would be great if you support Latvian translations someday. Thanks.

**Comment by vallettea** [comment]
👍
