### ISSUE TITLE
Creating reoccuring billing subscription for new customer

### ISSUE THREAD

**Issue by pujoey** [braintree/braintree-web-drop-in#84]
Is there a way to refresh the token after a new user has entered credit card info so customer and payment method can be vaulted before clicking on "submit" to create a subscription?

**Comment by lilaconlee** [comment]
At the moment, the only way to get this behavior is to tear down Drop-in and re-create it with the desired client token or wait to create Drop-in until after you have the client token you want to use. Feel free to re-open this issue if this doesn't address your problem.
