### ISSUE TITLE
Braintree PayPal login abort link always fails

### ISSUE THREAD

**Issue by julian-** [braintree/braintree-web-drop-in#841]
### General information

* SDK/Library version: 1.33.5
* Environment: sandbox
* Browser and OS (Capacitor App - difference between in-app browser ios and android)

### Issue description

Not working abort link when choosing/clicking the PayPal-Button as payment method. I am using the Web-Drop-In in a Capacitor Angular app. 

<img width="368" alt="Bildschirmfoto 2022-11-09 um 11 26 38" src="https://user-images.githubusercontent.com/5802676/200807841-2ddbf2d7-070a-4e88-886e-175f382b5525.png">

___

I am currently testing a Braintree (PayPal) checkout in sandbox mode. I initialize the drop-in as follows:

```
{
        authorization: {token},
        container: '#dropin-container',
        locale: 'de_DE',
        paymentOptionPriority: ['paypal'],
        card: false,
        paypal: {
          flow: 'checkout',
          amount: {price},
          currency: 'EUR',
        },
        translations: {
          chooseAnotherWayToPay: 'Anderen Paypal-Account verwenden.',
        }
      },
```

When the PayPal-Popup opens where I should enter my PayPal-Account-Credentials there are different ways to close the popup.
At least on iOS are appearing 2 options. The first option is the popup (modal) closing cross in the upper right corner.
The second option is an abort link "Cancel and go back to {company name}" below the login form.

When using the cross in the upper right corner the modal closes successfully. I expected the same behavior for the abort link.

I am wondering why this abort/cancel link is only appearing on ios (safari) and not on Android (or Chrome). And when I hit the link instead of the cross - the cancel process fails, I get asked if I want to try this again, which does not work too and the popup tells me immediately after this second attempt that I was too long inactive.

I usually expect anywhere the same behavior, Chrome should show the same as Safari. 
Maybe there is a way to forcefully hide this abort link?

**Comment by armandodlvr** [comment]
@julian- The screen you show belongs to PayPal, it is not something we can change or control.
