### ISSUE TITLE
How to add accessibility tags to errors field

### ISSUE THREAD

**Issue by cctorres** [braintree/braintree-web-drop-in#845]
### General information

* SDK/Library version: ~1.16.0
* Environment: Sandbox
* Browser and OS Chrome Version 107.0.5304.110  MacOS 12.6

### Issue description

Hi!, for accessibility reasons, I want to add some tags (such as role='alert') to the errors that appear in the dropin. Is this possible to do this similar to the override of the internalLabels done?

![Screen Shot 2022-11-18 at 3 56 19 PM](https://user-images.githubusercontent.com/25993793/202800947-033ae71e-00aa-4939-ace6-4ccc8361f77c.png)

**Comment by nidhinarendra** [comment]
Hello @cctorres ,

Would you be able to give us more specific tags you are looking to add?

**Comment by nidhinarendra** [comment]
Thanks @cctorres 

We will look into this and provide an update asap. ( Internal ticket created #7641)

**Comment by oscarleonnogales** [comment]
Hi @cctorres,

Thank you for bringing this to our attention. We've added the `role="alert"` tag to these error divs as of version 1.38.1
