### ISSUE TITLE
Overflow on iPhone5 inside Bootstrap modal

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#85]
### General information

* SDK/Library version: 1.0 beta4
* Environment: sandbox
* Browser and OS: Chrome 56.0.2924.87 (64-bit) on MacOS 10.12.3

### Issue description
<img width="419" alt="screen shot 2017-03-04 at 13 43 46" src="https://cloud.githubusercontent.com/assets/1783732/23578879/d7ef7cf6-00e0-11e7-9271-e6279d0cacd8.png">

This is how I've fixed it:
```

/* BRAINTREE FIX on small phones */
@media (max-width: 320px) {
    .braintree-option {
        width: 83vw;
    }
}
@media (min-width: 321px) {
    .braintree-option {
        width: 100%;
    }
}
/* ENDS BRAINTREE FIX */
```

**Comment by lilaconlee** [comment]
Thanks for letting us know and providing your solution! We'll keep this in mind as we're tweaking the UI and update this issue if we deploy a fix.

**Comment by crookedneighbor** [comment]
Why not just have a `max-width: 100%` ?

**Comment by NinoSkopac** [comment]
> Why not just have a max-width: 100% ?

Just tried this, it didn't work.
<img width="1203" alt="screen shot 2017-03-06 at 18 21 50" src="https://cloud.githubusercontent.com/assets/1783732/23621151/d69df6d8-0299-11e7-906e-e0ec7c2fd029.png">
