### ISSUE TITLE
Form resets wihout error message for some CC

### ISSUE THREAD

**Issue by leforthomas** [braintree/braintree-web-drop-in#850]
### General information

Dropin 1.33.4
Production
Chrome (no idea the OS, happens only for some customers)

### Issue description

It only happens with some customers and some cards.

Latest in date, the SAME customer did one purchase with one card which worked and then the other one with another card which failed. From the same computer, same browser, same application...

The issue appears to be the same to most customers, ie they fill in the form, press submit and then the page reloads, the form is empty (in their own words). I am not able to reproduce the issue at all with test cards.

An initial token is requested to BT when the form loads but after that (ie after submit) there are no requests sent to my server nor to BT, so the error seems to be happening on the client side. I am not able to see the browser logs on the customer's side unfortunately.

I don't think it is a question of VISA/MASTERCARD/... because we have had working purchases with all of them and conversely we had failing purchases with a mix of the same ones.

**Comment by leforthomas** [comment]
Someone at BT actually found the issue. It seems that the address field needs to be < 50 chars long. Anything above and the form "resets" without any error message. Would be good if this error could be handled in a less "obscure" way, eg at least some message saying the address field is too long.

**Comment by foton** [comment]
See https://braintree.github.io/braintree-web/3.88.3/ThreeDSecure.html#~billingAddress

**Comment by jplukarski** [comment]
Revisiting this thread. In the current version (1.40.2) we surface the error as a `THREEDS_LOOKUP_VALIDATION_ERROR` with the message: `The data passed in `verifyCard` did not pass validation checks. See details for more info`. The details contain this message: `Billing line1 format is invalid.`

To see this, you can use our codepen to test -> https://codepen.io/braintree/pen/KjWqGx

Enter a very large billing address and look in the browser console to see the error.

Closing this issue out.

**Comment by warrenkc** [comment]
I have also run into this issue, but I am only submitting the first and last name to Braintree. So I don't know why the page would reload and all the form fields are blank on the page.
