### ISSUE TITLE
THREEDS_NOT_ENABLED_FOR_V2 Braintree Production - Prestashop

### ISSUE THREAD

**Issue by okanano** [braintree/braintree-web-drop-in#851]
### General information

* SDK/Library version: braintreepaymentpro17
* Environment: Production
* Browser and OS: Firefox - Debian

### Issue description
Hi, I configured Braintree in Prestashop and works correctly in Sandbox mode because Braintree by default enables the 3D Secure option. However, I'm not enrolled to 3D Secure in Braintree production and when I changed of mode, Braintree stop working and now I'm getting this error:

code: "THREEDS_NOT_ENABLED_FOR_V2"
​details: undefined
​message: "3D Secure version 2 is not enabled for this merchant. Contact Braintree Support for assistance at https://help.braintreepayments.com/"

I checked the code and this section is generating the error:

braintree.threeDSecure.create({
                                    version: 2, // Will use 3DS2 whenever possible
                                    client: clientInstance
                                }, function (threeDSecureErr, threeDSecureInstance) {
                                    if (threeDSecureErr) {
                                        // Handle error in 3D Secure component creation
                                        return;
                                    }

                                    threeDSecure = threeDSecureInstance; // Variable value is undefined
                                });

Could you please advise what should I do?

Thanks.

**Comment by cgdibble** [comment]
Hi, @okanano, the error message is outlining your next steps. You need to contact Braintree Support to enable 3DS in production. The error has the link to follow, but we also include that information in our docs here: https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration

**Comment by okanano** [comment]
Hi, thanks for your answer

I'm wondering what's the case if I don't want to enroll to 3D Secure? Can I
do something or is mandatory?

Regards,
Oscar

**Comment by cgdibble** [comment]
Well, you don't have to enroll in 3DS, but then if that were the case you also wouldn't be trying to initialize the 3DS component we provide. 
Within the sandbox environment, it is automatically enabled. Our docs explain further here: https://developer.paypal.com/braintree/docs/guides/3d-secure/configuration
