### ISSUE TITLE
Purchase button is misaligned on desktop

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#86]
### General information

same as previous issue

### Issue description
<img width="742" alt="screen shot 2017-03-04 at 14 14 42" src="https://cloud.githubusercontent.com/assets/1783732/23579050/0e125282-00e5-11e7-8a45-f9492cc96252.png">

Fix
```
@media (min-width: 768px) {
    #braintree-submit-button {
        margin-left: 3px;
    }
}
```

Post-fix
<img width="743" alt="screen shot 2017-03-04 at 14 18 50" src="https://cloud.githubusercontent.com/assets/1783732/23579070/8707e4e0-00e5-11e7-9e2b-54740249e778.png">

**Comment by NinoSkopac** [comment]
Correction: it was misaligned on an actual phone too (as opposed to not being misaligned in a simulator)

**Comment by lilaconlee** [comment]
Because the button is not actually part of Drop-in, it looks like the fix you provided is the best solution for now. We'll keep your feedback in mind as we continue to tweak the design and update you here if we make a relevant fix.

**Comment by crookedneighbor** [comment]
Fixed on master. This will go out in the next release.
