### ISSUE TITLE
DropinError: "message":"No payment method is available.",

### ISSUE THREAD

**Issue by crag-a** [braintree/braintree-web-drop-in#873]
### General information

* SDK/Library version:  php sdk version 6.11  with  /dropin/1.36.0/js/dropin.min.js   
* Environment:  Production 
* Browser and OS: all major browsers  

### Issue description

dropin working properly and things have been working well for years, but now when there is an
existing id and customer adds a new card

we get this error:

{"name":"DropinError","message":"No payment method is available.","_braintreeWebError":{"name":"BraintreeError","code":"HOSTED_FIELDS_FAILED_TOKENIZATION","message":"The supplied card data failed tokenization.","type":"CUSTOMER","details":{"originalError":{"name":"BraintreeError","code":"CLIENT_REQUEST_ERROR","message":"There was a problem with your request.","type":"NETWORK","details":{"originalError":{"error":{"message":"Credit card is invalid"},"fieldErrors":[{"field":"creditCard","fieldErrors":[{"field":"billingAddress","fieldErrors":[{"code":"81811","field":"streetAddress","message":"Street address is required"}]}]}]},"httpStatus":422}}}}}

our relevant code:

`<?php
try {
$existing_braintree_customer_id = $gateway->ClientToken()->generate([ "customerId" => $braintree_customer_id['braintree_customer_id'] ]);
} catch (Exception $e) {
}
?>

<script src="includes/javascript/braintree/dropin.min.js"></script>
<script>
var client_token_existing = "<?php echo $existing_braintree_customer_id; ?>";
var client_token = "<?php echo($gateway->ClientToken()->generate()); ?>";
if (client_token_existing.length > 0) {
client_token = client_token_existing;
 }

 braintree.dropin.create({
authorization: client_token,
 vaultManager: true,
 selector: '#bt-dropin',
 venmo: {}

}, function (createErr, instance) {
if (createErr) {
console.log('Create Error', createErr);
return;
 }

form.addEventListener('submit', function (event) {
event.preventDefault();

var braintree_form_submitted = 0;

 instance.requestPaymentMethod(function (err, payload) {

if (err) {
console.log('Request Payment Method Error', err);
 enableConfirmationButton();

 $.ajax({
method: "POST",
 url: "bt_errors_ajax.php",
 data: {
ajax: 1,
 error: JSON.stringify(err)
},
 success: function (response) {
}
});

return;
 }

 form.submit();
 braintree_form_submitted = 1;
 });

});
 });
</script>`

**Comment by hollabaq86** [comment]
Please contact [Braintree Support](https://developer.paypal.com/braintree/help) referencing this issue so they can investigate why you're seeing increased validation errors.
