### ISSUE TITLE
Why on earth is the cardholder name for "Pay with card" inputmode=numeric?

### ISSUE THREAD

**Issue by lol768** [braintree/braintree-web-drop-in#874]
### General information

* SDK/Library version: 1.36.0
* Environment: Production
* Browser and OS: Firefox on Android, Safari for iOS

### Issue description

```
https://assets.braintreegateway.com/web/3.92.0/html/hosted-fields-frame.min.html
```

```html
<input autocomplete="cc-name" type="text" autocorrect="off" autocapitalize="none" spellcheck="false" class="cardholderName" data-braintree-name="cardholderName" name="cardholder-name" id="cardholder-name" inputmode="numeric" placeholder="Cardholder Name" maxlength="255" aria-describedby="field-description-cardholderName">
```

![image](https://user-images.githubusercontent.com/2552726/227737679-3accf762-cae3-4894-9dd2-c5cc23d06060.png)

Obviously this prevents our customers filling in the cardholder name on mobile. I'd _really_ like to know how something this basic made it into production?

<img src="https://user-images.githubusercontent.com/2552726/227737793-4d697dc8-51ca-4bdd-a775-17162eb793f6.png" width=600>

**Comment by lol768** [comment]
To add insult to injury, the cardholder name validation rejects numeric cardholder names, so there's no way that our customers on mobile can pay at all.

<img src="https://user-images.githubusercontent.com/2552726/227738148-eb14f7af-324d-4303-ac95-8548b9a63863.png" width=600>

**Comment by lol768** [comment]
Dupe of https://github.com/braintree/braintree-web/issues/673

**Comment by ibooker** [comment]
We are working on fix; in the meantime we have identified the following workaround: 
 -- Adding `type: 'text'` property to the `cardHolderName` field should override the numeric mode

```js
 braintree.hostedFields.create({
    ...
    fields: {
      cardholderName: {
        selector: '#cc-name',
        placeholder: 'Name as it appears on your card',
        type: 'text'
      },
      ...
    }
```

**Comment by lol768** [comment]
What's the workaround for those of us using the Drop-in UI @ibooker

**Comment by SancSalix** [comment]
```return braintree.dropin.create({
    authorization: clientToken,
    container: '#drop-in',
    threeDSecure: true,
    card:  {
    overrides: {
      fields: {
        cardholderName: {
          type: 'text'
        }
      }
    } 
  }
  })```

https://developer.paypal.com/braintree/docs/guides/drop-in/customization#customize-your-ui

This is also fixed in the next patch version of drop in that's going out today
