### ISSUE TITLE
Deleting vaulted payment methods isn't working

### ISSUE THREAD

**Issue by wamiswag** [braintree/braintree-web-drop-in#880]
### General information

Version: 1.36.1

I've enabled vault manager and vault manager override as such:
      dropin.create(
        {
          authorization: token,
          container: "#braintree-drop-in-div",
          dataCollector: true,
          vaultManager: true,
          card: {
            vault: {
              allowVaultCardOverride: true,
            },
          },

### Issue description

Upon clicking the "Edit" button, and then clicking the Delete button on a payment method, it does not delete. It just takes me back to the payment method which is active (which is the one I am trying to delete).

**Comment by SancSalix** [comment]
Did you experience this issue before this particular version update or is this a new thing? Do you have any logs or anything from inspections?

**Comment by cgdibble** [comment]
@wamiswag the [issue template](https://github.com/braintree/braintree-web-drop-in/blob/main/.github/ISSUE_TEMPLATE.md) lists some other helpful info, too. Can you provide more details? We aren't able to replicate this and so need more detail to try and get to the root of the issue.

On top of those in the issue template, do you have any further specifics about when this occurs?

**Comment by cgdibble** [comment]
Please contact [Braintree Support](https://developer.paypal.com/braintree/help) referencing this issue and provide that information, as well info around browser version, etc.

We'll partner with Support to investigate this issue further

**Comment by hollabaq86** [comment]
Going to close this issue since OP opted for email collaboration with us and BT Support
