### ISSUE TITLE
Venmo view does not show error message on requestPaymentMethod()

### ISSUE THREAD

**Issue by dwschultz** [braintree/braintree-web-drop-in#882]
### General information

* SDK/Library version: 1.34.0
* Environment: sandbox (or production)
* Browser and OS:  Chrome 112.0.5615.137 (Official Build) (arm64)on MacOS 13.3.1

### Issue description

Calling requestPaymentMethod when initial PayPal view button is showing, shows error message:
"Use the PayPal button to continue with your payment."

Calling requestPaymentMethod when initial Venmo view button is showing, shows no error message.

Immediate cause is that Venmo view doesn't override BaseView.requestPaymentMethod() while PayPal does:

Venmo:
```
BaseView.prototype.requestPaymentMethod = function () {
  return Promise.reject(new DropinError(errors.NO_PAYMENT_METHOD_ERROR));
};
```

PayPal:
```
BasePayPalView.prototype.requestPaymentMethod = function () {
  this.model.reportError('paypalButtonMustBeUsed');

  return BaseView.prototype.requestPaymentMethod.call(this);
};
```

**Comment by hollabaq86** [comment]
👋 Hi @dwschultz I see what you mean, the library needs to be improved to surface that Venmo _has_ to be launched from a direct user action (Venmo button click) for it to successfully work.

We'll take a look at improving this for folks, thanks!

For internal tracking, issue 10408

**Comment by jplukarski** [comment]
@dwschultz , thanks for this suggestion. We have added it to v1.40.0 of the Drop-In

<img width="513" alt="venmoRequestPaymentMethod" src="https://github.com/braintree/braintree-web-drop-in/assets/40774928/a97a56a3-7f36-4d2c-82b9-b16e14693d83">

**Comment by shango420** [comment]
sb-ngjvl21295634-1@business.example.com

**Comment by shango420** [comment]
window.paypal
  .Buttons({
    style: {
      shape: "rect",
      layout: "vertical",
    },
    async createOrder() {
      try {
        const response = await fetch("/api/orders", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          // use the "body" param to optionally pass additional order information
          // like product ids and quantities
          body: JSON.stringify({
            cart: [
              {
                id: "YOUR_PRODUCT_ID",
                quantity: "YOUR_PRODUCT_QUANTITY",
              },
            ],
          }),
        });

        const orderData = await response.json();

        if (orderData.id) {
          return orderData.id;
        } else {
          const errorDetail = orderData?.details?.[0];
          const errorMessage = errorDetail
            ? `${errorDetail.issue} ${errorDetail.description} (${orderData.debug_id})`
            : JSON.stringify(orderData);

          throw new Error(errorMessage);
        }
      } catch (error) {
        console.error(error);
        resultMessage(`Could not initiate PayPal Checkout...<br><br>${error}`);
      }
    },
    async onApprove(data, actions) {
      try {
        const response = await fetch(`/api/orders/${data.orderID}/capture`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
        });

        const orderData = await response.json();
        // Three cases to handle:
        //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
        //   (2) Other non-recoverable errors -> Show a failure message
        //   (3) Successful transaction -> Show confirmation or thank you message

        const errorDetail = orderData?.details?.[0];

        if (errorDetail?.issue === "INSTRUMENT_DECLINED") {
          // (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
          // recoverable state, per https://developer.paypal.com/docs/checkout/standard/customize/handle-funding-failures/
          return actions.restart();
        } else if (errorDetail) {
          // (2) Other non-recoverable errors -> Show a failure message
          throw new Error(`${errorDetail.description} (${orderData.debug_id})`);
        } else if (!orderData.purchase_units) {
          throw new Error(JSON.stringify(orderData));
        } else {
          // (3) Successful transaction -> Show confirmation or thank you message
          // Or go to another URL:  actions.redirect('thank_you.html');
          const transaction =
            orderData?.purchase_units?.[0]?.payments?.captures?.[0] ||
            orderData?.purchase_units?.[0]?.payments?.authorizations?.[0];
          resultMessage(
            `Transaction ${transaction.status}: ${transaction.id}<br><br>See console for all available details`,
          );
          console.log(
            "Capture result",
            orderData,
            JSON.stringify(orderData, null, 2),
          );
        }
      } catch (error) {
        console.error(error);
        resultMessage(
          `Sorry, your transaction could not be processed...<br><br>${error}`,
        );
      }
    },
  })
  .render("#paypal-button-container");

// Example function to show a result to the user. Your site's UI library can be used instead.
function resultMessage(message) {
  const container = document.querySelector("#result-message");
  container.innerHTML = message;
}
