### ISSUE TITLE
clearSelectedPaymentMethod does not return to options from a specific method

### ISSUE THREAD

**Issue by LeopoldTal** [braintree/braintree-web-drop-in#883]
### General information

* SDK/Library version: 1.36.1
* Environment: Both sandbox and prod
* Browser and OS: Firefox on macOS

### Issue description

In our application, after the user has entered payment details, the cart amount might change. In that case, we need to return to the options view so the user can re-confirm payment.

After selecting a method, e.g. card, and inputting any required info, call `clearSelectedPaymentMethod`. I expect to return to the list of payment options. Instead, nothing happens.

The relevant check is [line 719](https://github.com/braintree/braintree-web-drop-in/blob/main/src/dropin.js#L719): we only navigate if we're in the methods view.

**Comment by oscarleonnogales** [comment]
Hi,
Thanks for bringing this to our attention, we'll start looking into this and post any updates here.

**Comment by oscarleonnogales** [comment]
Hi @LeopoldTal,

We've gone ahead and fixed this issue as of version 1.38.1, calling `clearSelectedPayment` from any view will take you back to the initial view now, not just from the methods view.
