### ISSUE TITLE
Tabbing between input fields not working on Firefox

### ISSUE THREAD

**Issue by Jwright707** [braintree/braintree-web-drop-in#884]
### General information

* SDK/Library version: 1.33.6
* Environment: Production
* Browser and OS: Firefox and MacOS

### Issue description

I noticed when trying to use this package that the tabbing between input fields doesn't work on firefox but works on other browsers. Is there any workaround for this issue? Thank you.

**Comment by jlafosse** [comment]
I am using sdk version 1.37.0 and experiencing the same issue with FireFox regardless of environment. I have confirmed that tabbing does work on Chrome and Safari.

**Comment by hollabaq86** [comment]
👋 Hey folks, I'm testing this behavior with v1.38.0 of the Drop-in and v113.0.1 of Firefox on a Mac and I can't replicate this behavior:

https://github.com/braintree/braintree-web-drop-in/assets/22104233/a3515685-d1ec-42cc-aa39-b2f93faaef78

@Jwright707 @jlafosse what version of Firefox are you using?

**Comment by hollabaq86** [comment]
quick update I can't replicate this on v 113.0.2 of Firefox for Mac OS, either.

**Comment by jlafosse** [comment]
So I can confirm that tabbing does work when using the demo that you tested at: https://braintree.github.io/braintree-web-drop-in/  - however it does not work when using the demo at:  https://developer.paypal.com/braintree/docs/guides/drop-in/overview nor does it work on my local setup... so something must be different.

**Comment by hollabaq86** [comment]
@jlafosse ahhh yup! I can reproduce this issue with the link you provided, interesting... We'll take a look at this and see if we can figure out the root (whether it's an issue with how we're displaying the drop-in demo on our docs site, an issue in the SDK, or an issue with Firefox).

for internal tracking, issue 12646

**Comment by oscarleonnogales** [comment]
Issue has been fixed as of v1.40.1
