### ISSUE TITLE
Statistics about interactions with the web-drop-in

### ISSUE THREAD

**Issue by karolyi** [braintree/braintree-web-drop-in#889]
Hello,

we use the web drop-in (latest) on our checkout page, and while some users are paying properly, I see a lot of canceled orders, where the client doesn't pay, and we don't know why.

It would be nice to know what happens, and I understand that observing the fields from my JS based code is not only against the rules, it might be impossible as well.

Is there some kind of a statistic about the interactions with the web-drop-in?

**Comment by hollabaq86** [comment]
Hi @karolyi there currently aren't statistics about performance available to developers, for a few reasons:

1. **Every merchant integration is different**. There's simply no way for us to create a common "conversion" metric and track this information for all merchants.
2. **We do not own a merchant's entire checkout experience**. We're a small part in checkout workflows, which also means we have limited insight or access into calculating a measure for checkout friction or "conversion" from checkout to transaction.
3. **We have limited insight into all available payment methods**. We provide the ability to integrate with some payment methods like Apple Pay, Google Pay, or some particular fraud-prevention flows like 3D Secure, but we don't own all parts of that integration, making it impossible for us to calculate nuanced performance measurements for those flows.

That doesn't mean this isn't impossible! It just means that it's up to merchant developers to add their own logging and capture the information they need to calculate whatever measurements they want to use to calculate checkout performance.

That said, I'm going to forward this on to our Product folks in case this is something we can explore more deeply down the road. Thanks!
