### ISSUE TITLE
Allow automatic form entry?

### ISSUE THREAD

**Issue by meecect** [braintree/braintree-web-drop-in#895]
After implementing the drop-in UI, we noticed that our cypress automated testing scripts are unable to locate and insert credit card numbers for our E2E testing.

Is there an option that we can use in our sandbox environments to make the UI allow automated form entries?  

The error we received is: Automated credit card filling is disabled because this form does not use a secure connection.

Maybe it's just an SSL certificate issue?

**Comment by jplukarski** [comment]
Hello @meecect , thanks for using the Drop-In. This error is probably coming from the browser you are using to complete your testing, not our SDK. I think you are right that It's likely this is an SSL cert issue. I can suggest making sure your test environment is using https.

Let us know if you have any other questions.
