### ISSUE TITLE
Maestro cards are not supported using the Drop-In

### ISSUE THREAD

**Issue by afane20** [braintree/braintree-web-drop-in#898]
### General information

* SDK/Library version: 1.39.0
* Environment: Sandbox
* Browser and OS: Brave Versión 1.52.130 Chromium: 114.0.5735.198 (Build oficial) (64 bits) & Ubuntu 22.04

### Issue description

Maestro cards are not supported using the Drop-In feature. If they are supported, I would like to know how to enable their support since I haven't found it in the documentation. Thanks!

**Comment by jplukarski** [comment]
Hey @afane20 , thanks for using the Braintree Drop-In!

Support for Maestro cards depends on the Merchant Account Configuration you are using to instantiate the Drop-In. Please contact our support team so they can answer questions specific to your Merchant Account -> https://developer.paypal.com/braintree/help/

We'll close this issue for now, but feel free to re-open it or open a new issue if you run into any other issues while integrating with the Drop-In. Thanks!
