### ISSUE TITLE
On iOS Safari, rapidly switching DropIn payment methods causes soft lock (rendering glitch)

### ISSUE THREAD

**Issue by alfredsgenkins** [braintree/braintree-web-drop-in#902]
### General information

* SDK/Library version: 1.40.2
* Environment: Sandbox
* Browser and OS: iOS 16.6 Safari

### Issue description

For context, I am rendering the DropIn in the SPA app, using following parameters:
```
{
    "authorization": "<REDACTED>",
    "container": "#BRAINTREE_CONTAINER_ID",
    "threeDSecure": false,
    "applePay": {
        "displayName": "<REDACTED>",
        "paymentRequest": {
            "total": {
                "label": "<REDACTED>",
                "amount": 4
            },
            "requiredShippingContactFields": [
                "postalAddress",
                "name",
                "email",
                "phone"
            ],
            "requiredBillingContactFields": [
                "postalAddress",
                "name"
            ]
        }
    },
    "paypal": {
        "flow": "checkout",
        "amount": 4,
        "currency": "USD",
        "enableShippingAddress": true,
        "shippingAddressEditable": false
    },
    "googlePay": {
        "googlePayVersion": 1,
        "transactionInfo": {
            "totalPriceStatus": "ESTIMATED",
            "totalPrice": "4",
            "currencyCode": "USD"
        },
        "allowedPaymentMethods": [
            "CARD"
        ],
        "phoneNumberRequired": true,
        "emailRequired": true,
        "shippingAddressRequired": true,
        "cardRequirements": {
            "billingAddressRequired": true,
            "billingAddressFormat": "FULL"
        },
        "button": {
            "buttonColor": "white",
            "buttonType": "checkout"
        }
    },
    "card": false
}
```

When the component is mounted, everything is fine. If I select some payment option, the DropIn changes to display the corresponding button. However, if I start to switch payment methods too rapidly, I can get the whole application freezes in this state.

https://github.com/braintree/braintree-web-drop-in/assets/29531824/d680fd4d-3e93-4853-ae4d-f9a82ae43fa4

Once frozen, clicks anywhere on the page are no longer registered, even reloading the app does not help. The header (which should be fixed) appears somewhere in the middle of the page.

https://github.com/braintree/braintree-web-drop-in/assets/29531824/41e05850-078c-4f8e-8a20-b782745cb706

If connected to a Mac computer during this "freezed" state, the application appears to behave weird:

- Initially, the app appears to be stuck in an infinite loop of sorts, checking for `zoid` element, and it's children:

<img width="1407" alt="Screenshot 2023-09-05 at 19 01 58" src="https://github.com/braintree/braintree-web-drop-in/assets/29531824/06b10ea7-77b1-48fa-a5c1-1adc5e0fe63c">

- Deleting the element helps to exit the loop

- However, there is nothing which helps to exit the stuck rendering issue. Even deleting the HTML does not affect the page display (rendering) on iOS device (I assume that is a Safari bug), the visuals do not change.

- Sometimes (including the recorded case), if I click the area where apple pay button suppose to be, the ApplePay popup appears (but I cut the video off there for privacy reasons), while the visuals for the button do not appear. The only way out of this "soft lock" is to open the page in new tab.
 
What is important, is that I was unable to reproduce the issue on https://braintree.github.io/braintree-web-drop-in/, however, checking Performance tab (in Chrome, where issue is not repoducable) indicates me that no callbacks of our application are executed during the switch of payment options:

<img width="682" alt="image" src="https://github.com/braintree/braintree-web-drop-in/assets/29531824/a2a8d381-4feb-4b6f-a9db-153f22bd2f19">

Additionally, I would like to report weird black artifacts which sometimes appear in the area where the DropIn is rendered during clicks and navigation (as I assume this could also be attributed as rendering glitch, which sometimes just disappears all by itself). In this video everything is shown (black boxes, freezed rendering, and ability to click on button which is not rendered):

https://github.com/braintree/braintree-web-drop-in/assets/29531824/87bfe595-cb75-4374-a8e7-34cae1889b3a

I am reaching out as our team spent quite a while investigating this issue and we were unable to come up with a solution. Here are few notes on a topic:
- DropIn is `teardown` is called on unmount (but unmount never happens in our case
- There are no other elements with the same ID as the DropIn target element
- The bug vas reproducible on version 1.38.0 of sdk
- `dropin.create` is called once

**Comment by jplukarski** [comment]
Hey @alfredsgenkins thanks for using the Drop-In!

I am also not able to reproduce either of these issues with my own integration in a device using iOS 16.6. Since this is likely an issue with your integration, and not necessarily a bug within the Drop-In, I can suggest [writing into our support team with these details](https://developer.paypal.com/braintree/help/) and, if possible, a testing site with steps to reproduce. After they investigate if they do conclude it is indeed a bug within our Drop-In, they will loop us back in. But in the meantime, they are best equipped to help you troubleshoot your integration.

**Comment by shango420** [comment]
window.paypal
  .Buttons({
    style: {
      shape: "rect",
      layout: "vertical",
    },
    async createOrder() {
      try {
        const response = await fetch("/api/orders", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          // use the "body" param to optionally pass additional order information
          // like product ids and quantities
          body: JSON.stringify({
            cart: [
              {
                id: "YOUR_PRODUCT_ID",
                quantity: "YOUR_PRODUCT_QUANTITY",
              },
            ],
          }),
        });

        const orderData = await response.json();

        if (orderData.id) {
          return orderData.id;
        } else {
          const errorDetail = orderData?.details?.[0];
          const errorMessage = errorDetail
            ? `${errorDetail.issue} ${errorDetail.description} (${orderData.debug_id})`
            : JSON.stringify(orderData);

          throw new Error(errorMessage);
        }
      } catch (error) {
        console.error(error);
        resultMessage(`Could not initiate PayPal Checkout...<br><br>${error}`);
      }
    },
    async onApprove(data, actions) {
      try {
        const response = await fetch(`/api/orders/${data.orderID}/capture`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
        });

        const orderData = await response.json();
        // Three cases to handle:
        //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
        //   (2) Other non-recoverable errors -> Show a failure message
        //   (3) Successful transaction -> Show confirmation or thank you message

        const errorDetail = orderData?.details?.[0];

        if (errorDetail?.issue === "INSTRUMENT_DECLINED") {
          // (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
          // recoverable state, per https://developer.paypal.com/docs/checkout/standard/customize/handle-funding-failures/
          return actions.restart();
        } else if (errorDetail) {
          // (2) Other non-recoverable errors -> Show a failure message
          throw new Error(`${errorDetail.description} (${orderData.debug_id})`);
        } else if (!orderData.purchase_units) {
          throw new Error(JSON.stringify(orderData));
        } else {
          // (3) Successful transaction -> Show confirmation or thank you message
          // Or go to another URL:  actions.redirect('thank_you.html');
          const transaction =
            orderData?.purchase_units?.[0]?.payments?.captures?.[0] ||
            orderData?.purchase_units?.[0]?.payments?.authorizations?.[0];
          resultMessage(
            `Transaction ${transaction.status}: ${transaction.id}<br><br>See console for all available details`,
          );
          console.log(
            "Capture result",
            orderData,
            JSON.stringify(orderData, null, 2),
          );
        }
      } catch (error) {
        console.error(error);
        resultMessage(
          `Sorry, your transaction could not be processed...<br><br>${error}`,
        );
      }
    },
  })
  .render("#paypal-button-container");

// Example function to show a result to the user. Your site's UI library can be used instead.
function resultMessage(message) {
  const container = document.querySelector("#result-message");
  container.innerHTML = message;
}
