### ISSUE TITLE
Financing Options

### ISSUE THREAD

**Issue by iget-master** [braintree/braintree-web-drop-in#903]
### General information

* SDK/Library version: 
* Environment: 
* Browser and OS 

### Issue description

There's no documentation on how to use Financing Options with Braintree Web Dropin 

https://graphql.braintreepayments.com/integration_guides/financing_options/#checkout-with-installments

**Comment by hollabaq86** [comment]
👋 thanks for the feedback. I'm going to forward this on to the team that owns our documentation so we can evaluate how best to improve our docs. In the meantime, if you need assistance integrating this feature into your integration, [contact Technical Support](https://developer.paypal.com/braintree/help/).
