### ISSUE TITLE
> "https://api-m.paypal.com"

### ISSUE THREAD

**Issue by shango420** [braintree/braintree-web-drop-in#907]
> "https://api-m.paypal.com"
>  https://developer.paypal.com/reference/production/#:~:text=https%3A//api%2Dm.paypal.com

<script src="https://www.paypal.com/sdk/js?client-id=<Client-ID>&currency=USD">

_Publicado originalmente por @shango420 en https://github.com/shango420/rene-gilberto-hernandhttps-7pia71q9pgdm.runkit.shez-rojas/issues/6#issuecomment-1780150395_

**Comment by jplukarski** [comment]
Hey @shango420 , looks like this was opened by mistake? If you are having issues using the Braintree-Web Drop-In feel free to open an issue with details about your issue or [reach out to our support team](https://developer.paypal.com/braintree/help).

Thanks!
