### ISSUE TITLE
hoISeoI373mTmmqZxBUwNIeIGfEB4JQH5kNWfVB6tWxeiIUkTkw0EnHdwBJWRBOy

### ISSUE THREAD

**Issue by shango420** [braintree/braintree-web-drop-in#908]
hoISeoI373mTmmqZxBUwNIeIGfEB4JQH5kNWfVB6tWxeiIUkTkw0EnHdwBJWRBOy

_Publicado originalmente por @shango420 en https://github.com/actions/cache/issues/1266#issuecomment-1780277707_

**Comment by jplukarski** [comment]
Hey @shango420 , looks like this was opened by mistake? If you are having issues using the Braintree-Web Drop-In feel free to open an issue with details about your issue or [reach out to our support team](https://developer.paypal.com/braintree/help).

Thanks!

**Comment by shango420** [comment]
Hola @shango420, ¿parece que esto se abrió por error? Si tiene problemas para utilizar Braintree-Web Drop-In, no dude en abrir un problema con detalles sobre su problema o comunicarse con nuestro equipo de soporte.
