### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by tcetin** [braintree/braintree-web-drop-in#909]
### General information

* SDK/Library version: 1.40.2
* Environment: All
* Browser and OS: Chrome Version 118.0.5993.88 on all OS

### Issue description

Recently we have noticed there is a warning in the console and it says:
`button.js?date=2023-9-27:5078 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

This warning is shown in the browser console during the BT drop-in loading. 

Could you fix this issue?

The screenshot is here:
<img width="1190" alt="image" src="https://github.com/braintree/braintree-web-drop-in/assets/5071753/695b80ff-bb85-46c4-b65d-568de649c0a6">

**Comment by hollabaq86** [comment]
👋 I'm not seeing this same error message in Console logs when running our [Drop-in demo page](https://braintree.github.io/braintree-web-drop-in/), do have you any special options set when initializing your instance of the Drop-In, especially PayPal, ApplePay or GooglePay? 

Are you using a third-party library that has our drop-in library as a dependency? We don't have a `button.js` file in our library so I'm a little confused exactly where the root of this violation is.

**Comment by hollabaq86** [comment]
Going to close this issue since I haven't heard back. Feel free to create a new issue if you can give us more details
