### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by NinoSkopac** [braintree/braintree-web-drop-in#91]
```
Uncaught TypeError: Cannot read property 'getConfiguration' of undefined
    at Object.r [as sendEvent] (dropin.min.js:formatted:3946)
    at n._initialize (dropin.min.js:formatted:3782)
    at dropin.min.js:formatted:3909
    at dropin.min.js:formatted:614
r @ dropin.min.js:formatted:3946
n._initialize @ dropin.min.js:formatted:3782
(anonymous) @ dropin.min.js:formatted:3909
(anonymous) @ dropin.min.js:formatted:614
```

Happens sometimes when I destroy and re-create the drop in.

**Comment by crookedneighbor** [comment]
Thanks for the report. We're looking into it.

**Comment by crookedneighbor** [comment]
We had a typo in our error handling: https://github.com/braintree/braintree-web-drop-in/commit/0fce9759d66e6c11a06adafded40aa679b09d9dc

My guess is that whatever container you have selected isn't on your page when Drop-in is re-initialized. It Should have given you and error saying as much, but our typo was preventing it.

**Comment by NinoSkopac** [comment]
Hey, the error occurs when I **rapidly** destroy and re-create the dropin.

> My guess is that whatever container you have selected isn't on your page when Drop-in is re-initialized.

It **is** definitely on the page.

**Comment by crookedneighbor** [comment]
Yeah, that was just my guess.

There are three places where we had typos that would have caused the typeerror you were getting. The first, if you did not include a `selector` property, the second if your selector could not be found on the page. Obviously, those two options don't apply to you.

The third possibility is if the container found is not empty. <- I now suspect this is the error you were getting

Regardless, you should now get a better error response. You can either build `master` from the source yourself or wait till the next beta release comes out (hopefully this week).
