### ISSUE TITLE
Apple Pay svg size iPhone 15 series / macOS Sonoma

### ISSUE THREAD

**Issue by jtbas** [braintree/braintree-web-drop-in#911]
### General information

* SDK/Library version: 1.40.2 / current braintree demo site version
* Environment: all
* Browser and OS Safari 17/17.1 iPhone 15 series / Safari 17 macOS Sonoma

### Issue description

On newer Apple devices the Apple Pay svg for the braintree payment option is shrunk compared to the rest of the svgs: see images below
![image](https://github.com/braintree/braintree-web-drop-in/assets/84088128/4c5fc11b-f0a2-4a9d-936c-f4d2e65b12ea)
![image](https://github.com/braintree/braintree-web-drop-in/assets/84088128/638def6e-0658-4ec3-a47c-b8c886de5bd4)

Steps to reproduce: open the braintree demo (https://braintree.github.io/braintree-web-drop-in/) in the devices listed 

It looks like the logoApplePay svg has a width="24" on it.  In our site my current workaround is to remove the width with javascript in the callback function after calling dropin.create.

```
try {
    document.getElementById("logoApplePay").removeAttribute("width");
} catch (error) { }
```

**Comment by jplukarski** [comment]
Hey @jtbas , thanks for reporting this to us! I'm glad you were able to find a relatively simple workaround. We'll make a card in our backlog to get this fixed. For our internal tracking purposed -> 28713
