### ISSUE TITLE
Apple Pay UI goes disappears in a second

### ISSUE THREAD

**Issue by abuzer** [braintree/braintree-web-drop-in#918]
### General information

* SDK/Library version: web/dropin/1.41.0
* Environment: Sandbox
* Browser and OS: iPhone 14 pro max 17.1.2

### Issue description

Following this documentation to add Apple Pay: https://developer.paypal.com/braintree/docs/guides/drop-in/setup-and-integration/javascript/v3/

Tried all the possible methods mention but the UI appears and goes away
Or shows an error "Something went wrong on our side" 
https://naeems3.sg-host.com/braintree_php_example/public_html/index1.php

**Comment by hollabaq86** [comment]
👋 please [contact Technical Support](https://developer.paypal.com/braintree/help/) referencing this issue along with the following info:

- does this only happen on iPhone devices? Do you see the same behavior on safari desktop?

They'll also do some basic checks to make sure your test merchant is set up for Apple Pay correctly.
