### ISSUE TITLE
threeDSecure - Always Errors

### ISSUE THREAD

**Issue by Alchemy86** [braintree/braintree-web-drop-in#928]
### General information

* SDK/Library version: 1.42.0
* Environment: Sandbox
* Browser and OS: Chrome

### Issue description

When creating a new setup, we are using the examples for 3d secure
https://developer.paypal.com/braintree/docs/guides/3d-secure/migration/javascript/v3/

But even with minimal information, when submitting the data the system will error the same way, outside of our control:

Uncaught (in promise) ReferenceError: charsToDecode is not defined
    at r.sanitizeUrl (three-d-secure-bank-frame.min.html?showLoader=true:1:3583)
    at three-d-secure-bank-frame.min.html?showLoader=true:1:50611
    
    The initial value of u in this method shows as: 'https://1merchantacsstag.cardinalcommerce.com/MerchantACSWeb/creq.jsp'
    
    It will run, set charsToDecode to null.
    Then bomb out.
    
    Test Card: 4000111111111115

**Comment by jplukarski** [comment]
Hi @Alchemy86 ,

Thanks for writing in. We cannot recreate this issue using the same test card.

Can you please [write into our support team](https://developer.paypal.com/braintree/help) to assist you since this seems like an integration issue and not a bug within the SDK?

Thamnks
