### ISSUE TITLE
CardholerName prefill

### ISSUE THREAD

**Issue by BiroTb** [braintree/braintree-web-drop-in#930]
### General information

* SDK/Library version: 1.42.0
* Environment: Sandbox
* Browser and OS: Chrome

### Issue description

In Braintree integration, there's a supported functionality provided by braintree-web library where you can specify default values for certain fields within the overrides object, such as:

```
overrides: {
  fields: {
    cardholderName: {
      prefill: "cardholder name"
    }
  }
}
```

You can see it here (hosted-fields.js):
![image](https://github.com/braintree/braintree-web-drop-in/assets/73632218/0beadd45-ce06-4ee3-92a0-bec2789da7d3)

However, upon inspecting the braintree-web-dropin-ui library, it appears that this functionality is not included.

### Request:

I kindly request the addition of this functionality to the braintree-web-dropin-ui library. It would greatly enhance the user experience by allowing developers to prefill the cardholder name field, which is a feature available in the underlying braintree-web library.

Thank you for considering this enhancement request.

**Comment by jplukarski** [comment]
@BiroTb , thanks for reaching out with your question.

To clarify, the Braintree Web Drop-In actually uses Braintree Hosted Fields under the hood, and therefor this functionality actually does exist in the Drop-In.

You should be able to set field overrides like so:

```
        braintree.dropin.create({
          authorization: 'sandbox_w3yskrk8_7wgbnd5ss7jy6yy6',
          container: '#dropin-container',
          card: {
            cardholderName: true,
            overrides: {
              fields: {
                cardholderName: {
                  placeholder: "Walala Washington"
                }
              }
            },
          },
        }, function (createErr, instance) {
```

See our reference docs for our `dropin.create` method [here](https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create).

Let us know if you have any other questions.

**Comment by BiroTb** [comment]
Hi @jplukarski! 

Thank you for your answer. I checked it again and I realized the problem is in the @types/braintree-web-drop-in. There missing the cardholderName from the `cardCreateOption` model (index.d.ts):
 ![image](https://github.com/braintree/braintree-web-drop-in/assets/73632218/9f79117c-6439-4617-a55b-d6d8f7d82892)
Do you know where I can write about this issue?
