### ISSUE TITLE
Release with updated braintree-web?

### ISSUE THREAD

**Issue by mnightingale** [braintree/braintree-web-drop-in#931]
### General information

* SDK/Library version: v1.42.0
* Environment: production
* Browser and OS: NA

### Issue description

There has been an [unreleased](https://github.com/braintree/braintree-web-drop-in/blob/main/CHANGELOG.md#unreleased) change `Update braintree-web to 3.101.3` 2 months ago, and the last package release was 4 months ago.

[braintree-web v3.102.0](https://github.com/braintree/braintree-web/releases/tag/3.102.0) has since been released and by my count there have been 8 `braintree-web` releases since drop-in was last published.

Please can we get the braintree-web dependency updated and published on npmjs and https://js.braintreegateway.com/web/dropin/ ?

Going forward is there anyway this package could stay current with braintree-web?

**Comment by ibooker** [comment]
We just released Braintree Web Drop-In v1.43.0 with updated dependencies.
* [GitHub](https://github.com/braintree/braintree-web-drop-in/releases/tag/v1.43.0)
* [NPM](https://www.npmjs.com/package/braintree-web-drop-in/v/1.43.0)

We strive to keep the two libraries mostly* in sync.  However, you're right; we needed to update this one.  Thanks for your feedback.

Note: not all `braintree-web` releases affect `braintree-web-drop-in`.
